### ISSUE TITLE
Remove all jquery from the library

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#132]

**Comment by VinSpee** [comment]
I tend to agree with @soyuka here. What do we gain by replacing native dropdowns with Bootstrap dropdowns? Same for Buttons and Popovers. I think

Requiring an entire opinionated UI toolkit drastically restricts your user-base immediately – why not just use the native elements?

**Comment by hamilton** [comment]
@soyuka sorry for the delay in responding to your comment. I think it'd make sense to go with native javascript to the extent that we can. I think our general philosophy about IE support is "If D3 doesn't care, we don't care" given our library is built on top of D3.

re: popovers, I think that having a default popover is really important. Most of our users don't want to replace it. But having the ability to change the popover would be fine, as long as it doesn't mess with the 90% "I just want this goddamn thing to work without thinking about it" case. With that in mind, I say we should probably just pull out the jquery from the popover code, and we can moving forward have custom popover functionality in some way, when we have a bit more time to think about it.

Finally, re: Datatables, we're not interested in replicating that lib at all - they go above and beyond what most folks need for basic data reporting, I think, and in other ways they don't go far enough.

Thanks for the work!

**Comment by almossawi** [comment]
@VinSpee Having removed the dependency on Bootstrap, we pulled out three Bootstrap plugins (popover, tooltip, dropdown) so that our dashboards would continue to work. We've no objections to refining or replacing any of that code so long as we don't impact the user experience.

To be clear, the library doesn't require Bootstrap. The examples page uses Bootstrap's stylesheet to help with layout.

**Comment by almossawi** [comment]
@soyuka Wonderful work :)

Thank you very much.

**Comment by soyuka** [comment]
Thanks for the review! I'll take the time as soon as I get some!

**Comment by almossawi** [comment]
@hamilton Take a look at this, when you get the chance, to make sure we're on the same page. I've added a ``show_tooltips`` option that's set to true for now, which bypasses the jquery tooltip and popover code when set to false. That leaves just buttons, which use ``bootstrap_dropdown.js``.

This is a potentially liminal fix, with the final one being one of the ones proposed earlier in the conversation.

**Comment by almossawi** [comment]
@dandehavilland and anyone else, feel free to weigh in with your thoughts. This is currently the state of things (from the wiki):

>The library depends on [D3](http://d3js.org) and [jQuery](http://jquery.com/). As of v2.3, if you do not wish to use jQuery, set [show_tooltips](https://github.com/mozilla/metrics-graphics/wiki/Graphic#show_tooltips) to false, either globally in ``metricsgraphics.js``, or within ``MG.data_graphic``. Only tooltips and [buttons](https://github.com/mozilla/metrics-graphics/wiki/Button-Layout) depend on jQuery.

To me, this would satisfy the subset of users who don’t want to use jQuery.

**Comment by benschwarz** [comment]
@almossawi Agree. I think we've arrived at a great result here.

**Comment by dandehavilland** [comment]
Looks good to me - nice work!
