### ISSUE TITLE
chart supporting three axes

### ISSUE THREAD

**Issue by raluca-elena** [mozilla/metrics-graphics#138]
In our current dashboard(telemetry dashboard) we have a case where we would need a chart with both left and right Y axes.
Could you guys look into that as it would be really really useful.

**Comment by dgilperez** [comment]
I know ticket is closed, but I wanted to +1 to this feature. I think it's a very common feature and it's preventing us to use the library :( 

Our use case: charting accumulated values with daily increments for user signups. And then for some other KPIs in our dashboard. Once the accumulated value is way larger as the daily values, the second chart won't show. Of course, we can use two separated charts. But we still feel this should be possible in metrics-graphics. 

Any chance to reopen?

**Comment by nikos** [comment]
@dgilperez ...a possible work-around we are currently exploring is leveraging a logarithmic scale on the y axis to display two dimensions which are different by a factor 100-1000. It depends probably to the target audience if you can get them convenient with the logarithmic scale though?

**Comment by dgilperez** [comment]
Thanks @nikos! Not really the same since the data to compare might be of a linear nature but very different in scale ... but this would be an improvement nevertheless .

**Comment by satshabad-cr** [comment]
Would it be possible to write a plugin to do this? I need to generate a graph with multiple Y axis that is very common in the domain of my company.

**Comment by BenRomberg** [comment]
We've successfully implemented a workaround for this:
- Divide the data of the line you want to adjust by a factor.
- Multiply the values by the same factor using `y_rollover_format`:

```
        y_rollover_format: function(d) {
            if (d.index === 1) {
                return (d.value * FACTOR).toFixed(2);
            }
            return d.value.toFixed(2);
        }
```

The X-Axis won't match the line affected by the factor, but at least the rollover text will.
