### ISSUE TITLE
Allow for broken line charts

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#162]
Following up on the discussion in issue #137, we sometimes have the need to show a time series that has missing observations that we don't want to handle by showing them as zeros or interpolate between the two closest observations, but rather strip the missing date range and show the line as broken.

**Comment by avilaj** [comment]
I would love to see this.

**Comment by awashbrook** [comment]
We have people using today stuck with canvas based flotcharts products, who for some data sets are just sticking with points rather than line altogether...to avoid misrepresenting the data, so this is a killer feature to move to d3 and MG.

**Comment by almossawi** [comment]
@awashbrook The plan is to work on this next week.

**Comment by almossawi** [comment]
Perhaps something like this? Where we'd process the data object as though ``missing_is_zero`` were enabled, and then modify the line so that missing ranges are hidden and their rollovers are disabled:

```javascript
if (args.missing_is_hidden) {
    var the_line = svg.select('.mg-main-line.mg-line' + (line_id) + '-color');
    var bits = the_line.attr('d').split('L');
    var zero = args.scales.Y(0);
    var dasharray = [];

    var x_y, 
        x_y_plus_1,
        x,
        y,
        x_plus_1,
        y_plus_1,
        segment_length,
        cumulative_segment_length = 0;

    if (bits[0].charAt(0) === 'M') {
        bits[0] = bits[0].slice(1);
    }

    for (var j = 0; j < bits.length - 1; j++) {
        x_y = bits[j].split(',');
        x_y_plus_1 = bits[j + 1].split(',');
        x = Number(x_y[0]);
        y = Number(x_y[1]);
        x_plus_1 = Number(x_y_plus_1[0]);
        y_plus_1 = Number(x_y_plus_1[1]);

        segment_length = Math.sqrt(Math.pow(x - x_plus_1, 2) + Math.pow(y - y_plus_1, 2));

        if (y_plus_1 == zero && y != zero) {
            console.log("switching off line");
            dasharray.push(cumulative_segment_length);
            cumulative_segment_length = segment_length;
        } else if (y_plus_1 != zero && y == zero) {
            console.log("switching on line");
            dasharray.push(cumulative_segment_length += segment_length);
            cumulative_segment_length = 0;
        }
        else {
            cumulative_segment_length += segment_length;
        }
    }

    dasharray.push(the_line.node().getTotalLength() - dasharray[dasharray.length - 1]);

    svg.select('.mg-main-line.mg-line' + (line_id) + '-color')
        .attr('stroke-dasharray', dasharray.join());
}
```

Area enabled for clarity:

![screen shot 2015-02-11 at 10 59 40 pm](https://cloud.githubusercontent.com/assets/980049/6163122/a7d82d04-b242-11e4-91cb-6365e41c3214.png)

**Comment by almossawi** [comment]
Feel free to reopen if it causes a rash.

**Comment by cdchan** [comment]
I just tried this since we also have data with lots of missing values, and with `missing_is_hidden: true`, my true zero values are being hidden, which is problematic.

Also, is there any way to have this work with a data point explicitly set to missing? I have a use case where I'd like to have the date in the graph, but just display no points / lines over that date. Something like a data point where `count: null`?

**Comment by almossawi** [comment]
@cdchan Fair point. Let me take a look tomorrow morning.

**Comment by almossawi** [comment]
@cdchan Would you mind commenting on that last commit.

![screen-shot-2015-02-13-at-11 18 17-am- 2](https://cloud.githubusercontent.com/assets/980049/6193660/6b3819b4-b372-11e4-867d-874d6ed2b73b.png)

**Comment by cdchan** [comment]
Looks good - that fixed the zero value issue for me.
