### ISSUE TITLE
There is currently no default formatting for time series < 1 day (hours, minutes, seconds, etc.)

### ISSUE THREAD

**Issue by jdarling** [mozilla/metrics-graphics#192]
Needs to be a way to show data and group it by less than the day.  Or to have a string value on the X Axis to be displayed by.

As an example, if you want to give a single 6 hour window of data grouped by every 30 minutes, you can't do that with the library today.

**Comment by hamilton** [comment]
@jdarling I just made some sensible defaults for x-axis time scales that are less than a second. They should just automatically work. For now I'm going to close this particular issue unless this crops up again.

**Comment by glukgluk** [comment]
Is there a option to show the date in 24h format and not am/pm?

**Comment by almossawi** [comment]
@glukgluk You can change the specifier on [this line](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/x_axis.js#L385) to any one of the ones [listed here](https://github.com/mbostock/d3/wiki/Time-Formatting), so for instance:

```javascript
yformat = d3.time.format('%H');
```
