### ISSUE TITLE
Stacked graph

### ISSUE THREAD

**Issue by ghost** [mozilla/metrics-graphics#193]
Any plans for stacked area graph? If stacked graph is currently supported, then maybe make an example of that. Not supporting stacked is keeping me from using this great looking product!

**Comment by jimis** [comment]
In systems monitoring (e.g. CPU, RAM utilisation) it is very common to use stacked area graphs. I found a nice reasoning of [why and when it is desired](https://www.datadoghq.com/blog/timeseries-metric-graphs-101/#when-to-use-stacked-area-graphs). In short:
* To check both the sum and the contribution of each of its parts at a glance
* To see how a finite resource is being utilized
