### ISSUE TITLE
Browserify Support / package.json

### ISSUE THREAD

**Issue by namuol** [mozilla/metrics-graphics#200]
Adding a `package.json` would be helpful for those using browserify to build their frontend apps. Cheers!

**Comment by jjzazuet** [comment]
Hi. Was this package published to the NPM registry? I tried searching but found nothing. Thanks!

**Comment by almossawi** [comment]
Now it is :)

**Comment by jjzazuet** [comment]
Ah! Much appreciated! :+1: Thanks!
