### ISSUE TITLE
allow brushing / onclick support

### ISSUE THREAD

**Issue by mayuroks** [mozilla/metrics-graphics#244]
I have seen the example graphs. I couldn't zoom into any graphs. For eg if I have graph of CPU usage of a server for 1 year. I would like to be able to zoom in to a particular day of a particular month.

Can anyone explain how thats done ?

**Comment by dandehavilland** [comment]
@hamilton @almossawi I'm looking at implementing something like this for a project I'm currently working on, so I could take this on over the next coming weeks. Before I start though, it would be good to come up with a clear spec that would be useful as a part of MG - do you have anything in mind?

This was suggested as a reference: http://play.grafana.org/#/dashboard/db/grafana-play-home

**Comment by bbirand** [comment]
I'd also be very interested in seeing this as a feature. Dygraphs is another example that supports this, maybe could be an inspiration:
http://dygraphs.com/

**Comment by almossawi** [comment]
@dandehavilland Somehow, I missed your comment. Apologies.

@bbirand Here's @dandehavilland's work-in-progress implementation: http://dandehavilland.github.io/mg-with-extensions. More here: https://github.com/mozilla/metrics-graphics/pull/351

**Comment by almossawi** [comment]
Closing, seeing as this feature is now available as an extension: http://metricsgraphicsjs.org/examples.htm#addons
https://github.com/dandehavilland/mg-line-brushing
