### ISSUE TITLE
add a note about how metricsgraphics.js compares to other libraries

### ISSUE THREAD

**Issue by harobed** [mozilla/metrics-graphics#253]
Hi,

I suggest to append a note in README or github wiki about Metrics-graphics vs http://www.flotcharts.org/

I use Flotcharts to display my metrics, what benefit can I obtain tu use your solution ?

Best regards,
Stéphane

**Comment by frank-carnovale** [comment]
Hi, understood there are too many libraries out there to expect you to maintain a comparison chart.  But can you give more background on what you mean by "principled".  Thanks.
