### ISSUE TITLE
Graph exceeds y-axis

### ISSUE THREAD

**Issue by miles-gt** [mozilla/metrics-graphics#258]
I do not have a max_y set, and the y-axis inferred from the data set is far below the maximum value in the dataset (2.4M)...this ultimately cuts the graph off.  Any thoughts on why this is happening?

![image](https://cloud.githubusercontent.com/assets/10076502/5301040/4e592060-7ba3-11e4-9bc3-8132273260ee.png)

**Comment by Benco1** [comment]
Oh man, this saved me so much headache! I apparently overlooked this point in the docs and was seeing inconsistent behavior. :+1:
