### ISSUE TITLE
Naming of series data / multi-line chart

### ISSUE THREAD

**Issue by afandian** [mozilla/metrics-graphics#277]
Sorry if I've missed this in the docs.

I'm able to supply data as multiple series (e.g. 

    var data3 = [
    {"date": new Date("2012-01-01T00:00:00.000Z"), "count": 20}, 
    {"date": new Date("2012-01-02T00:00:00.000Z"), "count": 10},
    {"date": new Date("2012-01-03T00:00:00.000Z"), "count": 40}];

    var data4 = [
    {"date": new Date("2012-01-02T00:00:00.000Z"), "count": 10}, 
    {"date": new Date("2012-01-03T00:00:00.000Z"), "count": 60},
    {"date": new Date("2012-01-04T00:00:00.000Z"), "count": 30}];

    data_graphic({
        data: [data3, data4],
        target: '#ufo-sightings',
        x_accessor: 'date',
        y_accessor: 'count'
    });

This displays fine, with different colours for each series. So I suppose it's supported (although not mentioned in the docs).

It looks like I can't supply a legend or label for each series. Is it possible to add this?

**Comment by Svjard** [comment]
+1

**Comment by danieljacobarcher** [comment]
+1

**Comment by hamilton** [comment]
@almossawi This is nearly complete. Figured out the bounding rect issues, but could use another set of eyes on the multiline examples page (bottom graph).

**Comment by almossawi** [comment]
@hamilton I made a few minor changes to the style. I'll test the functionality on Monday:

1. Moved the styles to the css file and switched the font-size units to rem
2. Used ``fill`` instead of ``stroke`` for the labels so that they look crisper
3. Set the group's class name to ``mg-line-legend`` to make it consistent with the other groups

**Comment by almossawi** [comment]
@hamilton I fixed two issues and added a new test:

1. ``mg-line-legend`` wasn't being cleared on multiple calls to the same target element
2. labels  were overlapping when their lines were identical

Otherwise, it looks good. Do you want to go ahead and update the wiki?

**Comment by hamilton** [comment]
@almossawi yep happy to update it. Thanks for the style changes / fixes! Will close this out once it is updated.
