### ISSUE TITLE
Reimplement 'data missing' background image as an svg path

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#284]

**Comment by almossawi** [comment]
@hamilton A second pair of eyes would be good. Let me know your thoughts.

**Comment by hamilton** [comment]
Looks pretty good - thanks for taking that on. I might make a few small changes tomorrow, in particular adding margins to the missing chart type so they visually cohere a little more with non-missing charts

**Comment by almossawi** [comment]
Sounds good :+1:
