### ISSUE TITLE
Append date support on histogram xaxis

### ISSUE THREAD

**Issue by harobed** [mozilla/metrics-graphics#287]
Hi,

this two graphs : 
1. 
![line](https://cloud.githubusercontent.com/assets/230143/5528053/452e0ae0-8a04-11e4-8a67-1da1abef482a.png)
2. 
![histogram](https://cloud.githubusercontent.com/assets/230143/5528057/49773270-8a04-11e4-9d99-e9a8e1d5ea7b.png)

In 1. you can see some date on xaxis.

In 2. date isn't displayed on xaxis

Suggest : append date support on histogram xaxis.

**Comment by hamilton** [comment]
Yep - good catch.

**Comment by zedix** [comment]
@hamilton This issue still exists in v2.2.0. Should this be reopen ?

**Comment by hamilton** [comment]
Hey @zedix - would you mind posting your code? I'm having trouble reproducing the original issue now.

We fixed this issue in a previous version. On our [examples page](http://metricsgraphicsjs.org/examples.htm) under the title "Histograms can be time series as well" in the histograms section, you can see an example with Date support.

**Comment by zedix** [comment]
Sure ! but I've just figured out myself that the issue was caused by a chart_type `line`simply changed to graph `histogram'` __without__ adding `binned: true`.

Example below:
```js
MG.data_graphic({
      chart_type: 'line',
      //binned: true, <-- required when chart_type "line" is changed to "histogram"
      data: MG.convert.date([{"count":"60","day":"2015-01-03"},{"count":"70","day":"2015-01-04"},{"count":"80","day":"2015-01-08"}], 'day'),
       full_width: true,
       height: 400,
       target: '#js-graph',
       x_accessor: 'day',
       y_accessor: 'count'
})
```
I'm quite new to metrics-graphics so I've just missed it, sorry about that ! I confirm histograms are working well with dates now, thanks you.
