### ISSUE TITLE
handling dataset of length 1

### ISSUE THREAD

**Issue by greg0ire** [mozilla/metrics-graphics#289]
I'm using metrics graphics to show how many products were consumed by a user on a given date. When the users has only consumed on one date, the graph is missing an the console shows the following error message : 

> TypeError: args.data[0][0] is undefined

I think either metrics-graphics should support datasets of length 1, or this error message should replaced with something higher level, like 
> metrics-graphics does currently not support datasets of length 1

**Comment by almossawi** [comment]
@greg0ire Apologies for the late reply. Would you mind verifying the fix.

**Comment by greg0ire** [comment]
ping me if I forget to do that by tomorrow afternoon

**Comment by almossawi** [comment]
What does your data object look like when there's just one data point?

You should be able to see the change in, say, [examples/interactive-demo.htm](https://github.com/mozilla/metrics-graphics/blob/master/examples/interactive-demo.htm) by changing the dataset to 

``[
  {
    "year": "1945",
    "sightings": 6
  }
]
``

**Comment by greg0ire** [comment]
console.log show `Array [ Object ]`, and the pane on the right of the firefox debugger makes me say that it is something like this : `[ {"date" : <a Date object, not a string like you>, "quantity": 1}]`

**Comment by almossawi** [comment]
I can't quite see what the culprit might be in your case--if you have a live demo, that would be helpful. Unless your data object is an empty array, it ought to work. Here's a screenshot of your use-case using interactive-demo from master.

![screen shot 2015-01-12 at 10 59 13 am](https://cloud.githubusercontent.com/assets/980049/5708938/16cb5472-9a4a-11e4-8a63-9262b1a5d761.png)

**Comment by greg0ire** [comment]
No live demo, no, sorry… I'm debugging right now and I think it is a mistake in my code.

**Comment by greg0ire** [comment]
The problem seems to be that the loop that starts like this `for (var d = new Date(from); d <= upto; d.setDate(d.getDate() + 1)) {` in `processLine()` is never entered

`new Date(from)` gives `Date 2014-10-23T22:00:00.000Z` and upto is `Date 2014-10-22T22:00:00.000Z` (one day before ?!?). The day specified in th the data is `2014-10-22`

**Comment by greg0ire** [comment]
ping @almossawi

**Comment by greg0ire** [comment]
This comment looks funny, it explains why `from > upto` : 

> //we'll be starting from the day after our first date

**Comment by almossawi** [comment]
Aah, my bad. I thought this has been resolved.

I'm away today, so I'll take a look first thing tomorrow morning.

**Comment by almossawi** [comment]
@greg0ire Would you mind verifying, please. ``missing_is_zero`` only makes sense when we have a range of two or more observations, and so we're skipping that for the case of a single one.

Feel free to reopen if you continue to see this error.

**Comment by greg0ire** [comment]
Sorry for the delay, I can confirm it works beautifully! Thanks a lot!
