### ISSUE TITLE
max_y not being respected

### ISSUE THREAD

**Issue by zachberger** [mozilla/metrics-graphics#290]
In addition to #257 max_y is not being respected. 

```
    MG.data_graphic({
        data: getData(),
        target: '#graph',
        x_accessor: 'x',
        y_accessor: 'y',
        min_y: 3.5, 
        max_y: 4.0,
    })
```

is being rendered as 

![screen shot 2014-12-29 at 2 27 00 am](https://cloud.githubusercontent.com/assets/1634878/5566834/8798d740-8f02-11e4-896e-3801f8dd3d72.png)

**Comment by almossawi** [comment]
Would you mind sharing your dataset, as I'm unable to reproduce the bug. Do you get the same issue when running it [here](http://metricsgraphicsjs.org/interactive-demo.htm)?

**Comment by zachberger** [comment]
The data can be found here:
http://pastebin.com/dqGYZ9Nw

```
MG.data_graphic({
        data: getRatioData(),
        target: '#graph',
        x_accessor: 'x',
        y_accessor: 'y',
        width: 600,
        min_y: 3.5, 
        max_y: 4,
    })
```

Which is rendered as 
![screen shot 2015-01-02 at 4 15 22 pm](https://cloud.githubusercontent.com/assets/1634878/5599744/ba37cd50-929a-11e4-9043-053b32ae6647.png)

**Comment by almossawi** [comment]
I see it now. It occurs only when min_y is also set and for certain values of said option. I'll take a look.

**Comment by zachberger** [comment]
Thanks!
