### ISSUE TITLE
When value changes quickly wrt multiple points are plotted for the same time

### ISSUE THREAD

**Issue by zachberger** [mozilla/metrics-graphics#291]
The data being represented is a function of time, however that is not being represented in the graph. Multiple values are being plotted for the same time. 

![screen shot 2014-12-30 at 1 00 16 am](https://cloud.githubusercontent.com/assets/1634878/5576108/f325f750-8fbf-11e4-99cf-95c2acd7e4d8.png)

**Comment by almossawi** [comment]
Closing. Feel free to reopen if appropriate.

**Comment by zachberger** [comment]
Dataset: http://pastebin.com/dqGYZ9Nw

Is being rendered as:
![screen shot 2015-01-02 at 4 15 22 pm](https://cloud.githubusercontent.com/assets/1634878/5599750/eefa955e-929a-11e4-8da5-243faa2d3360.png)

The data passes the vertical line test, however when rendered on Dec 29 and Dec 31 it does not. The line appears to go backwards. I've exaggerated the pattern with these arrows. 
![screen shot 2015-01-02 at 4 15 22 pm](https://cloud.githubusercontent.com/assets/1634878/5599774/756fd626-929b-11e4-9a8e-54f6c326632b.png)

**Comment by almossawi** [comment]
The default [interpolation function](https://github.com/mozilla/metrics-graphics/wiki/Graphic#interpolate) is likely the culprit. Try setting it to linear or monotone:

**Comment by zachberger** [comment]
Thank you- linear is getting me what I'd like.
