### ISSUE TITLE
$svg.find('.mg-x-axis') bad 'getElementsByClassName' with later jQuery

### ISSUE THREAD

**Issue by philderbeast** [mozilla/metrics-graphics#297]
http://metricsgraphicsjs.org
http://metricsgraphicsjs.org/examples.htm

Both these pages reference jQuery 1.11.1. I have tried metrics with jQuery 2.1.1 and it fails to render in IE. Here's the error and the call stack ...
 ```
SCRIPT438: Object doesn't support property or method 'getElementsByClassName'
push.apply( results, context.getElementsByClassName( m ) ); Sizzle, jquery.js, line 800
jQuery.find( selector, self[ i ], ret ); find, jquery.js, line 2690
$svg.find('.mg-x-axis').remove(); x_axis, metricsgraphics.js, line 1427
```

I think you would be able to reproduce this problem by changing the jQuery CDN reference. I was able to have my chart render by rolling my jQuery reference back from 2.1.1 version to 1.11.1.

**Comment by almossawi** [comment]
Thanks, please refer to the comments in #310.

**Comment by almossawi** [comment]
With the recent commits, this issue should now be resolved. Feel free to reopen the issue if that is not the case.

PR #267
PR #346
