### ISSUE TITLE
Background image of missing-data graph was removed from the dist.

### ISSUE THREAD

**Issue by mouradmourafiq** [mozilla/metrics-graphics#298]
`mg-missing` is missing in the css file, and `missing-data.png` was removed from the package, but the [doc](https://github.com/mozilla/metrics-graphics/wiki/Graphic#chart_type) still suggests to use this class.

I saw that there's an issue [#284](https://github.com/mozilla/metrics-graphics/issues/284) to use SVG path, but this should only be available in the near future.

**Comment by almossawi** [comment]
I've updated the documentation. You actually no longer need to set a class name of 'missing' to the target element--specifying the chart type 'missing-data' suffices.

**Comment by mouradmourafiq** [comment]
:+1:
