### ISSUE TITLE
Allow markers to be clickable

### ISSUE THREAD

**Issue by alexzender** [mozilla/metrics-graphics#299]
If marker definition supports onclick event property in addition to label and date - then it would be possible to build richer functionality around such markers/milestones.

An alternative could be to add html support for the 'label' field so that developer could make links on her own.

**Comment by rolandgeider** [comment]
I just wanted to open a similar issue. Is this something that is planed or does it not fit into the library's philosophy?

**Comment by almossawi** [comment]
@rolandgeider That would certainly be a nice feature to have. We have our hands full with a few other tasks at the moment, so we can either come back to this at a later date, or, preferably, review a PR for it :)

**Comment by almossawi** [comment]
I've made a start on this.

```javascript
var clicker = function() {
    console.log('hello');
};

var markers = [{
    year: 1964,
    label: 'Marker 1',
    click: clicker
},
{
    year: 2008,
    label: 'Marker 2'
}]
  
MG.data_graphic({
  data: JSON.parse($('.data textarea').val()),
  markers: markers,
  target: ".result",
  x_accessor: "year",
  y_accessor: "sightings",
  interpolate: "monotone"
});
```

**Comment by rolandgeider** [comment]
Nice! If I can help with testing, just ask

**Comment by almossawi** [comment]
@rolandgeider Great, feel free to report any issues.

I've added an example under _Annotations_.
