### ISSUE TITLE
Confidence band not deleted in a multi line scenario upon updating the chart

### ISSUE THREAD

**Issue by ank19** [mozilla/metrics-graphics#303]
After updating a chart with multiple lines and a confidence band the old confidence band does not get deleted. I did not try to understand the metricsgraphics.js file in detail, but it seems to be that in line 2083 of metricsgraphics.js just the .first() band gets deleted, whereas in line 2131 the class mg-confidence-band is added to each dataset. Deleting all occurences of mg-confidence-band in line 2083 solves the problem for me.
Can you pls. have a look at it? Thank you.

**Comment by almossawi** [comment]
Could you please verify that it's fixed.

**Comment by ank19** [comment]
Thank you, Ali, for the quick solution.
I confirm that the problem is fixed.
