### ISSUE TITLE
y_extended_ticks opacity

### ISSUE THREAD

**Issue by dandehavilland** [mozilla/metrics-graphics#305]
Is this value intentionally so small, or should it actually be `0.7`?

https://github.com/mozilla/metrics-graphics/blob/8f2b44331adde3d7eda4f89e5e1dd5d81c66ffa5/dist/metricsgraphics.css#L135

**Comment by almossawi** [comment]
Indeed.

**Comment by dandehavilland** [comment]
Great, thanks :)
