### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#306]
Add unit tests to the test suite created in #238.

**Comment by dandehavilland** [comment]
Hi @almossawi - are these tests passing for you? Everything passes for me in Chrome but I'm getting about a dozen errors in PhantomJS. Just wondering if it's my machine or a PhantomJS problem.

**Comment by dandehavilland** [comment]
This is resolved by #314. PhantomJS is a great tool, but it's unforgiving in those edge cases where browsers usually a little more flexible.

**Comment by almossawi** [comment]
@dandehavilland Aah yes, I wasn't running them in PhantomJS. I'll be sure to do that, going forward.

Thanks for the PR :+1:

**Comment by almossawi** [comment]
I've done a first pass of adding unit tests (thanks @dandehavilland for pushing for this). These ones cover basic functionality and the regressions that we've seen in the past. I'll make it a point to do a second pass next week.
