### ISSUE TITLE
Wrong version in the bower.json of v2.0 archive

### ISSUE THREAD

**Issue by yutannihilation** [mozilla/metrics-graphics#307]
I saw this warning when installing metrics-graphics by bower.

```bash
$ bower install metrics-graphics
bower metrics-graphics#*    not-cached git://github.com/mozilla/metrics-graphics.git#*
bower metrics-graphics#*       resolve git://github.com/mozilla/metrics-graphics.git#*
bower metrics-graphics#*      download https://github.com/mozilla/metrics-graphics/archive/v2.0.0.tar.gz
bower metrics-graphics#*       extract archive.tar.gz
bower metrics-graphics#*      mismatch Version declared in the json (1.1.0) is different than the resolved one (2.0.0)
bower metrics-graphics#*      resolved git://github.com/mozilla/metrics-graphics.git#2.0.0
```

`v2.0` archive has version 1.1.0 in the bower.json.

```bash
$ wget https://github.com/mozilla/metrics-graphics/archive/v2.0.0.tar.gz
$ tar xf v2.0.0.tar.gz
$ grep -A1 -B1 version metrics-graphics-2.0.0/bower.json
  "name": "metrics-graphics",
  "version": "1.1.0",
  "main": [
```

The reason is that `v2.0` tag is on the commit [`1fd9d61`](https://github.com/mozilla/metrics-graphics/commit/1fd9d618b5d9c5c78db99d976be85bffb6afd9a6), while bower.json is updated to v2.0 by the commit [`083a9ba`](https://github.com/mozilla/metrics-graphics/commit/083a9ba61d6d81805b197e3f630bec0633bd3e5d#diff-0a08a7565aba4405282251491979bb6b).

**Comment by almossawi** [comment]
Indeed, the release had the older version number by mistake. Shouldn't happen again.

**Comment by yutannihilation** [comment]
I know this is not your intention.

> Shouldn't happen again.

Is it difficult just to move `v2.0` tag on the right commit (I think [`95f093e`](https://github.com/mozilla/metrics-graphics/commit/95f093e0efec18fc3f875f0de3344e60587f6d57) is)? If so, never mind, I close this issue and wait for the next release :)

**Comment by almossawi** [comment]
The docs deem that [an "insane" thing](http://schacon.github.io/git/git-tag.html) so--barring any opposing views--I'd prefer to not mess with it :) 

![Detour](http://buttersafe.com/comics/2008-10-23-Detour.jpg)

**Comment by yutannihilation** [comment]
What a scare...lol

I got it. I close this issue. Thanks for your response and the funny picture!
