### ISSUE TITLE
jQuery 2.x does not work

### ISSUE THREAD

**Issue by RusAlex** [mozilla/metrics-graphics#310]
Will it be possible to get rid of jQuery 1.x dependency and stick with 2.x ?

**Comment by almossawi** [comment]
The plan is to remove the jquery dependency altogether in v2.1 (see https://github.com/mozilla/metrics-graphics/issues/132)

**Comment by almossawi** [comment]
Out of interest, what error do you get with jquery 2.x? I've tried it with jquery 2.1.3 and don't see any errors.

**Comment by RusAlex** [comment]
It's IE9 

It has no getElementsByClassName function support in document context.

Thanks

**Comment by almossawi** [comment]
Thanks. As mentioned, we'll be removing the jquery dependency in v2.1. I'll keep the issue open and track it under #297 until then.

**Comment by almossawi** [comment]
Updated jQuery in examples to 2.1.3. See the update in #297 and [the note in the readme](https://github.com/mozilla/metrics-graphics#dependencies) for further details.
