### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by dandehavilland** [mozilla/metrics-graphics#311]
Hi @almossawi, @hamilton - with testing in mind, I think it'd be useful to setup a CI server like [Wercker](http://www.wercker.com) or [Travis](https://travis-ci.org/). Something like [code climate](https://codeclimate.com) might also be useful. These are all totally free for open-source projects.

**Comment by almossawi** [comment]
Hi @dandehavilland, Yes, that sounds great. We've used Travis and coveralls in the past.
