### ISSUE TITLE
bug: Lines with only one value are invisible in line char (thougn dots are shown on activating)

### ISSUE THREAD

**Issue by blazkovicz** [mozilla/metrics-graphics#313]
I suggest to show dots for such lines permanently.
Additional problem: if there is only one line with a single point - that point is really hard to show: cursor must be on exact same x-coordinate as point to view it.

**Comment by almossawi** [comment]
Hi @blazkovicz To your second point, the rollover rectangle ought to cover the entire area when there's a single data point, as in the screenshot below.

![screen-shot-2015-01-15-at-9 16 37-am](https://cloud.githubusercontent.com/assets/980049/5762543/916596a8-9c97-11e4-889a-15317599e827.jpg)

**Comment by blazkovicz** [comment]
@almossawi you're right, I copied code to plnkr and point is shown easily (also, graphic in my app is shown with just single vertical and horizontal line, not a wet like in plnkr, I've to check that).
But still, not every user will have insight to move mouse over an empty graphic to see that it has some data actually.

**Comment by blazkovicz** [comment]
Ah, after so much effort to reproduce bug, I go to the metrics-graphics interactive and see, that it was pretty simple: 
![1](https://cloud.githubusercontent.com/assets/4517837/5773550/96a1fc8a-9d85-11e4-9689-cf457751a490.PNG)

**Comment by almossawi** [comment]
Oh, the fix [is in master](https://github.com/mozilla/metrics-graphics/blob/master/examples/interactive-demo.htm) (see #289), and hence not yet deployed :) It will be in the upcoming v2.1.

To your first point, I think you're right. Hamilton and I chatted about that too, and decided that it wouldn't be an issue to break the pattern for line charts for datasets of length 1. I'll take a look at that on Monday.

**Comment by blazkovicz** [comment]
Thank you!

**Comment by almossawi** [comment]
@blazkovicz Done.

**Comment by blazkovicz** [comment]
Thanks! Is update available already?

**Comment by almossawi** [comment]
The change is committed. We're planning to release v2.1 on Thursday,
January 22.

**Comment by blazkovicz** [comment]
In version 2.1 several lines each of single dot are still invisible until hover.

**Comment by almossawi** [comment]
@blazkovicz Aah yes, multi-line ones ought to be updated to work in the same way. I'll take care of that.

**Comment by blazkovicz** [comment]
Next code gives error on data with color mapping, because there is no object ".mg-line1-color":

    //if the dataset is of length 1, trigger the rollover for our solitary rollover rect
    if (args.data.length == 1 && args.data[0].length == 1) {
        d3.select('.mg-rollover-rect .mg-line1-color')
            .on('mouseover')(args.data[0][0], 0);
    }

**Comment by almossawi** [comment]
@blazkovicz I've assigned it to v2.2 so that I don't lose track of it. I'll get to this as soon a possible.

**Comment by almossawi** [comment]
The first issue, where a single line might have an identifier greater than one ought to be fixed.

The fix for multi-lines is incomplete, as it doesn't currently show multiple dots in the case where there are multiple lines that have a solitary observation. I might have to revisit this after v2.2.

**Comment by almossawi** [comment]
Tacking in #361
