### ISSUE TITLE
implement clipPaths for plot areas when the data graphic limits are smaller than the plot element

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#320]

**Comment by hamilton** [comment]
@almossawi let me know if anything here seems amiss. I could have sworn there was an issue already made for this but maybe there wasn't.

**Comment by almossawi** [comment]
@hamilton Looks good to me.

**Comment by hamilton** [comment]
@almossawi realizing I didn't think about other chart types for this

**Comment by inh3** [comment]
This change has broken the ability to use a jQuery or DOM element as the target option.

Function mg_strip_punctuation expects a string as the input parameter.
