### ISSUE TITLE
the full_width: true doesn't seem to play nicely with bootstrap

### ISSUE THREAD

**Issue by tmatei** [mozilla/metrics-graphics#323]
The full width works nicely when it's in a div by itself, but if you wrap it within a div that reduces the width then there are issues.

Works:
```
<div id="fake_users2"></div>
```

Chart is bigger than the title:
```
    <div class="row">
        <div class="col-sm-11"
            <div id="fake_users2"></div>
        </div>
    </div>
```

**Comment by hamilton** [comment]
Could you post a screenshot to demonstrate this? The title is not svg, so it doesn't scale according to the graph.

**Comment by hamilton** [comment]
Also, agreed that the full-width option doesn't play nicely with bootstrap, but that's because the columns in Bootstrap typically don't scale with window size.

**Comment by tmatei** [comment]
![Screenshot]
(http://i.imgur.com/PlIEoMI.png)

Let me know if you need more info.

**Comment by hamilton** [comment]
Hi - took a look at what you have. The idea of using full_width is that it will automatically scale to the width of the parent element, not the width of the window. In the case of your screenshot, it looks like it is appropriately expanding all the way to col-sm-11.
