### ISSUE TITLE
hide line instead of zero

### ISSUE THREAD

**Issue by glukgluk** [mozilla/metrics-graphics#328]
Is there any way to hide a line when no datas are avaible?
As in example "Handling Missing Data" but not only at the beginning or end.
I can set the Line to zero : http://abload.de/img/metricsodca4.jpg but its not realy nice.

other question: is there a way to make a custom labeld x axis? "piece 1" instead of 1 for example.

Sry for my bad english ;-)

**Comment by almossawi** [comment]
Hi there, Your first point is likely related to https://github.com/mozilla/metrics-graphics/issues/264, which we're planning to work in v2.2. That's scheduled for release next month.

To your second point, unless I've misunderstood it, you can use [x_label](https://github.com/mozilla/metrics-graphics/wiki/Axes#x_label) to specify a custom x-axis label.

**Comment by glukgluk** [comment]
To my second point, i have a x axis in the format dd.mm.yy hh:mm. At the moment i only manipulate the "mouseover" text to show the x value (show picture above). I know that metrics-graphics doesen't support date time axis but i build it self. The only thing i want to do is to manipulate the showed x axis unit.

**Comment by almossawi** [comment]
Aah, if you mean the ability to have scales that are less than one day, the library does now support that. We'll be releasing v2.1 later today, which includes support for automatic time formatting--see the examples [here](https://github.com/mozilla/metrics-graphics/blob/master/examples/js/main.js#L63) and  conversation here: #192.

To set custom units on your x-axis ticks, take a look at [xax_units](https://github.com/mozilla/metrics-graphics/wiki/Axes#xax_units) or [xax_format](https://github.com/mozilla/metrics-graphics/wiki/Axes#xax_format).

**Comment by hamilton** [comment]
@glukgluk did Ali answer your question?

**Comment by glukgluk** [comment]
Yes. Version 2.1 solve my date problem. But i realy miss the hide line function for missing datas  ;-)

**Comment by almossawi** [comment]
@glukgluk This should help: https://github.com/mozilla/metrics-graphics/issues/162

v2.2 is scheduled for release on Monday.
