### ISSUE TITLE
display none and full_width true

### ISSUE THREAD

**Issue by michaelwittig** [mozilla/metrics-graphics#339]
Hi,

I have

```
<div style="display: none"><div class="result"></div></div>
```

and

```
MG.data_graphic({
	data: [...],
	width: 800,
	height: 600,
	full_width: true,
	target: ".result",
	x_accessor: "timestamp",
	y_accessor: "value",
	min_y_from_data: true,
	interpolate: "linear"
});
```

![Preview](http://s7.postimg.org/s5z2wc71n/Bildschirmfoto_2015_01_26_um_11_42_11.png)

Looks like a problem when the target element has 0x0 dimensions on calling MG.data_graphic?

How to use charts in tabs, accordion or stuff like this?

**Comment by hamilton** [comment]
Hello - I'm having trouble reproducing your issue on my end. Could you supply a js fiddle?

One possibility is if you are loading charts in an accordion, in whatever library you're using I'm sure you have a callback. full_width:true right now looks at the width of the parent element, so if it is none, then the width will be NaN (vs. 0). If you are expanding an accordion element for the first time, I'd suggest just drawing the graph at that point.

**Comment by almossawi** [comment]
Closing, as the issue hasn't been updated in a while. Feel free to reopen if necessary.
