### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by rubenv** [mozilla/metrics-graphics#341]
Hi,

We're currently looking into metrics-graphics and it looks like it might save us a ton of work compared to just using D3.

How easy/hard is it to plug in our own graph types? We have a number of specific chart types that we'd love to build, but I doubt that these will be of value for upstream submission.

We could fork the library, add our stuff and maintain the copy, but that's less than ideal.
Is there an API to hook in chart types?

**Comment by almossawi** [comment]
Hi there,

Here's some info about chart types: https://github.com/mozilla/metrics-graphics/wiki/Chart-Types

In order to add a new type:
1. Add it to ``src/js/charts/charts``
2. In ``src/js/common/data_graphic.js``, add the default options to ``defaults.your_new_chart_type``, merge them with other defaults as necessary and define the call order
3. [Build](https://github.com/mozilla/metrics-graphics/#contributing)

Happy to help further.

**Comment by rubenv** [comment]
That's not very handy for our purposes. Perhaps I wasn't very clear in my wording.

Ideally we'd:
1. Install `metrics-graphics` via bower
2. Write some new chart types  in our own application and hook it in

This gives us the option to update `metrics-graphics` whenever it changes upstream.

Off-course we could just take the library and add things as you described, but that means we have to merge each and every upstream change manually, which could be quite painful.

**Comment by almossawi** [comment]
Not at the moment. If you'd like to submit a PR, we'd be happy to review it.

**Comment by dandehavilland** [comment]
Some kind of plugin system would be really cool. Allowing third-party additions would give MG scope to reach a much wider audience while maintaining the principles of the core (even some of the additions I've been working on would feel more at home in a plugin), but it's a big job, likely involving major refactoring, and there are plenty of issues in the queue. Could be something to think about for the next major release?

**Comment by almossawi** [comment]
Sure, I'd be up for that.

I'll have my hands tied with some other work for the rest of the week, but will be back to carry on working on the outstanding issues for v2.2 starting Monday.

**Comment by almossawi** [comment]
Closing, as we're tracking the enhancement in #344.
