### ISSUE TITLE
Trouble trying to create a multi line chart

### ISSUE THREAD

**Issue by jjzazuet** [mozilla/metrics-graphics#342]
Hi. Like the title says. I'm just trying to plot multiple time series.

http://jsfiddle.net/s35jg7ko/1/

I'm getting: "TypeError: e is null". I'm doing something wrong.

Also, it would be better to have separate, standalone examples in the examples section on the site so that we can get more quickly to the least amount of code that can show a feature.

Thanks!

**Comment by almossawi** [comment]
Two things:

1) Since the dates are strings, convert them before calling ``MG.data_graphic``, like so:

```javascript
for (var i = 0;i < data.length; i++) {
    data[i] = MG.convert.date(data[i], 'date');
}
```

2) Define your target div like so:

```html
<div class="mg-chart"></div>
```

**Comment by jjzazuet** [comment]
OK fiddle updated. http://jsfiddle.net/s35jg7ko/3/

Still gives the same error on Firefox. So I'm still doing something wrong XD.

Thanks for the help!!

**Comment by almossawi** [comment]
See point 2 above. Don't use shorttags for your target div.

**Comment by jjzazuet** [comment]
OMG I'm an idiot. That worked.

Thanks again! ;)
