### ISSUE TITLE
Multi-line chart with no data in first set of series breaks rendering

### ISSUE THREAD

**Issue by dprotaso** [mozilla/metrics-graphics#347]
I've noticed the library makes a few assumptions about data format based on the first entry in the series

ie. https://github.com/mozilla/metrics-graphics/blob/master/src/js/misc/process.js#L13

In my case an API is returning the following data:
[ 
  [], 
  [ {...}, {...}, ..],
  [ {...}, {...}, ..]
]

This breaks rendering since it thinks my data is an unnested array of arrays and hence modifies the format.

Any thoughts on how to get around this? I'm aware I could remove the empty array prior - but one criteria I have is to always show the legends in a specific order even if there is no data present.

**Comment by almossawi** [comment]
Are you able to move that first element to, say, the end, to mitigate the issue?

@hamilton I'm guessing this is something that we'll want to think about? I've moved it to v2.3 since I suspect we won't have time to work on it before Monday.
