### ISSUE TITLE
styling font sizes on axis labels?

### ISSUE THREAD

**Issue by yosemitebandit** [mozilla/metrics-graphics#354]
Thanks for this awesome tool -- is there a correct way to change the font sizes?

I am trying to increase the size of the axis labels but the month and years labels are colliding: http://jsfiddle.net/hk63jfg3/1

**Comment by almossawi** [comment]
This will fix it for you, but I'd like to take a closer looker at that, so let's keep this issue open for now.

```javascript
$(function () {
    MG.data_graphic({
        title: "sightings",
        data: [{
            'date': new Date('2014-10-28'),
            'value': 7
        }, {
            'date': new Date('2014-11-01'),
            'value': 12
        }, {
            'date': new Date('2014-11-02'),
            'value': 18
        }],
        width: 400,
        height: 250,
        target: '#sightings',
        x_accessor: 'date',
        y_accessor: 'value',
        bottom: 35
    });
});

d3.selectAll('.mg-year-marker text')
    .attr('transform', 'translate(0, 8)');
```

**Comment by almossawi** [comment]
I'm going to close this. This, to me, seems like something that ought to be done by modifying margins and buffers, as above.

@hamilton Feel free to reopen if you think otherwise.

**Comment by matteocontrini** [comment]
Similar issue. Having to adjust many margins is definitely not ideal and really annoying! I don't get why the text is so small by default. Bigger seems more modern to me

![image](https://cloud.githubusercontent.com/assets/2164763/8891227/76b35978-3321-11e5-989f-d461d5cc06d1.png)
