### ISSUE TITLE
v2.1.0 breaks bootstrap dropdown menu

### ISSUE THREAD

**Issue by wgmueller** [mozilla/metrics-graphics#355]
I have a dropdown menu which breaks with MG v2.1.0.  I'm using bootstrap 3.1.1 and jasny bootstrap extension.

&lt;div class="btn-group"&gt;
    &lt;a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"&gt;Select a method&lt;span class="caret"&gt;&lt;/span&gt;&lt;/a&gt;
    &lt;ul class="dropdown-menu"&gt;
    .....
    &lt;/ul&gt;
  &lt;/div&gt;

**Comment by almossawi** [comment]
Are you loading Bootstrap first? See the note [here](https://github.com/mozilla/metrics-graphics#download-package).

**Comment by wgmueller** [comment]
Yes I'm loading Bootstrap then jquery then d3 then MG.

**Comment by almossawi** [comment]
I take it you mean jQuery, then Bootstrap? I'm unable to reproduce the error with v2.1. See attached.

![screen-shot-2015-02-11-at-8 00 59-am](https://cloud.githubusercontent.com/assets/980049/6150465/7abb8c36-b1c4-11e4-9b7f-132d41b2009f.png)

**Comment by wgmueller** [comment]
I think it is related to jasny bootstrap extension.

**Comment by wgmueller** [comment]
I loaded bootstrap twice ... once on the bottom of the page for speed and didn't notice it.

**Comment by deonthomasgy** [comment]
had this same issue, had to move d3 and metricsgraphics.js after bootstrap.js
