### ISSUE TITLE
When the x-axis starts too far to the right it can be confusing / an eyesore

### ISSUE THREAD

**Issue by passcod** [mozilla/metrics-graphics#358]
From #257:

![screenshot](https://cloud.githubusercontent.com/assets/1065169/5948284/f7253230-a743-11e4-8c84-30a6d673934d.PNG)
> As noted above, axis line does not cover the entire scale by design, though I'd like to look into that next week, since having ticks start so far to the right on occasion can be a bit of an eyesore.
— @almossawi 

Maybe have the first x-tick be off by default if it's farther than N% of the total width away from the y-axis? Or N pixels?

**Comment by almossawi** [comment]
"But you said it was an eyesore!"

Now I can't ignore this issue :) I'll spend some time on it after this upcoming Monday release.

Have a nice weekend.

**Comment by almossawi** [comment]
I've made a start on this. @hamilton Would you mind taking a look.

If ``xax_start_at_min`` is set, the x-axis' first tick starts at _min_ rather than the auto-generated ticks' first element.

**Comment by almossawi** [comment]
Having chatted with @hamilton, we'll be turning off the year marker by default to avoid the issue raised by the original poster. A new option called ``show_year_marker`` can be set to true to turn the year markers back on.

**Comment by passcod** [comment]
Thank you :)
