### ISSUE TITLE
When there are multiple lines with single observations, show multiple dots

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#361]
#313

**Comment by almossawi** [comment]
Terribly sorry for the late reply. Only just getting back to working on some of the outstanding issues.

I've made a start on this. See commit and attachments.
![screen shot 2015-03-26 at 1 13 17 pm](https://cloud.githubusercontent.com/assets/980049/6855983/15ae74d0-d3ba-11e4-8630-553306ef4334.png)
![screen shot 2015-03-26 at 1 13 00 pm](https://cloud.githubusercontent.com/assets/980049/6855984/15afef40-d3ba-11e4-8d9e-b269cd095975.png)
![screen shot 2015-03-26 at 1 12 52 pm](https://cloud.githubusercontent.com/assets/980049/6855985/15b11366-d3ba-11e4-875a-f73fe65cde2b.png)

**Comment by almossawi** [comment]
Feel free to reopen if you notice any issues. Seems to be working fine.

**Comment by blazkovicz** [comment]
Next code throws error on data with single line that has color mapping to id = 2:

    //remove active datapoint text on mouse out, except if we have a single point
    svg.selectAll('circle.mg-line-rollover-circle.mg-area' + (d.line_id) + '-color')
        .style('opacity', function() {
            if (args.data[d.line_id - 1].length == 1) {
                return 1;
            }
            else {
                return 0;
            }
        });

I do not undestand why you use line_id is array index, they have no correlation when color mapping is used.

**Comment by blazkovicz** [comment]
I don't know if this bug should be here, nevertheless: next code throws error on data with empty lines:

    //if the dataset is of length 1, trigger the rollover for our solitary rollover rect
    if (args.data.length == 1 && args.data[0].length == 1) {
        svg.select('.mg-rollover-rect rect')
            .on('mouseover')(args.data[0][0], 0);
    } else if (args.data.length > 1) {
        //otherwise, trigger it for an appropriate line in a multi-line chart
        for (var i = 0; i < args.data.length; i++) {
            if (args.data[i].length == 1) {
                svg.selectAll('.mg-voronoi .mg-line' + (i + 1) + '-color')
                    .on('mouseover')(args.data[i][0], 0);
            }
        }
    }

**Comment by blazkovicz** [comment]
Why x-labels not shown with predefined x_min and x_max when data contains only one point?
Also, graphics is built incorrectly when data contains lines with length === 0.

**Comment by almossawi** [comment]
Hi @blazkovicz, To your first two points, yes, I'm embarrassed to say that I forgot that we even have that feature. Thankfully, this isn't a public forum. ``line_id `` is so that a single-data-item line doesn't disappear on mouseout in the case of a multi-line chart.

![screen shot 2015-04-09 at 3 41 25 pm](https://cloud.githubusercontent.com/assets/980049/7078542/ee429e10-dece-11e4-82e3-b149076c4612.png)


I've committed a change that fixes the issue with the use-case that I have, using this code:

```javascript
var data = [];
    data[0] = [{'date': new Date('2015-03-05'), 'value': 12000}];
    data[1] = [{'date': new Date('2015-03-06'), 'value': 35000}];
    data[2] = [{'date': new Date('2015-03-07'), 'value': 23000},{'date': new Date('2015-03-08'), 'value': 20000}];

    MG.data_graphic({
        data: data,
        target: '#qunit-fixture',
        max_data_size: 5,
        custom_line_color_map: [3,4,5]
    });

    MG.data_graphic({
        data: data,
        target: '#qunit-fixture',
        max_data_size: 5,
        custom_line_color_map: [1,2,3]
    });
```

Please check to see if it does the same for you. If not, would you mind sharing your code and dataset so that I can replicate the bug? Similarly for your last point, as I'm unable to replicate it.

**Comment by blazkovicz** [comment]
I expected to see 12 x-labels here (each for a month), but what I got:
![image](https://cloud.githubusercontent.com/assets/4517837/7082450/cfd77b72-df6d-11e4-98a6-62d8e793a1e6.png)

**Comment by blazkovicz** [comment]
Also, it's just a suggestion, but coloring active datapoint with the line color would be more informative. See the graphics above - which one of two dots is active?

**Comment by blazkovicz** [comment]
PS can not get this update through bower :( It gives me old code for 2.3.0

**Comment by almossawi** [comment]
Yes, that's a bug, caused by [this line](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/x_axis.js#L520). We ought to forgo that block if min_x and max_x have been set. I'll open a new issue for that, and another one for your second comment.

Is there a way you might be able to test using metricsgraphics.min.js from master?

**Comment by blazkovicz** [comment]
Yes, I copied the file from github. First issues have been fixed, thank you.

**Comment by almossawi** [comment]
@blazkovicz Glad to hear it. v2.4 is planned for release on Thursday, the 16th.
