### ISSUE TITLE
Support for data roll off

### ISSUE THREAD

**Issue by phubner** [mozilla/metrics-graphics#362]
This is more of a question. I tried to create a dynamically loaded graph that would roll off the oldest data and only keep past 10 points. I couldn't find a way to do this in the documentation or examples, but have found some hints that others have been able to do this. 

My graph code
```javascript
MG.data_graphic({
  data: filterData,
  target: '#'+guid,
  max_data_size: 10, // thought this might be the key, but didn't seem to change the graph
  interpolate: 'linear',
  y_extended_ticks: true,
  x_accessor: 'date',
  y_accessor: 'value',
  width: torso.width,
  height: torso.height * 4 / 5
});
```

Thanks.

**Comment by almossawi** [comment]
Hi there, Is there a reason why you aren't able to splice ``filterData`` so that it contains just the ten most recent elements from last time plus the elements from the new ``filterData`` before calling ``MG.data_graphic``?

**Comment by phubner** [comment]
I could, I was just curious if MG had that logic built in. I couldn't really gather the meaning of max_data_size options and what they are really intended for.

Will the graph update smoothly if I just splice `filterData` ?

**Comment by almossawi** [comment]
[max_data_size](https://github.com/mozilla/metrics-graphics/wiki/Graphic#wiki-max_data_size) is only if you use a custom color map. See [this](https://metrics.mozilla.com/telemetry-prototype/) dashboard, for instance. Specifically, [this](https://github.com/mozilla/telemetry-dashboard-prototype/blob/master/js/main.js#L311).

Yes, the transitions will be super-smooth on update :) Update ``filterData`` and call ``MG.data_graphic`` on the same target element.
