### ISSUE TITLE
support for multiple series with bar chart

### ISSUE THREAD

**Issue by awashbrook** [mozilla/metrics-graphics#363]
have multi line charts working fine, starting to work with bar charts

only the first series of bar charts is rendered, are you planning to support rendering of multiple series

see below multi series rendered with MG and NVD3

![screen shot 2015-02-20 at 10 07 16](https://cloud.githubusercontent.com/assets/1024064/6284479/4a9b471e-b8e8-11e4-888b-48d28e144808.png)

some discussion but only regarding stacking in  #193

**Comment by almossawi** [comment]
@hamilton Is this something that you've had in mind for bar charts?

**Comment by almossawi** [comment]
I chatted with @hamilton about this. This isn't something that we're planning to implement for bar charts. 

If it's a feature that's important to you, and you would really like to stick with ``MetricsGraphics`` rather than use an alternative library, you should be able to make that change quite easily by modifying ``src/charts/bar.js``.

**Comment by Valve** [comment]
A pity to hear that

**Comment by luisrudge** [comment]
@almossawi why you don't want to support that?

**Comment by luisrudge** [comment]
http://demos.telerik.com/kendo-ui/bar-charts/multiple-axes charts like this are super handy to have

**Comment by hamilton** [comment]
@luisrudge @Valve Why not just use line charts? Seems like a much better data representation than having tow bars complete.

**Comment by luisrudge** [comment]
Sorry. My fault. I ignored the fact that this is only about bar chart. Does metrics graphics supports multiple series on bar charts?

**Comment by almossawi** [comment]
@luisrudge Take a look at @dandehavilland's work: #344 #359 

That will allow for custom charts, like the one you're interested in, to be added with ease.

**Comment by luisrudge** [comment]
thanks @almossawi

**Comment by awashbrook** [comment]
Thanks for your consideration @almossawi
