### ISSUE TITLE
Line chart with visible points

### ISSUE THREAD

**Issue by macpak** [mozilla/metrics-graphics#364]
Hi,

Can I have a line chart where data points are always visible (not just when I move mouse over them) ?

**Comment by almossawi** [comment]
You can add something like this to [line.js:60](https://github.com/mozilla/metrics-graphics/blob/master/src/js/charts/line.js#L60):

```javascript
svg.selectAll('circle-' + line_id)
    .data(args.data[i]).enter()
        .append('circle')
            .attr('class', 'mg-area' + (line_id) + '-color')
            .attr('cx', args.scalefns.xf)
            .attr('cy', args.scalefns.yf)
            .attr('r', 2);
```

![screen shot 2015-02-23 at 1 30 14 pm](https://cloud.githubusercontent.com/assets/980049/6337961/2b65ffea-bb60-11e4-828a-c92c71a509ef.png)

**Comment by benrolfe** [comment]
This works great if you add it to line [2393](https://github.com/mozilla/metrics-graphics/blob/master/dist/metricsgraphics.js#L2393)
