### ISSUE TITLE
Inverse of missing_is_zero  

### ISSUE THREAD

**Issue by Pascal66** [mozilla/metrics-graphics#365]
![missing_zero](https://cloud.githubusercontent.com/assets/3041616/6314726/5aa6524a-b9ea-11e4-872c-dc26f2f83b37.png)

I mean: a zero_is_missing option,  then we can use missing_is_hidden after.

So a zero_is_hidden as an option can work with multiline.

**Comment by almossawi** [comment]
You ought to get the desired effect if you set ``missing: true`` on those zero-values in your data object before calling ``MG.data_graphic``.

**Comment by Pascal66** [comment]
Mean that ????
for (var i=0; i < data.length; i++) {
	if (data[i] === 0) {
		data[i].value = 'missing: true';
	}
}

with missing_is_hidden: true,

**Comment by almossawi** [comment]
Before calling ``MG.data_graphic``

```javascript
data.forEach(function(d) {
    if(d.value === 0) {
        d.missing = true;
    }
});
```
Set ``missing_is_hidden`` to true in ``MG.data_graphic`` to hide missing values.

**Comment by Pascal66** [comment]
thank you, but... all line are hidden, and show 0 value in legend for all points.

**Comment by almossawi** [comment]
Inspect the data object in your console to make sure that only zero-elements have an extra ``missing`` attribute set to true, which should be the case.

If you're able to share your dataset and ``MG.data_graphic`` call, I'd be happy to take a look.

**Comment by Pascal66** [comment]
I found somthing :  fisrt
{"date":"2015-02-03T06:58:00.000Z","value":0,"value1":2.4030884543008573,"value2":4.057663664238833,"value3":4.8388803326009615,"missing":true}

so value is 0, but value1, value2 and value3 are not, so all the lines are set to missing

second : I've two arrays so the code was : 
data[0].forEach(function(d) {
    if(d.value === 0) {
        d.missing = true;
    }
});

**Comment by almossawi** [comment]
As you note, it won't work in the case where you're specifying multiple y_accessors. You'll have to modify your dataset so that each time-series is in a separate array, then run the above on each one. You seem to have already done that.

Feel free to reopen if you need further help.

**Comment by Pascal66** [comment]
Sorry, i've  to reopen it, because it doesnt work, even in test page 
So..  dataset is : 

 [{"date":"2015-01-30 14:58","value":5.8},{"date":"2015-01-31 10:28","value":7.6},{"date":"2015-01-31 16:00","value":7.6},{"date":"2015-01-31 16:19","value":7.6},{"date":"2015-01-31 16:20","value":7.6},{"date":"2015-01-31 17:41","value":7.6},{"date":"2015-01-31 18:06","value":7.6},{"date":"2015-01-31 18:08","value":7.6},{"date":"2015-01-31 18:11","value":7.6},{"date":"2015-01-31 18:13","value":7.6},{"date":"2015-02-01 08:27","value":0.5},{"date":"2015-02-01 08:37","value":0.5},{"date":"2015-02-01 08:45","value":0.5},{"date":"2015-02-01 09:03","value":0.5},{"date":"2015-02-01 09:10","value":0.5},{"date":"2015-02-01 09:12","value":0.5},{"date":"2015-02-01 09:25","value":0.5},{"date":"2015-02-01 09:34","value":0.5},{"date":"2015-02-01 09:45","value":0.5},{"date":"2015-02-01 09:55","value":0.5},{"date":"2015-02-01 10:13","value":0.5},{"date":"2015-02-01 10:32","value":0.5},{"date":"2015-02-01 10:45","value":0.5},{"date":"2015-02-01 10:48","value":0.5},{"date":"2015-02-01 11:51","value":0.5},{"date":"2015-02-01 13:23","value":0.5},{"date":"2015-02-01 13:36","value":0.5},{"date":"2015-02-01 14:35","value":0.5},{"date":"2015-02-01 14:48","value":0.5},{"date":"2015-02-01 14:51","value":0.5},{"date":"2015-02-01 14:52","value":0.5},{"date":"2015-02-01 15:25","value":0.5},{"date":"2015-02-01 16:07","value":0.5},{"date":"2015-02-01 16:13","value":0.5},{"date":"2015-02-01 16:33","value":0.5},{"date":"2015-02-01 16:35","value":0.5},{"date":"2015-02-01 16:50","value":0.5},{"date":"2015-02-01 16:55","value":0.5},{"date":"2015-02-01 16:56","value":0.5},{"date":"2015-02-02 07:55","value":0.8},{"date":"2015-02-02 08:05","value":0.8},{"date":"2015-02-02 08:31","value":0.8},{"date":"2015-02-02 08:53","value":0.8},{"date":"2015-02-02 08:57","value":0.8},{"date":"2015-02-02 09:12","value":0.8},{"date":"2015-02-02 09:26","value":0.8},{"date":"2015-02-02 09:29","value":0.8},{"date":"2015-02-02 09:40","value":0.8},{"date":"2015-02-02 09:51","value":0.8},{"date":"2015-02-02 10:55","value":0.8},{"date":"2015-02-02 11:02","value":0.8},{"date":"2015-02-02 12:48","value":0.8},{"date":"2015-02-02 12:51","value":0.8},{"date":"2015-02-02 13:00","value":0.8},{"date":"2015-02-02 13:06","value":0.8},{"date":"2015-02-02 13:49","value":0.8},{"date":"2015-02-02 13:53","value":0.8},{"date":"2015-02-02 14:03","value":0.8},{"date":"2015-02-02 14:05","value":0.8},{"date":"2015-02-02 14:06","value":0.8},{"date":"2015-02-02 14:45","value":0.8},{"date":"2015-02-02 15:10","value":0.8},{"date":"2015-02-02 15:21","value":0.8},{"date":"2015-02-02 15:35","value":0.8},{"date":"2015-02-02 16:11","value":0.8},{"date":"2015-02-02 16:19","value":0.8},{"date":"2015-02-02 16:28","value":0.8},{"date":"2015-02-02 16:34","value":0.8},{"date":"2015-02-02 16:36","value":0.8},{"date":"2015-02-02 16:39","value":0.8},{"date":"2015-02-02 17:33","value":0.8},{"date":"2015-02-02 17:52","value":0.8},{"date":"2015-02-02 17:53","value":0.8},{"date":"2015-02-02 17:55","value":0.8},{"date":"2015-02-02 18:03","value":0.8},{"date":"2015-02-02 18:08","value":0.8},{"date":"2015-02-02 20:02","value":0.8},{"date":"2015-02-03 07:58","value":0},{"date":"2015-02-03 08:13","value":0},{"date":"2015-02-03 08:14","value":0},{"date":"2015-02-03 08:18","value":0},{"date":"2015-02-03 08:24","value":0},{"date":"2015-02-03 08:27","value":0},{"date":"2015-02-03 08:39","value":0},{"date":"2015-02-03 08:51","value":0},{"date":"2015-02-03 08:57","value":0},{"date":"2015-02-03 11:29","value":0},{"date":"2015-02-03 13:07","value":0},{"date":"2015-02-03 13:22","value":0},{"date":"2015-02-03 13:31","value":0},{"date":"2015-02-03 13:41","value":0},{"date":"2015-02-03 13:59","value":0},{"date":"2015-02-03 15:08","value":0},{"date":"2015-02-03 15:27","value":0},{"date":"2015-02-03 16:53","value":0},{"date":"2015-02-03 17:01","value":0},{"date":"2015-02-03 17:15","value":0},{"date":"2015-02-03 17:17","value":0},{"date":"2015-02-03 17:26","value":0},{"date":"2015-02-03 17:28","value":0},{"date":"2015-02-03 17:40","value":0},{"date":"2015-02-03 17:53","value":0},{"date":"2015-02-03 18:12","value":0},{"date":"2015-02-03 18:24","value":0},{"date":"2015-02-03 18:25","value":0},{"date":"2015-02-03 18:27","value":0},{"date":"2015-02-03 18:30","value":0},{"date":"2015-02-03 18:33","value":0},{"date":"2015-02-03 18:35","value":0},{"date":"2015-02-04 09:17","value":4.8},{"date":"2015-02-04 10:51","value":4.8},{"date":"2015-02-04 11:02","value":4.8},{"date":"2015-02-04 11:04","value":4.8},{"date":"2015-02-04 11:47","value":4.8},{"date":"2015-02-04 11:48","value":4.8},{"date":"2015-02-04 11:52","value":4.8},{"date":"2015-02-04 12:53","value":4.8},{"date":"2015-02-04 13:18","value":4.8},{"date":"2015-02-04 13:24","value":4.8},{"date":"2015-02-04 13:36","value":4.8},{"date":"2015-02-04 13:54","value":4.8},{"date":"2015-02-04 16:55","value":4.8},{"date":"2015-02-04 16:59","value":4.8},{"date":"2015-02-04 17:21","value":4.8},{"date":"2015-02-04 17:39","value":4.8},{"date":"2015-02-04 17:43","value":4.8},{"date":"2015-02-04 17:47","value":4.8},{"date":"2015-02-04 17:59","value":4.8},{"date":"2015-02-04 18:04","value":4.8},{"date":"2015-02-04 22:11","value":4.8},{"date":"2015-02-05 05:46","value":0},{"date":"2015-02-05 08:21","value":0},{"date":"2015-02-05 08:44","value":0},{"date":"2015-02-05 08:50","value":0},{"date":"2015-02-05 09:12","value":0},{"date":"2015-02-05 09:16","value":0},{"date":"2015-02-05 09:17","value":0},{"date":"2015-02-05 11:20","value":0},{"date":"2015-02-06 08:43","value":0.3},{"date":"2015-02-06 09:47","value":0.3},{"date":"2015-02-06 10:47","value":0.3},{"date":"2015-02-06 11:05","value":0.3},{"date":"2015-02-06 11:24","value":0.3},{"date":"2015-02-06 12:04","value":0.3},{"date":"2015-02-06 12:20","value":0.3},{"date":"2015-02-06 12:36","value":0.3},{"date":"2015-02-06 12:40","value":0.3},{"date":"2015-02-06 12:43","value":0.3},{"date":"2015-02-06 12:51","value":0.3},{"date":"2015-02-06 12:58","value":0.3},{"date":"2015-02-06 13:00","value":0.3},{"date":"2015-02-06 13:03","value":0.3},{"date":"2015-02-06 13:11","value":0.3},{"date":"2015-02-06 13:14","value":0.3},{"date":"2015-02-06 13:18","value":0.3},{"date":"2015-02-06 13:21","value":0.3},{"date":"2015-02-06 13:23","value":0.3},{"date":"2015-02-06 13:58","value":0.3},{"date":"2015-02-07 07:33","value":0},{"date":"2015-02-07 09:14","value":0},{"date":"2015-02-07 09:41","value":0},{"date":"2015-02-07 09:49","value":0},{"date":"2015-02-07 09:50","value":0},{"date":"2015-02-07 09:53","value":0},{"date":"2015-02-07 10:08","value":0},{"date":"2015-02-07 10:11","value":0},{"date":"2015-02-07 10:13","value":0},{"date":"2015-02-07 10:19","value":0},{"date":"2015-02-07 10:23","value":0},{"date":"2015-02-07 10:29","value":0},{"date":"2015-02-07 10:32","value":0},{"date":"2015-02-07 15:08","value":0},{"date":"2015-02-07 15:14","value":0},{"date":"2015-02-07 15:42","value":0},{"date":"2015-02-07 15:56","value":0},{"date":"2015-02-07 16:10","value":0},{"date":"2015-02-07 16:51","value":0},{"date":"2015-02-07 16:52","value":0},{"date":"2015-02-07 17:03","value":0},{"date":"2015-02-07 17:17","value":0},{"date":"2015-02-07 17:40","value":0},{"date":"2015-02-07 17:51","value":0},{"date":"2015-02-07 18:15","value":0},{"date":"2015-02-08 08:51","value":0},{"date":"2015-02-08 09:14","value":0},{"date":"2015-02-08 09:19","value":0},{"date":"2015-02-08 09:23","value":0},{"date":"2015-02-08 09:45","value":0},{"date":"2015-02-08 09:54","value":0},{"date":"2015-02-08 09:58","value":0},{"date":"2015-02-08 10:05","value":0},{"date":"2015-02-08 10:09","value":0},{"date":"2015-02-08 10:24","value":0},{"date":"2015-02-09 05:52","value":0},{"date":"2015-02-12 06:19","value":0},{"date":"2015-02-12 15:21","value":0},{"date":"2015-02-13 02:51","value":0},{"date":"2015-02-14 13:46","value":0},{"date":"2015-02-14 13:57","value":0},{"date":"2015-02-15 16:42","value":0.3},{"date":"2015-02-16 07:50","value":2.8},{"date":"2015-02-17 07:19","value":0},{"date":"2015-02-17 09:16","value":0},{"date":"2015-02-18 13:17","value":0},{"date":"2015-02-18 13:20","value":0},{"date":"2015-02-20 11:35","value":0},{"date":"2015-02-20 11:54","value":0},{"date":"2015-02-20 12:00","value":0},{"date":"2015-02-20 12:19","value":0},{"date":"2015-02-20 12:21","value":0},{"date":"2015-02-20 12:27","value":0},{"date":"2015-02-20 13:59","value":0},{"date":"2015-02-21 14:25","value":0},{"date":"2015-02-21 17:58","value":0},{"date":"2015-02-21 20:57","value":0},{"date":"2015-02-22 10:26","value":1.5},{"date":"2015-02-22 10:31","value":1.5},{"date":"2015-02-22 10:35","value":1.5},{"date":"2015-02-22 10:38","value":1.5},{"date":"2015-02-22 20:32","value":1.5},{"date":"2015-02-23 09:10","value":0},{"date":"2015-02-23 16:25","value":0},{"date":"2015-02-23 20:46","value":0},{"date":"2015-02-23 22:52","value":0},{"date":"2015-02-24 09:13","value":0.5},{"date":"2015-02-24 16:39","value":0.5},{"date":"2015-02-25 09:51","value":1.3},{"date":"2015-02-25 10:33","value":1.3},{"date":"2015-02-25 10:38","value":1.3},{"date":"2015-02-25 12:00","value":1.3},{"date":"2015-02-25 13:28","value":1.3},{"date":"2015-02-25 14:00","value":1.3},{"date":"2015-02-25 14:15","value":1.3},{"date":"2015-02-25 14:15","value":1.3},{"date":"2015-02-25 14:53","value":1.3},{"date":"2015-02-25 15:03","value":1.3},{"date":"2015-02-26 09:25","value":0.3},{"date":"2015-02-26 10:14","value":0.3},{"date":"2015-02-26 10:29","value":0.3},{"date":"2015-02-26 12:50","value":0.3},{"date":"2015-02-26 12:54","value":0.3},{"date":"2015-02-26 12:56","value":0.3},{"date":"2015-02-26 14:28","value":0.3},{"date":"2015-02-26 14:30","value":0.3},{"date":"2015-02-26 14:39","value":0.3},{"date":"2015-02-26 14:45","value":0.3},{"date":"2015-02-26 15:05","value":0.3},{"date":"2015-02-26 15:08","value":0.3},{"date":"2015-02-26 15:32","value":0.3},{"date":"2015-02-26 16:09","value":0.3},{"date":"2015-02-26 16:52","value":0.3},{"date":"2015-02-26 17:02","value":0.3},{"date":"2015-02-26 17:05","value":0.3},{"date":"2015-02-27 08:39","value":0.3},{"date":"2015-02-27 09:37","value":0.3},{"date":"2015-02-27 09:53","value":0.3},{"date":"2015-02-27 14:37","value":0.3},{"date":"2015-02-27 14:51","value":0.3},{"date":"2015-02-28 09:41","value":1.5},{"date":"2015-02-28 12:27","value":1.5},{"date":"2015-02-28 14:02","value":1.5},{"date":"2015-02-28 14:21","value":1.5},{"date":"2015-02-28 14:53","value":1.5}]

**Comment by Pascal66** [comment]
and call MG like that : 

var data = JSON.parse($('.data textarea').val());
data = MG.convert.date(data, 'date', '%Y-%m-%d %H:%M');

data.forEach(function(d) {
    if(d.value === 0) {
        d.missing = true;
    } 
});
		
MG.data_graphic({
  data: data,
  //missing_is_hidden: true,
  width: 400,
  height: 250,
  target: ".result",
  x_accessor: "date",
  y_accessor: "value",
  interpolate: "step"
});

**Comment by Pascal66** [comment]
If I set missing_is_hidden, nothing is displayed, 
I've tested if only 0.00 value are set to missing:true, and it's ok
