### ISSUE TITLE
line is going back

### ISSUE THREAD

**Issue by Pascal66** [mozilla/metrics-graphics#366]
![strange](https://cloud.githubusercontent.com/assets/3041616/6314738/8dfd5d82-b9ea-11e4-948a-ffbb350072dc.png)

**Comment by almossawi** [comment]
You'll want to change the interpolation function. See https://github.com/mozilla/metrics-graphics/issues/291.

**Comment by Pascal66** [comment]
Only 'step' work in my case

**Comment by almossawi** [comment]
Sorry, I didn't quite get whether you mean changing the interpolation function fixes the issue for you? If not, would you mind posting your dataset.

**Comment by Pascal66** [comment]
here is the data set : 

[[{"date":"2015-01-30 14:58","value":5.8,"value1":3.663136559546781,"value2":6.1812680303922525,"value3":5.444376996633585},{"date":"2015-01-31 10:28","value":7.6,"value1":2.3246407056931093,"value2":3.9234669978220587,"value3":5.488841890799771},{"date":"2015-01-31 16:00","value":7.6,"value1":2.3246407056931093,"value2":3.922831190857121,"value3":5.899953831183295},{"date":"2015-01-31 16:19","value":7.6,"value1":2.324923286566415,"value2":3.922831190857121,"value3":5.814670179492309},{"date":"2015-01-31 16:20","value":7.6,"value1":2.324923286566415,"value2":0.0,"value3":5.814670179492309},{"date":"2015-01-31 17:41","value":7.6,"value1":2.326336190932943,"value2":3.925374418716873,"value3":5.2896701794923064},{"date":"2015-01-31 18:06","value":7.6,"value1":2.326147803684073,"value2":0.0,"value3":5.366286744605137},{"date":"2015-01-31 18:08","value":7.6,"value1":2.326147803684073,"value2":0.0,"value3":5.366286744605137},{"date":"2015-01-31 18:11","value":7.6,"value1":2.326147803684073,"value2":0.0,"value3":5.366286744605137},{"date":"2015-01-31 18:13","value":7.6,"value1":2.326147803684073,"value2":0.0,"value3":5.366286744605137},{"date":"2015-02-01 08:27","value":0.5,"value1":2.2598291825869503,"value2":7.626568852808364,"value3":4.456286744605139},{"date":"2015-02-01 08:37","value":0.5,"value1":2.259934260638089,"value2":0.0,"value3":4.818223585873952},{"date":"2015-02-01 08:45","value":0.5,"value1":2.259724104535812,"value2":0.0,"value3":4.888223585873952},{"date":"2015-02-01 09:03","value":0.5,"value1":2.259303792331258,"value2":7.626568852808364,"value3":5.028223585873953},{"date":"2015-02-01 09:10","value":0.5,"value1":2.259303792331258,"value2":0.0,"value3":5.03161772137247},{"date":"2015-02-01 09:12","value":0.5,"value1":2.259303792331258,"value2":0.0,"value3":5.03161772137247},{"date":"2015-02-01 09:25","value":0.5,"value1":2.2598291825869503,"value2":0.0,"value3":4.856617721372469},{"date":"2015-02-01 09:34","value":0.5,"value1":2.2600393386892277,"value2":0.0,"value3":4.786617721372469},{"date":"2015-02-01 09:45","value":0.5,"value1":2.2596190264846734,"value2":0.0,"value3":4.92661772137247},{"date":"2015-02-01 09:55","value":0.5,"value1":2.2596190264846734,"value2":0.0,"value3":4.92661772137247},{"date":"2015-02-01 10:13","value":0.5,"value1":2.2605647289449204,"value2":7.626214214385773,"value3":4.61161772137247},{"date":"2015-02-01 10:32","value":0.5,"value1":2.2609850411494747,"value2":7.629760598611698,"value3":4.475017381484108},{"date":"2015-02-01 10:45","value":0.5,"value1":2.2602494947915046,"value2":0.0,"value3":4.720017381484107},{"date":"2015-02-01 10:48","value":0.5,"value1":2.2602494947915046,"value2":0.0,"value3":4.720017381484107},{"date":"2015-02-01 11:51","value":0.5,"value1":2.2584631679221494,"value2":7.625150299117995,"value3":5.315017381484106},{"date":"2015-02-01 13:23","value":0.5,"value1":2.2582530118198725,"value2":7.6212492764694755,"value3":5.388422564462271},{"date":"2015-02-01 13:36","value":0.5,"value1":2.2579377776664566,"value2":0.0,"value3":5.500249492017611},{"date":"2015-02-01 14:35","value":0.5,"value1":2.260144416740366,"value2":7.626568852808364,"value3":4.765249492017611},{"date":"2015-02-01 14:48","value":0.5,"value1":2.259724104535812,"value2":0.0,"value3":4.908671233087414},{"date":"2015-02-01 14:51","value":0.5,"value1":2.259724104535812,"value2":0.0,"value3":4.908671233087414},{"date":"2015-02-01 14:52","value":0.5,"value1":2.259724104535812,"value2":0.0,"value3":4.908671233087414},{"date":"2015-02-01 15:25","value":0.5,"value1":2.258568245973288,"value2":7.623377107005032,"value3":5.293671233087412},{"date":"2015-02-01 16:07","value":0.5,"value1":2.260354572842643,"value2":7.627632768076144,"value3":4.702098490008993},{"date":"2015-02-01 16:13","value":0.5,"value1":2.260354572842643,"value2":0.0,"value3":4.70553126102158},{"date":"2015-02-01 16:33","value":0.5,"value1":2.260669806996059,"value2":7.633306982837625,"value3":4.600531261021581},{"date":"2015-02-01 16:35","value":0.5,"value1":2.260669806996059,"value2":0.0,"value3":4.600531261021581},{"date":"2015-02-01 16:50","value":0.5,"value1":2.2602494947915046,"value2":0.0,"value3":4.74053126102158},{"date":"2015-02-01 16:55","value":0.5,"value1":2.2602494947915046,"value2":0.0,"value3":4.74053126102158},{"date":"2015-02-01 16:56","value":0.5,"value1":2.2602494947915046,"value2":0.0,"value3":4.74053126102158},{"date":"2015-02-02 07:55","value":0.8,"value1":2.2482967550266166,"value2":7.587533355745947,"value3":3.903969544361569},{"date":"2015-02-02 08:05","value":0.8,"value1":2.2479499457904066,"value2":0.0,"value3":4.481204065839117},{"date":"2015-02-02 08:31","value":0.8,"value1":2.247464412859713,"value2":7.585660585870414,"value3":4.7262040658391165},{"date":"2015-02-02 08:53","value":0.8,"value1":2.247048241776261,"value2":7.58519239340153,"value3":4.936204065839117},{"date":"2015-02-02 08:57","value":0.8,"value1":2.247048241776261,"value2":0.0,"value3":4.936204065839117},{"date":"2015-02-02 09:12","value":0.8,"value1":2.246909518081777,"value2":0.0,"value3":5.009730304258952},{"date":"2015-02-02 09:26","value":0.8,"value1":2.246701432540051,"value2":0.0,"value3":5.114730304258952},{"date":"2015-02-02 09:29","value":0.8,"value1":2.246701432540051,"value2":0.0,"value3":5.114730304258952},{"date":"2015-02-02 09:40","value":0.8,"value1":2.2465627088455675,"value2":0.0,"value3":5.1847303042589505},{"date":"2015-02-02 09:51","value":0.8,"value1":2.2463546233038416,"value2":0.0,"value3":5.289730304258951},{"date":"2015-02-02 10:55","value":0.8,"value1":2.245522281136938,"value2":7.579574083774931,"value3":5.709730304258951},{"date":"2015-02-02 11:02","value":0.8,"value1":2.24559164298418,"value2":0.0,"value3":5.681799225024811},{"date":"2015-02-02 12:48","value":0.8,"value1":2.243718873108647,"value2":7.5741898703827735,"value3":6.626799225024811},{"date":"2015-02-02 12:51","value":0.8,"value1":2.243718873108647,"value2":0.0,"value3":6.630341903739138},{"date":"2015-02-02 13:00","value":0.8,"value1":2.243580149414163,"value2":0.0,"value3":6.70389005891524},{"date":"2015-02-02 13:06","value":0.8,"value1":2.243580149414163,"value2":0.0,"value3":6.70389005891524},{"date":"2015-02-02 13:49","value":0.8,"value1":2.2444124915810666,"value2":7.573955774148333,"value3":6.283890058915238},{"date":"2015-02-02 13:53","value":0.8,"value1":2.2444124915810666,"value2":0.0,"value3":6.283890058915238},{"date":"2015-02-02 14:03","value":0.8,"value1":2.2442044060393407,"value2":0.0,"value3":6.39244368873023},{"date":"2015-02-02 14:05","value":0.8,"value1":2.2442044060393407,"value2":0.0,"value3":6.39244368873023},{"date":"2015-02-02 14:06","value":0.8,"value1":2.2442044060393407,"value2":0.0,"value3":6.39244368873023},{"date":"2015-02-02 14:45","value":0.8,"value1":2.2444124915810666,"value2":7.574423966617216,"value3":6.28744368873023},{"date":"2015-02-02 15:10","value":0.8,"value1":2.2442737678865825,"value2":7.574892159086099,"value3":6.35744368873023},{"date":"2015-02-02 15:21","value":0.8,"value1":2.2444124915810666,"value2":0.0,"value3":6.291002791358409},{"date":"2015-02-02 15:35","value":0.8,"value1":2.2444124915810666,"value2":0.0,"value3":6.291002791358409},{"date":"2015-02-02 16:11","value":0.8,"value1":2.2448286626645184,"value2":0.0,"value3":6.084567364971273},{"date":"2015-02-02 16:19","value":0.8,"value1":2.2449673863590025,"value2":0.0,"value3":6.014567364971272},{"date":"2015-02-02 16:28","value":0.8,"value1":2.2449673863590025,"value2":0.0,"value3":6.014567364971272},{"date":"2015-02-02 16:34","value":0.8,"value1":2.245106110053486,"value2":0.0,"value3":5.944567364971272},{"date":"2015-02-02 16:36","value":0.8,"value1":2.245106110053486,"value2":0.0,"value3":5.944567364971272},{"date":"2015-02-02 16:39","value":0.8,"value1":2.245106110053486,"value2":0.0,"value3":5.944567364971272},{"date":"2015-02-02 17:33","value":0.8,"value1":2.2452448337479702,"value2":7.5774672176649585,"value3":5.874567364971272},{"date":"2015-02-02 17:52","value":0.8,"value1":2.245314195595212,"value2":7.577701313899398,"value3":5.8431374077374905},{"date":"2015-02-02 17:53","value":0.8,"value1":2.245314195595212,"value2":0.0,"value3":5.8431374077374905},{"date":"2015-02-02 17:55","value":0.8,"value1":2.245314195595212,"value2":0.0,"value3":5.8431374077374905},{"date":"2015-02-02 18:03","value":0.8,"value1":2.245452919289696,"value2":0.0,"value3":5.776712917822941},{"date":"2015-02-02 18:08","value":0.8,"value1":2.245452919289696,"value2":0.0,"value3":5.776712917822941},{"date":"2015-02-02 20:02","value":0.8,"value1":2.245661004831422,"value2":7.579105891306049,"value3":5.671712917822941},{"date":"2015-02-03 07:58","value":0.0,"value1":2.4030884543008573,"value2":4.057663664238833,"value3":4.8388803326009615},{"date":"2015-02-03 08:13","value":0.0,"value1":2.403633320435554,"value2":0.0,"value3":5.127343093746063},{"date":"2015-02-03 08:14","value":0.0,"value1":2.403633320435554,"value2":0.0,"value3":5.127343093746063},{"date":"2015-02-03 08:18","value":0.0,"value1":2.4041781865702516,"value2":0.0,"value3":5.022343093746063},{"date":"2015-02-03 08:24","value":0.0,"value1":2.4041781865702516,"value2":0.0,"value3":5.022343093746063},{"date":"2015-02-03 08:27","value":0.0,"value1":2.4041781865702516,"value2":0.0,"value3":5.022343093746063},{"date":"2015-02-03 08:39","value":0.0,"value1":2.4047230527049486,"value2":0.0,"value3":4.917343093746062},{"date":"2015-02-03 08:51","value":0.0,"value1":2.4054495408845447,"value2":0.0,"value3":4.7773430937460635},{"date":"2015-02-03 08:57","value":0.0,"value1":2.4054495408845447,"value2":0.0,"value3":4.7773430937460635},{"date":"2015-02-03 11:29","value":0.0,"value1":2.41180631245601,"value2":4.069923152269516,"value3":3.552343093746064},{"date":"2015-02-03 13:07","value":0.0,"value1":2.406902517243737,"value2":4.062260972250339,"value3":4.50833129825107},{"date":"2015-02-03 13:22","value":0.0,"value1":2.4067208951988377,"value2":0.0,"value3":4.550683940184761},{"date":"2015-02-03 13:31","value":0.0,"value1":2.4063576511090394,"value2":0.0,"value3":4.620683940184762},{"date":"2015-02-03 13:41","value":0.0,"value1":2.4063576511090394,"value2":0.0,"value3":4.620683940184762},{"date":"2015-02-03 13:59","value":0.0,"value1":2.4061760290641407,"value2":4.060728536246503,"value3":4.655683940184762},{"date":"2015-02-03 15:08","value":0.0,"value1":2.4058127849743425,"value2":4.059809074644202,"value3":4.729368407168705},{"date":"2015-02-03 15:27","value":0.0,"value1":2.4059944070192416,"value2":4.059809074644202,"value3":4.698058302307755},{"date":"2015-02-03 16:53","value":0.0,"value1":2.406902517243737,"value2":4.06103502344727,"value3":4.526753623706208},{"date":"2015-02-03 17:01","value":0.0,"value1":2.4070841392886355,"value2":0.0,"value3":4.49545436946557},{"date":"2015-02-03 17:15","value":0.0,"value1":2.4072657613335346,"value2":0.0,"value3":4.46045436946557},{"date":"2015-02-03 17:17","value":0.0,"value1":2.4072657613335346,"value2":0.0,"value3":4.46045436946557},{"date":"2015-02-03 17:26","value":0.0,"value1":2.4072657613335346,"value2":0.0,"value3":4.46045436946557},{"date":"2015-02-03 17:28","value":0.0,"value1":2.4072657613335346,"value2":0.0,"value3":4.46045436946557},{"date":"2015-02-03 17:40","value":0.0,"value1":2.4072657613335346,"value2":0.0,"value3":4.46045436946557},{"date":"2015-02-03 17:53","value":0.0,"value1":2.407447383378434,"value2":0.0,"value3":4.4254543694655695},{"date":"2015-02-03 18:12","value":0.0,"value1":2.407447383378434,"value2":4.062567459451108,"value3":4.4254543694655695},{"date":"2015-02-03 18:24","value":0.0,"value1":2.4078106274682316,"value2":0.0,"value3":4.359160537684561},{"date":"2015-02-03 18:25","value":0.0,"value1":2.4078106274682316,"value2":0.0,"value3":4.359160537684561},{"date":"2015-02-03 18:27","value":0.0,"value1":2.4078106274682316,"value2":0.0,"value3":4.359160537684561},{"date":"2015-02-03 18:30","value":0.0,"value1":2.4078106274682316,"value2":0.0,"value3":4.359160537684561},{"date":"2015-02-03 18:33","value":0.0,"value1":2.4078106274682316,"value2":0.0,"value3":4.359160537684561},{"date":"2015-02-03 18:35","value":0.0,"value1":2.4078106274682316,"value2":0.0,"value3":4.359160537684561},{"date":"2015-02-04 09:17","value":4.8,"value1":1.4117376542785904,"value2":4.765307484923889,"value3":4.07916053768456},{"date":"2015-02-04 10:51","value":4.8,"value1":1.411635002169902,"value2":4.764268132323418,"value3":4.5204024547384165},{"date":"2015-02-04 11:02","value":4.8,"value1":1.4115323500612138,"value2":0.0,"value3":4.562993177908414},{"date":"2015-02-04 11:04","value":4.8,"value1":1.4115323500612138,"value2":0.0,"value3":4.562993177908414},{"date":"2015-02-04 11:47","value":4.8,"value1":1.4111217416264603,"value2":4.762882328856127,"value3":4.702993177908414},{"date":"2015-02-04 11:48","value":4.8,"value1":1.4111217416264603,"value2":0.0,"value3":4.702993177908414},{"date":"2015-02-04 11:52","value":4.8,"value1":1.4111217416264603,"value2":0.0,"value3":4.702993177908414},{"date":"2015-02-04 12:53","value":4.8,"value1":1.4115323500612138,"value2":4.763228779722949,"value3":4.562993177908414},{"date":"2015-02-04 13:18","value":4.8,"value1":1.411635002169902,"value2":4.764268132323418,"value3":4.5356054521203255},{"date":"2015-02-04 13:24","value":4.8,"value1":1.411635002169902,"value2":0.0,"value3":4.5356054521203255},{"date":"2015-02-04 13:36","value":4.8,"value1":1.4117376542785904,"value2":0.0,"value3":4.500605452120325},{"date":"2015-02-04 13:54","value":4.8,"value1":1.411635002169902,"value2":4.764614583190242,"value3":4.5356054521203255},{"date":"2015-02-04 16:55","value":4.8,"value1":1.4114296979525254,"value2":4.763228779722949,"value3":4.605605452120326},{"date":"2015-02-04 16:59","value":4.8,"value1":1.4114296979525254,"value2":0.0,"value3":4.617064237409741},{"date":"2015-02-04 17:21","value":4.8,"value1":1.411635002169902,"value2":4.764268132323418,"value3":4.5508945910520335},{"date":"2015-02-04 17:39","value":4.8,"value1":1.4117376542785904,"value2":4.764268132323418,"value3":4.515894591052033},{"date":"2015-02-04 17:43","value":4.8,"value1":1.4117376542785904,"value2":0.0,"value3":4.515894591052033},{"date":"2015-02-04 17:47","value":4.8,"value1":1.4118403063872789,"value2":0.0,"value3":4.480894591052035},{"date":"2015-02-04 17:59","value":4.8,"value1":1.4118403063872789,"value2":0.0,"value3":4.480894591052035},{"date":"2015-02-04 18:04","value":4.8,"value1":1.4118403063872789,"value2":0.0,"value3":4.4847303206897635},{"date":"2015-02-04 22:11","value":4.8,"value1":1.4120456106046555,"value2":4.767039739258005,"value3":4.414730320689763},{"date":"2015-02-05 05:46","value":0.0,"value1":2.1268147903209274,"value2":7.178183081016803,"value3":3.7651269597410515},{"date":"2015-02-05 08:21","value":0.0,"value1":2.1269776024841915,"value2":0.0,"value3":4.048993906566226},{"date":"2015-02-05 08:44","value":0.0,"value1":2.1269776024841915,"value2":7.178549408384145,"value3":4.048993906566226},{"date":"2015-02-05 08:50","value":0.0,"value1":2.1269776024841915,"value2":0.0,"value3":4.048993906566226},{"date":"2015-02-05 09:12","value":0.0,"value1":2.1269233317631038,"value2":7.178549408384145,"value3":4.083993906566226},{"date":"2015-02-05 09:16","value":0.0,"value1":2.1269233317631038,"value2":0.0,"value3":4.087910038115783},{"date":"2015-02-05 09:17","value":0.0,"value1":2.1269233317631038,"value2":0.0,"value3":6.887910038115782},{"date":"2015-02-05 11:20","value":0.0,"value1":2.1265434367154867,"value2":7.177084098914767,"value3":4.332910038115783},{"date":"2015-02-06 08:43","value":0.3,"value1":2.7636138810145683,"value2":4.663651287290137,"value3":3.745758331604131},{"date":"2015-02-06 09:47","value":0.3,"value1":2.763519902209139,"value2":4.663492698055975,"value3":4.109451938081444},{"date":"2015-02-06 10:47","value":0.3,"value1":2.763269292061328,"value2":4.663122656509599,"value3":4.397544891478276},{"date":"2015-02-06 11:05","value":0.3,"value1":2.7632379657928516,"value2":0.0,"value3":4.436599308636794},{"date":"2015-02-06 11:24","value":0.3,"value1":2.763206639524375,"value2":4.662964067275437,"value3":4.471599308636794},{"date":"2015-02-06 12:04","value":0.3,"value1":2.7629873556450404,"value2":4.662594025729058,"value3":4.716599308636793},{"date":"2015-02-06 12:20","value":0.3,"value1":2.763018681913517,"value2":4.662541162651005,"value3":4.6856590166589775},{"date":"2015-02-06 12:36","value":0.3,"value1":2.7629247031080877,"value2":0.0,"value3":4.790659016658978},{"date":"2015-02-06 12:40","value":0.3,"value1":2.7629247031080877,"value2":0.0,"value3":4.790659016658978},{"date":"2015-02-06 12:43","value":0.3,"value1":2.7629247031080877,"value2":0.0,"value3":4.790659016658978},{"date":"2015-02-06 12:51","value":0.3,"value1":2.7630500081819935,"value2":0.0,"value3":4.650659016658979},{"date":"2015-02-06 12:58","value":0.3,"value1":2.7630500081819935,"value2":0.0,"value3":4.650659016658979},{"date":"2015-02-06 13:00","value":0.3,"value1":2.7631126607189462,"value2":0.0,"value3":4.5847240134591285},{"date":"2015-02-06 13:03","value":0.3,"value1":2.7631126607189462,"value2":0.0,"value3":4.5847240134591285},{"date":"2015-02-06 13:11","value":0.3,"value1":2.7631126607189462,"value2":0.0,"value3":4.5847240134591285},{"date":"2015-02-06 13:14","value":0.3,"value1":2.7631126607189462,"value2":0.0,"value3":4.5847240134591285},{"date":"2015-02-06 13:18","value":0.3,"value1":2.7630813344504697,"value2":0.0,"value3":4.619724013459129},{"date":"2015-02-06 13:21","value":0.3,"value1":2.7630813344504697,"value2":0.0,"value3":4.619724013459129},{"date":"2015-02-06 13:23","value":0.3,"value1":2.7630813344504697,"value2":0.0,"value3":4.619724013459129},{"date":"2015-02-06 13:58","value":0.3,"value1":2.762830724302659,"value2":4.662382573416845,"value3":4.899724013459128},{"date":"2015-02-07 07:33","value":0.0,"value1":2.8019923960894393,"value2":4.728362168400928,"value3":4.318915736842392},{"date":"2015-02-07 09:14","value":0.0,"value1":2.8018801680156704,"value2":4.7281727835264435,"value3":4.413795942957529},{"date":"2015-02-07 09:41","value":0.0,"value1":2.801711825905017,"value2":4.727983398651959,"value3":4.527131356835202},{"date":"2015-02-07 09:49","value":0.0,"value1":2.8016557118681327,"value2":0.0,"value3":4.562131356835202},{"date":"2015-02-07 09:50","value":0.0,"value1":2.8016557118681327,"value2":0.0,"value3":4.562131356835202},{"date":"2015-02-07 09:53","value":0.0,"value1":2.8016557118681327,"value2":0.0,"value3":4.562131356835202},{"date":"2015-02-07 10:08","value":0.0,"value1":2.801431255720595,"value2":0.0,"value3":4.706306931373748},{"date":"2015-02-07 10:11","value":0.0,"value1":2.801431255720595,"value2":0.0,"value3":4.706306931373748},{"date":"2015-02-07 10:13","value":0.0,"value1":2.801431255720595,"value2":0.0,"value3":4.706306931373748},{"date":"2015-02-07 10:19","value":0.0,"value1":2.801206799573057,"value2":0.0,"value3":4.846306931373746},{"date":"2015-02-07 10:23","value":0.0,"value1":2.801206799573057,"value2":0.0,"value3":4.846306931373746},{"date":"2015-02-07 10:29","value":0.0,"value1":2.801206799573057,"value2":0.0,"value3":4.846306931373746},{"date":"2015-02-07 10:32","value":0.0,"value1":2.801206799573057,"value2":0.0,"value3":4.846306931373746},{"date":"2015-02-07 15:08","value":0.0,"value1":2.798176641581299,"value2":4.7218283902312,"value3":6.736306931373745},{"date":"2015-02-07 15:14","value":0.0,"value1":2.798176641581299,"value2":0.0,"value3":6.75726339417378},{"date":"2015-02-07 15:42","value":0.0,"value1":2.7979521854337612,"value2":4.722017775105684,"value3":6.89726339417378},{"date":"2015-02-07 15:56","value":0.0,"value1":2.7979521854337612,"value2":0.0,"value3":6.89726339417378},{"date":"2015-02-07 16:10","value":0.0,"value1":2.7979521854337612,"value2":0.0,"value3":6.901470389682137},{"date":"2015-02-07 16:51","value":0.0,"value1":2.798008299470646,"value2":4.721544312919471,"value3":6.866470389682137},{"date":"2015-02-07 16:52","value":0.0,"value1":2.798008299470646,"value2":0.0,"value3":6.866470389682137},{"date":"2015-02-07 17:03","value":0.0,"value1":2.79806441350753,"value2":0.0,"value3":6.835682614469691},{"date":"2015-02-07 17:17","value":0.0,"value1":2.798457211765721,"value2":0.0,"value3":6.590682614469694},{"date":"2015-02-07 17:40","value":0.0,"value1":2.7987938959870275,"value2":4.722396544854654,"value3":6.380682614469693},{"date":"2015-02-07 17:51","value":0.0,"value1":2.799130580208334,"value2":0.0,"value3":6.170682614469692},{"date":"2015-02-07 18:15","value":0.0,"value1":2.7997478346140627,"value2":4.724101008725017,"value3":5.789900066372388},{"date":"2015-02-08 08:51","value":0.0,"value1":3.321271534278814,"value2":5.604832837637907,"value3":4.739900066372389},{"date":"2015-02-08 09:14","value":0.0,"value1":3.3211606462536833,"value2":0.0,"value3":5.013787618964326},{"date":"2015-02-08 09:19","value":0.0,"value1":3.3211606462536833,"value2":0.0,"value3":5.013787618964326},{"date":"2015-02-08 09:23","value":0.0,"value1":3.3209388702034213,"value2":0.0,"value3":5.083787618964326},{"date":"2015-02-08 09:45","value":0.0,"value1":3.3206062061280286,"value2":5.603522972841048,"value3":5.1887876189643265},{"date":"2015-02-08 09:54","value":0.0,"value1":3.320162654027505,"value2":0.0,"value3":5.328787618964325},{"date":"2015-02-08 09:58","value":0.0,"value1":3.320162654027505,"value2":0.0,"value3":5.328787618964325},{"date":"2015-02-08 10:05","value":0.0,"value1":3.3199408779772432,"value2":0.0,"value3":5.4030884082098645},{"date":"2015-02-08 10:09","value":0.0,"value1":3.3199408779772432,"value2":0.0,"value3":5.4030884082098645},{"date":"2015-02-08 10:24","value":0.0,"value1":3.3194973258767195,"value2":0.0,"value3":5.543088408209865},{"date":"2015-02-09 05:52","value":0.0,"value1":3.583095611278101,"value2":6.046473844031795,"value3":5.298088408209864},{"date":"2015-02-12 06:19","value":0.0,"value1":1.0215661951320585,"value2":3.446698353577818,"value3":2.559014879013384},{"date":"2015-02-12 15:21","value":0.0,"value1":0.9932092056881044,"value2":3.3586063991546253,"value3":8.590442332844628},{"date":"2015-02-13 02:51","value":0.0,"value1":0.8943963792515295,"value2":3.019647746830572,"value3":6.863113258684356},{"date":"2015-02-14 13:46","value":0.0,"value1":0.8166462379974463,"value2":2.7561810532413813,"value3":9.068113258684354},{"date":"2015-02-14 13:57","value":0.0,"value1":0.8156121199983873,"value2":0.0,"value3":9.380538694411378},{"date":"2015-02-15 16:42","value":0.3,"value1":0.7580736068659004,"value2":2.5642049672524387,"value3":8.860582138342},{"date":"2015-02-16 07:50","value":2.8,"value1":1.4800877193356299,"value2":4.996132275949107,"value3":7.159121596973717},{"date":"2015-02-17 07:19","value":0.0,"value1":4.7395312749609895,"value2":5.332223685339113,"value3":7.71173970259499},{"date":"2015-02-17 09:16","value":0.0,"value1":4.739419718957434,"value2":5.331847183827111,"value3":8.049011593967231},{"date":"2015-02-18 13:17","value":0.0,"value1":2.8529165989456704,"value2":4.815031280094829,"value3":9.209373073226676},{"date":"2015-02-18 13:20","value":0.0,"value1":2.8529165989456704,"value2":0.0,"value3":12.184373073226674},{"date":"2015-02-20 11:35","value":0.0,"value1":0.9871663657506521,"value2":3.3368122078236304,"value3":7.296374272002213},{"date":"2015-02-20 11:54","value":0.0,"value1":0.9848882664550166,"value2":3.33168648440845,"value3":8.56885098624007},{"date":"2015-02-20 12:00","value":0.0,"value1":0.9843820221670976,"value2":0.0,"value3":8.644553776763594},{"date":"2015-02-20 12:19","value":0.0,"value1":0.9836226557352191,"value2":3.322289324813954,"value3":8.749553776763594},{"date":"2015-02-20 12:21","value":0.0,"value1":0.9836226557352191,"value2":0.0,"value3":8.749553776763594},{"date":"2015-02-20 12:27","value":0.0,"value1":0.9836226557352191,"value2":0.0,"value3":8.749553776763594},{"date":"2015-02-20 13:59","value":0.0,"value1":0.9780539685681101,"value2":3.3034950056249612,"value3":9.519553776763594},{"date":"2015-02-21 14:25","value":0.0,"value1":1.1167407069466535,"value2":3.7700401606241,"value3":8.620972679824405},{"date":"2015-02-21 17:58","value":0.0,"value1":1.1210559204305122,"value2":3.780442907415545,"value3":8.444376732681873},{"date":"2015-02-21 20:57","value":0.0,"value1":1.1318439541401584,"value2":3.817892795864745,"value3":7.242689607687932},{"date":"2015-02-22 09:26","value":1.5,"value1":1.9933460940801904,"value2":6.727975276106806,"value3":7.114372173368174}]]

**Comment by almossawi** [comment]
I'm not seeing those squiggles.

![screen shot 2015-02-23 at 12 18 04 pm](https://cloud.githubusercontent.com/assets/980049/6336275/3a5d341e-bb56-11e4-8f38-e1c6de36ea99.png)

**Comment by Pascal66** [comment]
thank you, I've tried now, and I dont see it too, now it work well something has change... :+1:
