### ISSUE TITLE
Buggy vertical line on time-based axis

### ISSUE THREAD

**Issue by eltermann** [mozilla/metrics-graphics#370]
![screenshot from 2015-02-23 15 25 38](https://cloud.githubusercontent.com/assets/569111/6334010/77fcd616-bb70-11e4-946a-4a2bf0190a47.png)

The above was extracted from http://metricsgraphicsjs.org/examples.htm

**Comment by almossawi** [comment]
This is the start-of-year marker. Several people have pointed out that it is odd-looking. It's being tracked here: https://github.com/mozilla/metrics-graphics/issues/358.

**Comment by eltermann** [comment]
I searched the open issues but wasn't able to find anything.
Anyway, I'll be watching it. Thanks.
