### ISSUE TITLE
V2.2 custom xax_format function isn't being called?

### ISSUE THREAD

**Issue by okhorseguy** [mozilla/metrics-graphics#372]
Greetings,
I switched to v2.2 yesterday and have since noticed that my custom function for generating
X axis labels is no longer being called. We also have a custom function for mouseovers which *is* still
being called. A few debug messages leads me to think that it's simply no longer being called at all.
Is there something  that was changed that I am unaware of or is this a known issue and I'm not finding it?
Thanks.

**Comment by okhorseguy** [comment]
In fact, I don't find setTicks in the dist/min version at all. Has this been deprecated?

**Comment by almossawi** [comment]
Hi there, Would you mind sharing a few things to help us find the culprit: 1) your custom function, 2) which version you upgraded from, 3) the console messages that you're getting.

``rollover_callback`` was deprecated in v2.0 and replaced with ``mouseover``, ``mouseout`` and ``mousemove``. See this: https://github.com/mozilla/metrics-graphics/wiki/Graphic#rollover_callback

``SetTicks`` isn't a function that I believe we've ever had.

**Comment by okhorseguy** [comment]
Apologies, I deleted that after posting it as I realized that setTicks() is my custom function being called (doh!). 

I upgraded from version 2.0.0 to 2.2.0.
When I switched back to 2.0 as a test, my setTicks() function was being called again and labels came
up correct.

I'm not getting any console messages good bad or otherwise.
I added a console.log line or two just inside my setTicks() function and nothing at all shows up in
the console. Truly looks as if it's just not being called.

setTicks looks like this:

/**
 * Format our xticks the way we want them instead of defaults
 * @param xtype "norm" for normal formatting, "month" for monthly, "billed" for last bill
 * @param last (optional) number for last day of month (for monthly)
 * @param end last day at the end of the current data set
 * @returns New string formatted as needed for an xtick
 */
function setTicks(d, xtype, last, end) {
    var nd = new Date(d);

    var hr = nd.getHours();
    var mi = nd.getMinutes();

    if(xtype == "month" || xtype == "billed") {
        if(hr == 0 && mi == 0) {
            if(xtype == "month") {
                // simple bitwise check for odd dates so only print those
                // in order to skip every other day for real estate savings
                // if it's the last day of the month..skip it to avoid 
                // being crammed against the 1st of the next month, but only
                // skip it if there is another date past it in the data set
                // or we would drop off the last date in the time scale!
                if(nd.getDate() & 1 && (nd.getDate() != last && end != last)) {
                    return(d3.time.format('%b %d')(nd));
                } else {
                    return "";
                }
            } else if(xtype == "billed") {
                // here we don't skip the last since there is no next month to overlap
                // and end (in a proper data set) will likely be the same as the last
                if(nd.getDate() & 1) {
                    return(d3.time.format('%b %d')(nd));
                } else {
                    return "";
                }
            }
        } else {
            return "";
        }
    }

    // if not monthly or billed, and midnight, print the day instead of time
    // to show the transition to the next day
    if(hr == 0 && mi == 0) {
        return(d3.time.format('%b %d')(nd));
    }

    // If it's top of the hour, roll with hh:00   
    if(mi == 0) {
        return(d3.time.format('%H:%M')(nd));
    }

    // not an interesting point, return empty string for no tick
    return "";
}

**Comment by okhorseguy** [comment]
Graph setup:

MG.data_graphic({
                    title: "Last Bill"+ titleMark,
                    description: "Bandwidth Utilization For Last Month's Billing Cycle",
                    data: lastBillData,
                    target: tzGraphDIV,
                    legend: lastBillLEGEND,
                    legend_target: tzLegendDIV,
                    width: tzGraphWIDTH,
                    height: tzGraphHEIGHT,
                    animate_on_load: true,
                    xax_count: numDays,
                    show_secondary_x_label: true,
                    x_accessor: "date",
                    yax_count: 10,
                    y_accessor: lastBilledYACC,
                    y_extended_ticks: true,
                    interpolate: "monotone",
                    missing_is_hidden: false,
                    xax_format: function(z) { return setTicks(z, "billed", lastDay, 0); },
                    mouseover: function(r) { return customRollover(r); }
                });

**Comment by okhorseguy** [comment]
This was with version 2.0 and is the expected layout..

![screenshot from 2015-02-24 16 11 26](https://cloud.githubusercontent.com/assets/197075/6360514/3aec7c4c-bc40-11e4-83b8-d2a61d89e173.png)

**Comment by almossawi** [comment]
I suspect [this line](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/x_axis.js#L444) is the culprit. The change was made in issue #192.

Changing it to this ought to fix the issue:

```javascript
if(!args.xax_format) {
    delete args.xax_format;
}
```

I have to get a few things done today, so let me take a look at that for you tomorrow morning.

**Comment by almossawi** [comment]
Would you mind verifying if the fix solves your problem.

**Comment by almossawi** [comment]
@hamilton Would you mind taking a look at this, as I'm not that familiar with that part of the code. The fix corrects the issue of custom x-axis formatters being ignored.

**Comment by okhorseguy** [comment]
I took the liberty of adding the if() around the delete line in the un-minimized dist file.
That fixed it!
I'll run that for today then switch it back out once you release a new minimized file.
Many thanks for your help and for a great tool!  :-)

**Comment by almossawi** [comment]
Good to hear that it fixed it for you. Please update this thread if you run
into the issue again. I'm going to keep it open since I'd like to take a
closer look at it tomorrow.

By the way, here's the updated metricsgraphics.min.js:
https://github.com/mozilla/metrics-graphics/blob/f53392d6fc6c69f63cfe38e370469ebd596005a0/dist/metricsgraphics.min.js

**Comment by okhorseguy** [comment]
The new min file seems to work as expected.
Thanks again for the swift response and for all that you do!

**Comment by almossawi** [comment]
@hamilton Seeing as the next release is still a few weeks away, I'm leaning towards releasing a patch version that would include this fix (once you've gotten a chance to take a look at it) and the fixes in #367, #369, #371 by @dandehavilland and @beardicus.

Does that work for you?

**Comment by almossawi** [comment]
Chatted with @hamilton  offline.

I'm adding a unit test and closing this issue.
