### ISSUE TITLE
Custom legend

### ISSUE THREAD

**Issue by Pascal66** [mozilla/metrics-graphics#376]
I'm trying to add a function to legend:option, but i wish my legend to be on the right and having custom values, like that : 
![custom_legend](https://cloud.githubusercontent.com/assets/3041616/6431199/04780b0e-c028-11e4-8f70-035f87916783.png)

legend seems formated as htm in a span

**Comment by Pascal66** [comment]
for my own sparline, I've added that for the moment, after MG call

var svg = d3.select("#mgTemp svg");
var g = svg.append("g").attr("class", "legend").attr("transform", "translate(155, 0)");
g.append("text")
        .attr("y", 6 ).attr("class", "legend_max")
        .text("↑ <?=$tmax;?> °C");
g.append("text")
        .attr("y", 23 ).attr("class", "legend_avg")
        .text("↔ <?=($tmax+$tmin)/2;?> °C");
g.append("text")
        .attr("y", 39 ).attr("class", "legend_min")
        .text("↓ <?=$tmin;?> °C");

**Comment by almossawi** [comment]
@Pascal66 Can I close this issue?

**Comment by Pascal66** [comment]
I'll close it even if my solution isnt the good one, thank you
