### ISSUE TITLE
Support providing a jQuery object as the target

### ISSUE THREAD

**Issue by rgbkrk** [mozilla/metrics-graphics#378]
I've started creating an IPython/Jupyter widget that uses metrics graphics in the frontend of the notebook. To work with metrics-graphics, I set an ID on a created element (via Backbone+jQuery). Since elements aren't created on the page right away, I end up setting an ID for metrics-graphics' use.

```JavaScript
// Create the viewing frame.
this.$frame = $('<div/>')
    .css({
        overflow: 'hidden'
}).appendTo(this.$el);

// TODO: Declare a unique ID
this.$frame.id = 'widget_test';
this.$frame.attr('id', 'widget_test');
```

Later on during the "render", I use the same ID (I'm trying to do this using the example:

```JavaScript
MG.data_graphic({
  title: "UFO Sightings",
  description: "Yearly UFO sightings from the year 1945 to 2010.",
  data: data,
  width: width,
  height: height,
  target: this.$frame.id,
  x_accessor: 'year',
  y_accessor: 'sightings',
  markers: [{'year': 1964, 'label': '"The Creeping Terror" released'}]
});
```

When this is used, it can't find the target element:

```
The specified target element "widget_test" could not be found in the page. The chart will not be rendered.
```

If there's another way for me to work with the library that I'm unaware of, let me know! I'm not stuck with just one way of doing this.

**Comment by almossawi** [comment]
Wonderful.

This is likely related to https://github.com/mozilla/metrics-graphics/issues/368. The feature was [introduced in v1.1](https://github.com/mozilla/metrics-graphics/pull/211) and broken in v2.1.

Once we have some end-of-quarter tasks done next week, we'll be back on track to work on the currently open issues. Any PRs in the meantime are welcome :)

**Comment by rgbkrk** [comment]
Ah, ok. I was using a built copy straight from master. I'm a JavaScript novice (I mostly do server side work), so I'd love to contribute if I get anything meaningful in for fixes. There was one issue I patched but I wasn't sure if it was the right thing to do. `layers` was undefined in one of the internal functions, so I checked for it:

```diff
diff --git a/metricsgraphics/metricsgraphics.js b/metricsgraphics/metricsgraphics.js
index 6089353..bad29c9 100644
--- a/metricsgraphics/metricsgraphics.js
+++ b/metricsgraphics/metricsgraphics.js
@@ -1948,7 +1948,7 @@
         }

         function preventOverlap(labels) {
-            if (labels.length == 1) {
+            if (!labels || labels.length == 1) {
                 return;
             }
```

**Comment by almossawi** [comment]
Aah, good catch. That block of code was updated in https://github.com/mozilla/metrics-graphics/issues/374 and likely needs a bit more testing.

**Comment by almossawi** [comment]
If you don't mind, I'll close this issue since we're tracking the issue in #368.

**Comment by rgbkrk** [comment]
I don't mind, thank you for the response!

**Comment by rgbkrk** [comment]
There's some jankiness right now, but we have a partially working prototype that works with the IPython widget system:

![screenshot 2015-03-11 01 23 25](https://cloud.githubusercontent.com/assets/836375/6606907/06d1f7c8-c809-11e4-94ea-73b2af3a3dc4.png)

Users will be able to expose other controls to inject data, markers, etc. which update the view of the model. :smile: Looking forward to this. Thanks for a stellar beautiful library.

**Comment by almossawi** [comment]
Wonderful :)
