### ISSUE TITLE
X axis label placement includes args.buffer 3 times, but it cancels out

### ISSUE THREAD

**Issue by mduggan** [mozilla/metrics-graphics#379]
I spent a while staring at the calculation for the x axis label placement here
https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/x_axis.js#L246

```js
return args.left + args.buffer
                + ((args.width - args.right - args.buffer)
                    - (args.left + args.buffer)) / 2;
```

It seems like `args.buffer` is added then removed again (twice, divided by 2).  Is it supposed to be doing anything there other than making the calculation more confusing?

**Comment by almossawi** [comment]
Aah, yes, you're absolutely right.

**Comment by hamilton** [comment]
@mduggan pretty much just to confuse folks. You pesky kids and your sleuthing!

(good catch)
