### ISSUE TITLE
Plans for pie charts?

### ISSUE THREAD

**Issue by ErtugKaya** [mozilla/metrics-graphics#381]
Great lib, well done. I wonder if pie charts are on your roadmap.

**Comment by almossawi** [comment]
In general, pie charts aren't the best way to present data. What kind of data do you have that you're considering using pie charts for?

**Comment by ErtugKaya** [comment]
Ali, thank you for your response. 

If you have to present percentages, I think pies are your most compact and best option. I am aware that some statisticians regard pie charts as a poor method of displaying information according to [wiki](http://en.wikipedia.org/wiki/Pie_chart#Use.2C_effectiveness_and_visual_perception), but I have to disagree.

It is easier to see the whole and portions in a pie chart. It is not the same as putting bars side by side. If bars to use instead of pies, they should have background to show the whole.

Please take a look at how WinDirStat presents file sizes. At top it has horizontal bars with gray background. That is very useful to see percentage of a single item. They also have a chart below which helps how big is the biggest and the others. It is easier to see and compare all, in the bottom.

I hope I can make my point. I am open to your suggestions as well.

![image](https://cloud.githubusercontent.com/assets/4015159/6593007/c2ed80f8-c7dc-11e4-8faf-c27367d36d39.png)

**Comment by almossawi** [comment]
Quite honestly, I've no priggish aversion to pie charts, although there are usually better ways to present data. In cases where you're comparing two values and care about showing which is more and which is less, they might be apt. In a set of more than two values, you might wish to consider a stacked bar chart--as in your example--or a donut chart, which can make it easier to see differences between arcs.

We used both [in a recent project](https://webwewant.mozilla.org/en/#stats). The code for that [is on GitHub](https://github.com/mozilla/mrburns) and you're more than welcome to adapt it.

**Comment by ErtugKaya** [comment]
That's amazing, I am really impressed. That is way better than I can ask for.

I sincerely appreciate all the work you done. Thank you.

**Comment by tomde** [comment]
Hello,

i really like this amazing graphs, it is state of art! I just need to have pie chart or donut chart in my project and links above did not give me any clue. Is there a way how to do donut chart in this library?

**Comment by wlach** [comment]
At this time this isn't supported, nor is there is any plan to add pie or donut charts to metricsgraphics. Sorry!
