### ISSUE TITLE
mouseover documentation is incomplete

### ISSUE THREAD

**Issue by alex94040** [mozilla/metrics-graphics#383]
I can't figure out how to implement a custom mouseover function - I see the method signature, but I can't quite comprehend what d stands for. Looks like i is the sequence number of the data record. 

mouseover: function(d, i) {}

A comprehensive example would be very helpful. Thanks so much!

**Comment by almossawi** [comment]
Take a look at the [examples](https://github.com/mozilla/metrics-graphics/blob/master/examples/js/main.js) to see a few different ways of overriding [mouseover](https://github.com/mozilla/metrics-graphics/wiki/Graphic#mouseover).

Add a console log to your function and then mouse-over your chart to see what your ``d`` and ``i`` contain: ``console.log(d,i)``

![screen-shot-2015-03-16-at-6 28 46-am](https://cloud.githubusercontent.com/assets/980049/6666955/e5396858-cba5-11e4-8423-cbf89f1d9538.png)

**Comment by alex94040** [comment]
Interesting... I've been trying to override it for a scatter plot, and d has a very different schema (array; each element is an array of two doubles, neither of which maps particularly well to the source data).

**Comment by almossawi** [comment]
Take a look at ``d.point`` instead of ``d`` with scatterplots.

**Comment by alex94040** [comment]
Awesome. Thank you!
