### ISSUE TITLE
MG should be able to take data straight from d3.nest().entries()

### ISSUE THREAD

**Issue by contentfree** [mozilla/metrics-graphics#384]
I'm new to MG and having a helluva time getting a simple multi-line graph to render. I expected to be able to do something like http://jsfiddle.net/ddL0hao8/ and have it render the multi-line graph. However, there's just a lot of NaN errors.

**Comment by contentfree** [comment]
And even if I go through and manually set legend and data to mapped versions of the entries data that match the default expectations (ala http://jsfiddle.net/onour9y0/1/) there's still NaN errors.

**Comment by almossawi** [comment]
You can use the built-in function to convert timestamps:

```javascript
```

**Comment by almossawi** [comment]
And to get the legend, something like this:

```javascript
var legend = [];
data.forEach(function(d) {
    legend.push(d.key);
})

for(var i = 0; i < data.length; i++) {
    data[i] = MG.convert.date(data[i].values, 'calculated_at', '%Y-%m-%dT%H:%M:%S.%LZ');
}

MG.data_graphic({
    title: 'TPS by Shortcode',
    target: "#graph",
    interpolate: 'linear',
    legend_target: '#legend',
    legend: legend,
    data: data,
    x_accessor: 'calculated_at',
    y_accessor: 'tps'
});
```

**Comment by almossawi** [comment]
Closing, as this appears to be resolved. Feel free to reopen if that's not the case.
