### ISSUE TITLE
Multiline limit at 5?

### ISSUE THREAD

**Issue by phubner** [mozilla/metrics-graphics#386]
When trying to create a graph with more than 5 lines, the 6th+ line is created but not given a color. It would seem to stand that we could randomly assign colors in the multiline graphs. In the code, it seems like they are hard linked to css line colors. I do believe I can create my own css and assign them a color but want to raise the issue that by default a color should be given.

In the graph below, you can see that a dot is given for line6 but no line color.
![screen shot 2015-03-17 at 2 50 19 pm](https://cloud.githubusercontent.com/assets/751333/6697317/5d227bce-ccb5-11e4-9c47-c55d233f9f6f.png)

Here is the data set in case you want to reproduce

```json
[
  {
    "year": "1945",
    "sightings1": 6,
    "sightings2": 2,
    "sightings3": 3,
    "sightings4": 4,
    "sightings5": 1,
    "sightings6": 9
  },
  {
    "year": "1946",
    "sightings1": 10,
    "sightings2": 20,
    "sightings3": 30,
    "sightings4": 40,
    "sightings5": 10,
    "sightings6": 90
  },
  {
    "year": "1947",
    "sightings1": 5,
    "sightings2": 10,
    "sightings3": 15,
    "sightings4": 25,
    "sightings5": 30,
    "sightings6": 45
  },
  {
    "year": "1948",
    "sightings1": 2,
    "sightings2": 15,
    "sightings3": 2,
    "sightings4": 60,
    "sightings5": 7,
    "sightings6": 20
  },
  {
    "year": "1949",
    "sightings1": 15,
    "sightings2": 2,
    "sightings3": 19,
    "sightings4": 5,
    "sightings5": 30,
    "sightings6": 9
  }
]
```

**Comment by almossawi** [comment]
Yes, indeed, the colors for the first five lines, areas and legends are defined in the stylesheet for the light and dark themes. For a sixth line, you would add:

```css
.mg-line6-color {
    stroke: steelblue;
}

.mg-area6-color {
    fill: steelblue;
}

.mg-hover-line6-color {
    fill: steelblue;
}

.mg-line6-legend-color {
    color: steelblue;
}
```

We figured that if we're plotting more than five lines in the same chart and using color to encode some dimension of the data, then we probably need to rethink the chart.

Having said that, we can keep this issue open to see what others think.

**Comment by phubner** [comment]
For sure, I totally understand. At least use this issue to add some documentation to state a limit and a way to add color if needed.

**Comment by danieljacobarcher** [comment]
It would be great to separate the color from the css into the configuration/initializer for the chart, maybe as an array that lines up with the y_accessor array?

**Comment by almossawi** [comment]
@phubner Thanks. I've added a note to the readme file and wiki and referenced this issue.
