### ISSUE TITLE
Specify color of graph?

### ISSUE THREAD

**Issue by danieljacobarcher** [mozilla/metrics-graphics#389]
I haven't been able to find an easy solution for specifying the color of the graph. It'd be great if the data could include the color of the graph (or other metadata) that it would be drawn in.

**Comment by almossawi** [comment]
If by graph, you mean the plot area, then yes, there's no way to currently style that.

**Comment by almossawi** [comment]
@hamilton I've never found the need to style just the plot area, but if this is something that might be useful, I'd be happy to keep this open and target it for v2.3.

**Comment by hamilton** [comment]
Sorry for the very-long delay. I believe this was resolved in #503. Feel free to re-open if it wasn't.

**Comment by Be0rn01** [comment]
Hi, thank's for your job ! I try to reproduce the "Changing Single Line Color" example  on my website but the color argument don't work . I think I need something more CSS ? but I don't understand what thank you in advance.

`<!DOCTYPE html>`
`<html>`
`<lang="en">`
`<meta charset="UTF-8">`
`<script src="ajax/libs/d3/3.5.6/d3.js"></script>`
`<script src="ajax/libs/jquery/2.1.4/jquery.js"></script>`
`<script src="ajax/libs/metrics-graphics/2.6.0/metricsgraphics.js"></script>`
`<link rel="stylesheet" href="ajax/libs/metrics-graphics/2.6.0/metricsgraphics.css">`

`</head>`
`<body>`
    `<div id="chart"></div>`

`<script>`
`data =  [`
`  {`
`      "date": "2014-01-01",`
`      "value": 1`
`  },`
`  {`
`      "date": "2014-01-02",`
`      "value": 3`
`  },`
`  {`
`      "date": "2014-01-03",`
 `     "value": 2`
`  },`
 ` {`
`     "date": "2014-01-04",`
`      "value": 2`
`  },`
` {`
`      "date": "2014-01-05",`
 `     "value": 2`
 ` },`
`  {`
`     "date": "2014-01-06",`
`      "value": 1`

`        }];`


`    data = MG.convert.date(data, 'date');`
`    MG.data_graphic({`
`     title: "Changing Single Line Color",`
 `     description: "For single line charts, there are two simple ways to change a line color. The first is to change the css (described on the wiki). The other is to specify a color value using color: string or colors: string.",`
 `  data: data,`
`      width: 600,`
`      height: 200,`
  `    right: 40,`
  `    color: '#8C001A',`
  `    target: '#chart',`
  `    x_accessor: 'date',`
`      y_accessor: 'value'`
`    });`
`    </script>`
`</body>`
`</html>`
