### ISSUE TITLE
Improve the examples page

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#390]
The examples page has grown considerably since v1, making it difficult to see which block of code is for which chart. The proposal that we've chatted about is to have each group of charts on a different page and show the ``MG.data_graphic`` call and the dataset used to generate each one beside it.

Raised by @contentfree in #337.

**Comment by samjewell** [comment]
+1

**Comment by almossawi** [comment]
@hamilton do these categories look good?

__Line__
 * Line
 * Broken
 * Linked
 * Small range
 * Confidence band
 * Single dot

__Multi-line__
 * Multi-line
 * Broken
 * Linked
 * Single dot

__Data__
 * Handling missing data
 * Few observations
 * Missing data
 * Error flag set

__Axes__
 * Log scale
 * Min, max on y-axis, with negative values
 * Min, max on y-axis, when y-axis not zero
 * Hiding axes
 * Labels, not time
 * Custom units
 * Percentages

__Rollovers__
 * Aggregate rollovers
 * Rollover text formatting

__Automatic time formatting__
 * Less than a minute
 * Less than a day
 * A few days
 * A large span of days

__Annotations__
 * Markers
 * Baselines
 * Non-overlapping markers 

__Updating__
 * Updating x-axis
 * Updating y-axis
 * Updating with different number of lines
 * Updating with different number of lines while preserving colors

__Other__
  * Preserving the aspect ratio
  * Small charts
  * Rug plots

__Barplots__
__Histograms__
__Scatterplots__
__Data tables__
__Data-based buttons__

**Comment by almossawi** [comment]
@hamilton I've moved the v2.3 release to Monday, since I'll need to spend a bit more time on this.

**Comment by hamilton** [comment]
@almossawi Sounds good. Push whatever you have at the end of the day and I'll take a look / make some tweaks on Sunday.

**Comment by almossawi** [comment]
I am become Dev. Destroyer of code!

Everything below the footer is still outstanding, but you can see the new layout coming together. I'll be moving each section to its own file under ``examples`` and then loading things as appropriate as one clicks on the links at the top.

Also, we'll need to rename the data files and seriously clean up ``main.js``. I'm leaving those until the very end.

**Comment by almossawi** [comment]
@hamilton All done. Feel free to modify things further as you see fi. I'll be doing a final cleanup of the files under ``examples/charts`` tomorrow morning.
