### ISSUE TITLE
Markers are shown without vertical line  in line chart sometimes.

### ISSUE THREAD

**Issue by blazkovicz** [mozilla/metrics-graphics#391]
Here is screenshot:

![image](https://cloud.githubusercontent.com/assets/4517837/6823344/eec7cf9e-d308-11e4-9db4-14d4236956c9.png)

 This behaviour is not random, same data displays same result.

**Comment by blazkovicz** [comment]
Changing css from  `.mg-markers line {stroke-width: 0.5;}` to `.mg-markers line {stroke-width: 1;}` solved the problem.

**Comment by almossawi** [comment]
Yes, that was a bug in v2.1 that was fixed in v2.2. See https://github.com/mozilla/metrics-graphics/issues/336
