### ISSUE TITLE
args.processed.main_x_time_format() function is undefined sometime

### ISSUE THREAD

**Issue by azhai** [mozilla/metrics-graphics#393]
Line 1521
return args.processed.main_x_time_format(d);

bugfix: Change to
return main_time_format(d);

**Comment by hamilton** [comment]
@azhai can you post some example code? Would help us troubleshoot the error you're getting.

**Comment by almossawi** [comment]
Indeed, this happens if you call ``MG.data_graphic`` multiple times with the same params object. ``args.processed.main_x_time_format`` is undefined since ``xax_format`` is already set.

I'm currently looking into it, though a quick fix appears to be to delete xax_format between calls:

```javascript
delete params.xax_format;
```

**Comment by almossawi** [comment]
Closing, since we're tracking this issue in #401.
