### ISSUE TITLE
`args.target` as a DOM node not just a string

### ISSUE THREAD

**Issue by gfarrell** [mozilla/metrics-graphics#396]
Requiring that the `target` option as a string selector is really inflexible. For example, [`d3.select(node)`](https://github.com/mbostock/d3/wiki/Selections#d3_select) takes a DOM Element or a selector.

This is important for working within, for example, react components. It's a bit primitive to build a GUI using selectors to grab your elements.

One of the problems is caused in [init.js#80](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/init.js#L80) where you try to strip the punctuation from `args.target`.

Please don't depend on `args.target` being a string, but let it also be a DOM Element.

**Comment by hamilton** [comment]
We just fixed this issue, and will be in the 2.3 release. For context, we originally had dom elements as something you can pass as a target, but improper test coverage led to it being broken.

**Comment by hamilton** [comment]
(For more context see #368)
