### ISSUE TITLE
Missing data chart type doesn't seem to obey full_width 

### ISSUE THREAD

**Issue by reanimus** [mozilla/metrics-graphics#399]
First of all, kudos on this library, It's been a dream to use so far. I'm looking to include the pre-existing 'missing-data' type graphs when we've got insufficient data, but there's a slight annoyance in the way it's rendered at the moment. All of our graphs are set to use full width, but when the graph is a missing data graph, it doesn't fill in horizontal space. It looks like this:

![screen shot 2015-03-30 at 5 08 28 pm](https://cloud.githubusercontent.com/assets/1053912/6906870/72c67a58-d6ff-11e4-8667-3cf8d403754b.png)

Am I doing something wrong here? For reference, these are the options being used:

```
// Missing
{
    title: this.props.title,
    full_width: true,
    height: 300,
    chart_type: 'missing-data',
    missing_text: 'We are still collecting data. Check back later.'
}
```

```
// Present
{
    title: this.props.title,
    data: this.props.data,
    full_width: true,
    show_year_markers: false,
    height: 300,
    target: '#chartcomponent_' + this.props.datasetId,
    x_accessor: 'x',
    y_accessor: 'y'
}
```

**Comment by almossawi** [comment]
Indeed, you're right. The missing chart type doesn't call the common ``init`` function and so it ends up bypassing that option.

**Comment by hamilton** [comment]
@almossawi @reanimus please take a look at most recent commit. Should in theory fix the bug, but am pretty tired and could use another set of eyes. New test passes, at least :)

**Comment by almossawi** [comment]
The line that updates the viewbox was missing, and I updated the left margin in ``data_graphics.js``. Otherwise, this looks good.

**Comment by reanimus** [comment]
Agreed! Chart works as intended now. :)

**Comment by phubner** [comment]
Was just about to write an issue on this, glad to see it fixed so quickly! Also, +1 on a great library.
