### ISSUE TITLE
conflict with jquery ui

### ISSUE THREAD

**Issue by alisabri** [mozilla/metrics-graphics#400]
Hi,
metricsgraphics.js conflicts with jquery-ui

Uncaught TypeError: Cannot read property 'DEFAULTS' of undefined    metricsgraphics.js 748

**Comment by almossawi** [comment]
Does loading jquery-ui after MetricsGraphics fix it?

Let's keep this open so that I can take a closer look at it. Related issue: https://github.com/mozilla/metrics-graphics/issues/385

**Comment by alisabri** [comment]
Yes it fixes

**Comment by almossawi** [comment]
Let's just do that then. I've added a note to the FAQ section of the readme.
