### ISSUE TITLE
Issue with multiple data sets in the same graph 

### ISSUE THREAD

**Issue by atlantageek** [mozilla/metrics-graphics#403]
I am trying to draw two lines whose points share the same x values. The x axis is in date/time format.
I only have 10 points and it looks like a grid is displayed. Ive narrowed it down to this segment of code
g.selectAll('path')
                    .data(voronoi(data_nested))
                    .enter()
                        .append('path')
                            .filter(function(d) { return d !== undefined; })
                            .attr("d", function(d) { return "M" + d.join("L") + "Z"; })  
This draws the grid.

![screenshot from 2015-04-02 20 27 06](https://cloud.githubusercontent.com/assets/625215/6976364/b854bf52-d976-11e4-8d19-e410f6972388.png)

**Comment by almossawi** [comment]
Would you mind posting your date and code.

**Comment by almossawi** [comment]
Feel free to reopen if the issue persists.
