### ISSUE TITLE
Black background seeping through to timeline.

### ISSUE THREAD

**Issue by froriz5** [mozilla/metrics-graphics#404]
I'm getting this weird black background seeping through to the timeline and I don't what wrong. I'm not getting any console errors either. When I downloaded the source code, I copied over the 3 files in the "/dist folder, and imported them into my html page.

"metricsgraphics.css"
"metricsgraphics.min.js"
"metricsgraphics.js"

The data passed in is this:
[
		{"year": "2014", "position": 3},
		{"year": "2013", "position": 2},
		{"year": "2012", "position": 1},
		{"year": "2011", "position": 2},
		{"year": "2010", "position": 2},
		{"year": "2009", "position": 2},
		{"year": "2008", "position": 1},
		{"year": "2007", "position": 1},
		{"year": "2006", "position": 1},
		{"year": "2005", "position": 2}
]

The code to attach it is the following...
d3.json("TeamPositions.json", function(data){
	d3.select("body").append("div").attr("id", "timeline");
	MG.data_graphic({
	    title: 'Soccer Team Positions',
	    data: data["Chelsea"], 
	    width: 600,
	    height: 550,
	    target: '#timeline', // the html element that the graphic is inserted in
	    x_accessor: 'year',  // the key that accesses the x value
	    y_accessor: 'position' // the key that accesses the y value
	});
});

Note: I have JQuery imported as well.

Thanks,

Here's a screenshot of what it looks like...
![cs4460timelinepic](https://cloud.githubusercontent.com/assets/1795695/6995643/8f8e99fe-db23-11e4-81f1-36592764df12.png)

**Comment by almossawi** [comment]
Are you certain metricsgraphics.css is being loaded?

**Comment by froriz5** [comment]
Yea that was it...My bad, noob move.
