### ISSUE TITLE
full_width with constant height

### ISSUE THREAD

**Issue by sanga** [mozilla/metrics-graphics#407]
Apologies, this isn't really a bug but rather a question, just that I didn't see any other forum (irc, mailing list etc) to ask noob questions. In any case:

With full_width: true, when you resize the parent object both the width and height change to keep the aspect ratio constant. Is there a way to keep the width scaling to the parent size but the height constant?

**Comment by sanga** [comment]
figured this out myself. Apologies

**Comment by jetpackjarrett** [comment]
What was your solution, @sanga?
