### ISSUE TITLE
Array.max is undefined

### ISSUE THREAD

**Issue by zachberger** [mozilla/metrics-graphics#408]
`Array.max` is undefined as used in `_neighborhood_width`

**Comment by almossawi** [comment]
@hamilton To my knowledge, several of those functions are untested {and, or} not in use?

**Comment by hamilton** [comment]
Yes the _neighborhood_width is part of untested & unfinished code at the moment. We'll be circling back to the code for smoothers at some point in the future, but it's not currently on our horizon.
