### ISSUE TITLE
full height not accounting for title

### ISSUE THREAD

**Issue by thesec** [mozilla/metrics-graphics#411]
Configured at full_height the graph renders at 100% of the height, a configured title is not displayed unless the containing element is set to render overflow.

**Comment by phof** [comment]
+1

**Comment by almossawi** [comment]
#504 will likely address this.

**Comment by almossawi** [comment]
Fixed. Feel free to reopen if you continue to face issues.

<img width="694" alt="screen shot 2015-10-20 at 2 25 57 pm" src="https://cloud.githubusercontent.com/assets/980049/10621607/b43ec3e6-7736-11e5-8d77-b7d4fe8801b0.png">
