### ISSUE TITLE
no rollover on any data point

### ISSUE THREAD

**Issue by thesec** [mozilla/metrics-graphics#412]
Data points are no longer highlighted, the custom mouseover does not fire despite not JS errors in the log and show_rollover_text explicitely set true. Any hints what to look at? :/

**Comment by almossawi** [comment]
Would you mind sharing your data and code, please, so that we can replicate the bug and debug?

**Comment by thesec** [comment]
Hehe ... have seen that answer coming ... was just hoping for some general hints on where to look at if not a pointer to what this usually happens with from your experience ...

Here comes the code, config used to render the graph:

    MG.data_graphic( {
                            area: false,
                            decimals: 0,
                            data: data,
                            full_height: true,
                            full_width: true,
                            interpolate: "monotone",
                            legend: legends,
                            legend_target: '.mg-legend',
                            mouseover: function(d, i) {
                                //custom format the rollover text, show days
                                var prefix = d3.formatPrefix(d.value);
                                jQuery('.mg-rollover')
                                    .html('Day ' + (i+1) + ' &nbsp; '
                                        + prefix.scale(d.value).toFixed(2) + prefix.symbol);
                            },
                            point_size: 4,
                            show_rollover_text: true,
                            show_secondary_x_label: false, // show year and other
                            show_year_markers: false,
                            target: "#the_graph",
                            x_accessor: "time",
                            xax_start_at_min: true,
                            x_extended_ticks: true,
                            y_accessor: "value",
                            y_extended_ticks: true
                        } );

Any issues with that?

**Comment by thesec** [comment]
Mmmh, the issue seems to be with the (test) data:

    {
      "us": [
        34.12733333333333,
        35.693333333333335,
        34.95744444444445,
        37.565444444444445,
        38.023111111111106,
        38.420666666666676,
        38.38455555555555,
        37.956444444444436,
        35.257555555555555,
        33.443333333333335
      ],
      "eu": [
        116.4,
        113.4,
        114.4,
        113.6,
        119.6,
        112.6,
        111.6,
        113.8,
        108,
        108.4
      ],
      "asia": [
        7.8,
        7.6,
        6.8,
        5.8,
        6.2,
        6.8,
        5.2,
        4.8,
        4.2,
        3
      ],
      "time": [
        1.4285988e+09,
        1.4286006e+09,
        1.4286024e+09,
        1.4286042e+09,
        1.428606e+09,
        1.4286078e+09,
        1.4286096e+09,
        1.4286114e+09,
        1.4286132e+09,
        1.428615e+09
      ]
    }

Each of the regions is mapped to a timestamp using 

    var addTime = function ( x, i ) {
                            return { "time": new Date( xport.time[ i ] * 1000 ), "value": x }
                        }

and then passed as `data`.

While none of the single lines display the marker on hover, all combined views do.
With `aggregate_rollover` set true the marker displays for none.

Am using MG 2.2.1, d3 3.5.5, jQuery 2.1.3 on FF and Chrome.

**Comment by thesec** [comment]
Behavior does not change w/ latest MG and d3.

**Comment by thesec** [comment]
... getting closer ... seems to result from the graph rendering in absolute positioned parent?!

**Comment by thesec** [comment]
Am using http://codeitdown.com/css-square-rectangle/ with a full width container, set to display with 1/2 height ( 2 : 1 ratio ), the graph to display in `.rectangle-content`.

**Comment by thesec** [comment]
Ha! Got it!

The embedding container's CSS was set to `pointer-events: none;`, therefore not bubbling mouse events.
Weird though that some still made it through - see above.

Quite some sherlocking on that one ;)
