### ISSUE TITLE
Create a new section on the Wiki, add examples for the new hooks component

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#416]
Make sure we incorporate existing and new documentation into the Wiki and Examples page for @dandehavilland's PR (#351)

**Comment by almossawi** [comment]
@dandehavilland @hamilton I've added a brief overview of the new changes to the Wiki: [this](https://github.com/mozilla/metrics-graphics/wiki#resources) and [this](https://github.com/mozilla/metrics-graphics/wiki/Developing-Addons). Feel free to modify or add to that page as you see fit.

I've also added one of the two extensions to the [examples page](http://metricsgraphicsjs.org/examples.htm#addons), with the plan to add others shortly.

**Comment by dandehavilland** [comment]
Thanks @almossawi, that looks great. I'm planning to write up a short guide/tutorial for developing an extension, hopefully during some downtime I have next week. Will keep you updated!
