### ISSUE TITLE
Question multi-lines graphic

### ISSUE THREAD

**Issue by jonnymohamed** [mozilla/metrics-graphics#418]
It's possible a graphic has two lines,  but with differents values?
ex.: A graphic show a line with number of accidents in a month and at same time other line show the number of deaths.

**Comment by almossawi** [comment]
Sure, see the examples [here](http://metricsgraphicsjs.org/examples.htm#multilines) and the documentation for ``y_accessor`` [here](https://github.com/mozilla/metrics-graphics/wiki/Data#y_accessor).
