### ISSUE TITLE
hourly graph's missing_is_hidden option

### ISSUE THREAD

**Issue by airtoxin** [mozilla/metrics-graphics#420]
Hi
I try to show hourly graph with missing_is_hidden option but ti shows no graphs.
![screenshot 2015-04-29 16 08 36](https://cloud.githubusercontent.com/assets/2460874/7386031/0fe40a70-ee8a-11e4-8563-50e7ae99cd88.png)

If missing_is_hidden=false, graph was shown but missing point was connected with line. It's not good for my purpose.
![screenshot 2015-04-29 16 11 52](https://cloud.githubusercontent.com/assets/2460874/7386103/e8f49492-ee8a-11e4-979c-4ce7b9eed255.png)

Are there any way to show hourly graph with missing values?

**Comment by almossawi** [comment]
[missing_is_hidden](https://github.com/mozilla/metrics-graphics/wiki/Data#missing_is_hidden) works with time-series where the unit is no smaller than _days_. See the currently open issues on that. We'll be expanding it in the near future.
