### ISSUE TITLE
Undefined variables used

### ISSUE THREAD

**Issue by zachberger** [mozilla/metrics-graphics#423]
`args` is undefined on lines [utility.js:158](https://github.com/mozilla/metrics-graphics/blob/master/src/js/misc/utility.js#L158) and [utility.js:160](https://github.com/mozilla/metrics-graphics/blob/master/src/js/misc/utility.js#L160)

`breaker` is undefined on lines [utility.js:196](https://github.com/mozilla/metrics-graphics/blob/master/src/js/misc/utility.js#L196) and [utility.js:200](https://github.com/mozilla/metrics-graphics/blob/master/src/js/misc/utility.js#L200)

`rolloverNumberFormatter` is undefined on [histogram.js:143](https://github.com/mozilla/metrics-graphics/blob/master/src/js/charts/histogram.js#L143), [point.js:145](https://github.com/mozilla/metrics-graphics/blob/34e56c4a387940c3e5e58a458062389a8110c4e5/src/js/charts/point.js#L145)

**Comment by zachberger** [comment]
Flow static type checker was used to find all undefined identifiers

**Comment by zachberger** [comment]
#421 seems to trigger one of these

**Comment by almossawi** [comment]
Thanks. :+1:
