### ISSUE TITLE
Error with line chart

### ISSUE THREAD

**Issue by ilariuss** [mozilla/metrics-graphics#426]
Hello everybody.

I have a problem with chart width. I'm using two charts, line and histogram types, with the same data, but the width of the line chart is less than histogram and I don't know why.

My code: 
<pre>
d3.json('js/chart/datos.json', function (data) {
    data = MG.convert.date(data, 'date');
    MG.data_graphic({        
        data: data,
        target: "#chartLinear",
        x_accessor: 'date',
        y_accessor: 'value',
        animate_on_load: true,        
        width: 350,
        y_extended_ticks: true,
    });
});

d3.json('js/chart/datos.json', function (data) {
    data = MG.convert.date(data, 'date');
    MG.data_graphic({        
        data: data,
        target: '#chartRect',
        chart_type: 'histogram',
        binned: true,
        width: 350,
        y_extended_ticks: true,
    });
});

</pre>
Thank you very much!
![error](https://cloud.githubusercontent.com/assets/9787907/7512423/251f658c-f4ad-11e4-80e2-f39bdb4ae65a.jpg)

**Comment by almossawi** [comment]
Hi there, yes, histograms have a few quirks that we've not yet ironed out, hence why they're listed under _Experimental_ on the examples page :)

To modify the right margin of your line chart, you can update the value of [right] (https://github.com/mozilla/metrics-graphics/wiki/Layout#right).
