### ISSUE TITLE
turning off animation on the charts

### ISSUE THREAD

**Issue by gfarrell** [mozilla/metrics-graphics#427]
I'm using MG for streaming data that are coming in over websockets. Problem is that each point moves into its position over about 0.5s. I can see why animation might be desirable if changing y-axis data, but it looks terrible when changing x-axis data (i.e. time values - adding new points etc.).

There needs to be a way to disable this (but not for all charts by disabling the animations which I assume come from css?)

**Comment by gfarrell** [comment]
Ok so actually transitions are not css-based, but from transitions.js and D3's built in transitions. Is there a way of turning this off?

**Comment by almossawi** [comment]
You can set transition_on_update to false to disable transitions: https://github.com/mozilla/metrics-graphics/wiki/Graphic#wiki-transition_on_update

**Comment by gfarrell** [comment]
Ah ok, I had been searching the options for "animation", didn't think about transition.
Cheers.
