### ISSUE TITLE
ability to maintain null data points, and break the path

### ISSUE THREAD

**Issue by birdage** [mozilla/metrics-graphics#429]
it would be great to break the path if a null or invalid data point is come across, there is already a method in d3 to do this, and ive tested and it works in my case, will generate a pull request soon. there is an example on the examples page http://metricsgraphicsjs.org/examples.htm#data but i need it for non zero elements, for a long path.

http://bl.ocks.org/mbostock/3035090
http://stackoverflow.com/questions/9580003/pass-null-values-to-svg-path-using-d3-js-to-suppress-missing-data

**Comment by birdage** [comment]
![screen shot 2015-05-13 at 4 41 11 pm](https://cloud.githubusercontent.com/assets/547228/7620585/e3d0a3fc-f98e-11e4-8e7d-eda6c10be3c4.png)

**Comment by birdage** [comment]
pull request soon but....

`args`
``` JAVASCRIPT
MG.data_graphic = function() {
	'use strict';
	var defaults = {};
	defaults.all = {
	    missing_is_value: false,
	    missing_value: 0,
	    missing_is_zero: false,
	    missing_is_hidden: false, 
```


`charts.line`
``` JAVASCRIPT
//main line
 var line = d3.svg.line()
	.defined(function(d) { if (args.missing_is_value){return d.value != args.missing_value; }else{return d.value}})
	.x(args.scalefns.xf)
	.y(args.scalefns.yf)
	.interpolate(args.interpolate)
	.tension(args.interpolate_tension);
```
``` JAVASCRIPT
//for animating line on first load
var flat_line = d3.svg.line()
    .defined(function(d) {return d.value > -999; })
    .x(args.scalefns.xf)
    .y(function() { return args.scales.Y(data_median); })
    .interpolate(args.interpolate)
    .tension(args.interpolate_tension);
```

**Comment by birdage** [comment]
this might break some of the areas tho

**Comment by almossawi** [comment]
Sure, go for it. There's an implementation for broken lines that you're welcome to improve upon: http://metricsgraphicsjs.org/examples.htm#data (2nd example)

**Comment by birdage** [comment]
@almossawi i saw that, but that results in lots of spaces, for sparse time series data.
