### ISSUE TITLE
No styling for the tooltip

### ISSUE THREAD

**Issue by joergd** [mozilla/metrics-graphics#431]
When I hover over my title - the rollover event displays the description above the title - but it is missing all the styling so that it looks like a tooltip. I have jquery on the page, and the css too. The rest of the graph looks like in the examples, except the tooltip. It only displays the text, but no tooltip "bubble" ... Is there something I am missing?

**Comment by almossawi** [comment]
Have you included the Bootstrap stylesheet, as on the [examples page](http://metricsgraphicsjs.org/examples.htm)?

**Comment by joergd** [comment]
Ah - that must be it obviously - thanks :)
