### ISSUE TITLE
Add region annotation

### ISSUE THREAD

**Issue by dareid** [mozilla/metrics-graphics#432]
The annotations currently implemented are great. However, I currently need to mark a region, not just a point. Could annotations be extended to support this functionality? I figure the lib would be passed an annotation with start x value, end x value and a label.

**Comment by almossawi** [comment]
Not at the moment. Why not [write an addon](https://github.com/mozilla/metrics-graphics/wiki/Developing-Addons) that does that or submit a PR? :)

I can certainly imagine good use-cases for that.

**Comment by dareid** [comment]
I have started writing an addon for this. Currently a WIP : https://github.com/dareid/mg-regions

**Comment by almossawi** [comment]
Wonderful, feel free to add it to the list [here](https://github.com/mozilla/metrics-graphics/#gallery).
