### ISSUE TITLE
feature request: zoom ?

### ISSUE THREAD

**Issue by bbulkow** [mozilla/metrics-graphics#439]
I'm looking for some solution for basic time-oriented data that includes a "zoom in" feature. Most of the data I have ( for personal projects ) needs a big huge overview, and also benefits from zooming in. I want something with a "thumbnail" that allows zooming, I believe.

I realize this places higher load on the back-end system --- you need a tighter data integration --- but I think I need that anyway. I have sample datasets with 1y+ data at 30 seconds - which is about 1M points. That clearly needs to be downsampled, but I need the ability to then zoom into particular hours.

I would think my need is common --- any hints appreciated, hopefully I've missed something.

**Comment by almossawi** [comment]
Sorry, I've been a bit behind on emails lately.

Yes, indeed, the principal objective ought to be minimizing the number of data points on screen, on accord of the fact that you'll start taking a performance hit once that number gets over a few orders of magnitude--in SVG, that is.

There's an add-on written by @dandehavilland that will give you a starting point for the zooming functionality you're looking for: http://metricsgraphicsjs.org/examples.htm#addons

Two questions you might wish to ask are:

1. Do I need to see all the data at this level of granularity? If not, then consider smoothing the data via, say, a moving average. You may then alter the amount of smoothing as you zoom in and out.

2. Do I need to see all the data? If not, then slice it and show each slice at a time.

Hope that helps.
