### ISSUE TITLE
Error on recent Firefox versions

### ISSUE THREAD

**Issue by Uberi** [mozilla/metrics-graphics#441]
The following causes an error on Firefox 39 beta:

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Evolution Dashboard</title>
        <link rel="stylesheet" type="text/css" href="style/metricsgraphics.css" />
        
    </head>
    <body onload="main()">
        <div id="evolutions"></div>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>
        <script src="https://raw.githubusercontent.com/mozilla/metrics-graphics/master/dist/metricsgraphics.js"></script>
        <script>
    gx=[
      [{"date":"2014-09-02T04:00:00.000Z","value":244.8172820553797},{"date":"2014-09-03T04:00:00.000Z","value":263.88043}],
      [{"date":"2014-10-13T04:00:00.000Z","value":197.54449884347426},{"date":"2014-10-14T04:00:00.000Z","value":200.86218},{"date":"2014-10-15T04:00:00.000Z","value":199.77045},{"date":"2014-10-16T04:00:00.000Z","value":203.73876968},{"date":"2014-10-17T04:00:00.000Z","value":198.42171017865508}],
      [{"date":"2015-05-29T04:00:00.000Z","value":0}]
    ];

    gy=[
      [{"date":"2014-10-13T04:00:00.000Z","value":197.54449884347426}],
      [{"date":"2015-05-29T04:00:00.000Z","value":0}]
    ]

    function plot(data) { //wip: debug
      var filteredDatasets = data.map(function (line) {
        return line.map(function(point) { return {date: new Date(point.date), value: point.value}; });
      });
      MG.data_graphic({
        description: "Handling a solitary data point.",
        data: filteredDatasets,
        width: 1600,
        height: 600,
        target: "#evolutions"
      });
    }

    function main() {
      plot(gx);
      plot(gy);
    }
        </script>
    </body>
    </html>

![untitled](https://cloud.githubusercontent.com/assets/437196/7988692/bc971912-0ab2-11e5-946f-de6884c7fcde.png)

 Running `path0.getTotalLength()` additionally returns NaN, but only for this specific path - changing the values even slightly will cause it to no longer work.

**Comment by almossawi** [comment]
Could you please verify the fix.

**Comment by Uberi** [comment]
Yep, it's working fine now. Thanks!
