### ISSUE TITLE
Request for missing_is_hidden modification

### ISSUE THREAD

**Issue by okhorseguy** [mozilla/metrics-graphics#449]
For the data that I'm working with, we have times where data is missing.
It's not so much date based however, which as I understand, is what the missing_is_hidden option
works with.

The JSON data that I get from my source denotes missing data with a "missing: 0" when data is there and a "missing: 1" when the data is missing. 

Seems it would be a simple change to add the ability to show a break in the line for each data point that
has "missing: 1" defined in the JSON instead of just missing data in a time range.

Just thought I'd ask...we'd love to have the ability to show missing data as breaks in the line rather than
bottoming out.

**Comment by okhorseguy** [comment]
Maybe a simple addition of an option such as 
missing_is_hidden_accessor: "missing"
to tell the code what to check for a 0 or 1 and break the line if it's a 1. 
Just a thought. 

Thanks..

**Comment by almossawi** [comment]
Indeed, that could be useful. I'll add it to our backlog. :+1:

**Comment by okhorseguy** [comment]
Thank you!   :-)

**Comment by hamilton** [comment]
@almossawi

**Comment by hamilton** [comment]
Totally misunderstood this feature request. Reopening issue now.

**Comment by almossawi** [comment]
To summarize the change, when [missing_is_hidden](https://github.com/mozilla/metrics-graphics/wiki/Data#missing_is_hidden) is enabled and [missing_is_hidden_accessor](https://github.com/mozilla/metrics-graphics/wiki/Data#missing_is_hidden_accessor) is set, not only will ranges for which there is no data be hidden, but also data points that have been identified in the data source as missing, which is to say those that have a _missing_is_hidden_accessor_ attribute that's set to true.

If [missing_is_hidden_accessor](https://github.com/mozilla/metrics-graphics/wiki/Data#missing_is_hidden_accessor) is not set, then [missing_is_hidden](https://github.com/mozilla/metrics-graphics/wiki/Data#missing_is_hidden) works as before.

**Comment by okhorseguy** [comment]
Exactly!
Sounds perfect.  :-)

**Comment by almossawi** [comment]
The implementation is now much cleaner now. Thanks @birdage. We'll be adding additional examples soon.
