### ISSUE TITLE
How to use with ISO date format ?

### ISSUE THREAD

**Issue by thanyawzinmin** [mozilla/metrics-graphics#452]
I have been using the MG for a project. At first we follow the guidged exampless data format and then it came to use ISO date format for date which is (YYYY-MM-DDTHH:MM:SS ).

DO MG supports it ? If it supports it , how should I implement it ?

**Comment by almossawi** [comment]
Yes, `MG.convert.date` has a third parameter that takes a format string. So you'd do this:

```javascript
var data = [
    {
        "date": "2014-01-01T00:00:00",
        "value": 10000000
    },
    {
        "date": "2014-01-02T00:00:00",
        "value": 10379978
    }
];

MG.convert.date(data, 'date', '%Y-%m-%dT%H:%M:%S');

MG.data_graphic({
  data: data,
  target: ".result"
});
```

Take a look at the time-formatting link here for a full list of directives: https://github.com/mozilla/metrics-graphics/wiki/Convenience-Functions

**Comment by thanyawzinmin** [comment]
Thanks for the heads up. That really helps.
