### ISSUE TITLE
Use in Shiny Applications

### ISSUE THREAD

**Issue by kditmeye** [mozilla/metrics-graphics#453]
Hello,
Is there an output and render function that allows us to enable the use of metrics-graphics within Shiny applications ?
Thanks for your help

**Comment by almossawi** [comment]
Hi there, Apologies for the late reply.

I wouldn't know, sadly. There is [an R package](http://cran.r-project.org/web/packages/metricsgraphics/) that uses htmlwidgets. What would need to happen to make that work with Shiny?
