### ISSUE TITLE
Add a xax_end_at_max option to complement xax_start_at_min

### ISSUE THREAD

**Issue by hampsterx** [mozilla/metrics-graphics#456]
![graph_temp](https://cloud.githubusercontent.com/assets/1887721/8532215/ac522d34-2480-11e5-8dce-b7f868a55398.png)

The default behavior seems to be having the first X axis label using first data point, then a gap, then at the end it runs off the end.

Any idea how to get it to go the other way around, eg first label would be 08:00 (first data point is 08:19) and last point would be 08:05am (ie last data point 08:05)

I have tried the x axis options but cannot seem to get it to do what I want unless I go the full hog and implement xax_format :(

xax_count - the number of x-axis ticks
xax_format - a function that formats the x-axis' labels
x_axis - determines whether to display the x-axis
x_extended_ticks - determines whether to extend the x-axis ticks across the chart
x_label - the label to show below the x-axis
xax_start_at_min - determines whether to start the x-axis from the left-most edge
xax_tick_length - the x-axis' tick length in pixels

**Comment by hampsterx** [comment]
ahh my bad, xax_start_at_min was set, causing the first value being used as first Label. Maybe an xax_end_at_max would do it?

**Comment by almossawi** [comment]
Yes, we've had a few requests for that. Targeting v2.6.

**Comment by silverwind** [comment]
I've also been looking for such an option. :+1:

**Comment by brylie** [comment]
From a usability perspective, and in saving people strain when reading these charts, it might be worthwhile to enable the `start_at_min` and `end_at_max` by default (setting to `true`).

**Comment by almossawi** [comment]
@brylie Absolutely: https://github.com/mozilla/metrics-graphics/issues/489

October is the month for getting  2.7 out the door :)

**Comment by brylie** [comment]
Cool, are there any 'low hanging fruit' or easy tasks in the 2.7 backlog to which I may contribute?

**Comment by almossawi** [comment]
@brylie Take your pick :) https://github.com/mozilla/metrics-graphics/issues?q=is%3Aopen+is%3Aissue 

Here's the prioritized list, though I suspect several of those unassigned open issues will make it in too: https://github.com/mozilla/metrics-graphics/milestones/v2.7

**Comment by almossawi** [comment]
See the most recent commit referenced above. The proposed option, ``axes_not_compact``, does away with the need to have to set multiple options and avoids unevenly spaced ticks. It's on by default for now.

<img width="623" alt="screen shot 2015-10-15 at 1 38 58 pm" src="https://cloud.githubusercontent.com/assets/980049/10526889/389cb100-7342-11e5-9dd2-00f519fdca15.png">

<img width="658" alt="screen shot 2015-10-15 at 1 39 03 pm" src="https://cloud.githubusercontent.com/assets/980049/10526891/3ab87faa-7342-11e5-92e0-efeafe711459.png">
