### ISSUE TITLE
Extra tick when xax_start_at_min is true

### ISSUE THREAD

**Issue by Tchanders** [mozilla/metrics-graphics#458]
Sometimes when xax_start_at_min is set to true, an extra tick could be put in. E.g. I'm working on a graph where this happens:

xax_start_at_min: false
![selection_011](https://cloud.githubusercontent.com/assets/10440647/8582141/e080625a-25bc-11e5-8d70-54171857aa0b.png)

xax_start_at_min: true
![selection_012](https://cloud.githubusercontent.com/assets/10440647/8582146/eaacca34-25bc-11e5-934b-253ac01eac26.png)

In this case it would make sense to have a tick for June 20.

**Comment by almossawi** [comment]
Being tracked in #456 and #489, so I'll close this if you don't mind.
