### ISSUE TITLE
cannot plot parametric curves

### ISSUE THREAD

**Issue by mndrake** [mozilla/metrics-graphics#460]
When trying to plot a closed "loop", in this case something that should plot a simple hourglass like shape it appears that the data is being sorted first instead of being used in the order given. Is it possible to have sort as an optional parameter?  

http://jsfiddle.net/mndrake/hk63jfg3/12/

```javascript
    MG.data_graphic({
        data: [{x: 1, y: 3},
               {x: 3, y: 1},
               {x: 1, y: 1},
               {x: 3, y: 3},
               {x: 1, y: 3}],
        width: 400,
        height: 250,
        interpolate: 'basic',
        target: '#test',
        x_accessor: 'x',
        y_accessor: 'y',
        area: false
    });
```

**Comment by mndrake** [comment]
commenting out the following code solves the issue. If a "sort" parameter was added then the logic could just be `arg.chart_type === 'line' && arg.x_sort === true`

https://github.com/mozilla/metrics-graphics/blob/master/src/js/misc/process.js#L61

```javascript
    //sort x-axis data
    if (args.chart_type === 'line') {
        for (var i = 0; i < args.data.length; i++) {
            args.data[i].sort(function(a, b) {
                return a[args.x_accessor] - b[args.x_accessor];
            });
        }
    }
```

**Comment by almossawi** [comment]
Merged and [updated the wiki](https://github.com/mozilla/metrics-graphics/wiki/Data#x_sort). Thanks.
