### ISSUE TITLE
Show more decimal places on axes if values are small

### ISSUE THREAD

**Issue by Tchanders** [mozilla/metrics-graphics#463]
(Related to #395) The y axis shows repeated labels if the values are small:

![screenshot from 2015-07-12 14 39 54](https://cloud.githubusercontent.com/assets/10440647/8638035/7d616080-28a4-11e5-8d02-650169573b51.png)

I initially corrected the above graph by setting the decimals option to a higher number, but as live data came in with even smaller values, the repeated values in the y axis appeared again. Obviously this can be corrected by setting the decimals option to an even higher number, but it would make more sense to add more decimal places automatically in these situations, since the order of magnitude of the data can be unpredictable.

**Comment by almossawi** [comment]
Indeed, targeting 2.7.

**Comment by almossawi** [comment]
@Tchanders In the meantime, you can override the default precision by setting [decimals](https://github.com/mozilla/metrics-graphics/wiki/Graphic#decimals).

<img width="513" alt="screen shot 2015-09-08 at 1 56 21 pm" src="https://cloud.githubusercontent.com/assets/980049/9747449/74c4c104-5632-11e5-907f-20e480648b7a.png">
