### ISSUE TITLE
Y axis min + max with negative values

### ISSUE THREAD

**Issue by dareid** [mozilla/metrics-graphics#464]
The automatic selection of min and max Y axis values are incorrect for negative data sets.

For example:

```
MG.data_graphic({
  title: "UFO Sightings",
  description: "Yearly UFO sightings from 1945 to 2010.",
  data: [
      {
        "year": "1945",
        "sightings": -6
      },
      {
        "year": "1946",
        "sightings": -8
      },
      {
        "year": "1947",
        "sightings": -34
      },
      {
        "year": "1948",
        "sightings": -8
      },
      {
        "year": "1949",
        "sightings": -15
      }
  ],
  width: 400,
  height: 250,
  target: ".result",
  x_accessor: "year",
  y_accessor: "sightings"
});
```

**Comment by almossawi** [comment]
Thanks, targeting 2.7.

**Comment by almossawi** [comment]
This should now be fixed. Thanks.

<img width="376" alt="screen shot 2015-10-15 at 2 24 15 pm" src="https://cloud.githubusercontent.com/assets/980049/10528026/9ff700ca-7348-11e5-94c5-7b5f9ff95967.png">

**Comment by hamilton** [comment]
This behavior will likely be changed soon. We are not at the moment showing areas from the zero boundary, and I think we probably should if we want to have these area charts go negative.
