### ISSUE TITLE
Allow points to be clicked / event capture

### ISSUE THREAD

**Issue by garygreen** [mozilla/metrics-graphics#468]
Is it possible to capture an event when a data (dot/value) is clicked on and capture the value/details? 

My use case is where I plot a graph of number of members who have joined the site. When I click on a date I would like to capture the date and open a new page (/members?join_date=<date>) which lists more detailed information about members that joined on that date.

I'm sure there is lots of other use cases for capturing the clicked point and showing more details etc.

**Comment by almossawi** [comment]
Say your marker is defined like this:

```javascript
markers: [{'date': new Date('2014-02-01T00:00:00.000Z'), 'label': '"Something happened'}]
```

Then you could do:

```javascript
d3.selectAll('.mg-marker-text').on('click', function(d, i) {
    var format = d3.time.format('%Y-%m-%d');
    window.location.href = '/members?join_date=' + format(d.date);
});
```

And add this to your stylesheet:

```css
.mg-markers text {
    cursor: pointer;
}
```

Or am I misunderstanding the question?

<img width="1680" alt="screen shot 2015-07-17 at 9 23 48 am" src="https://cloud.githubusercontent.com/assets/980049/8751973/b02bd92c-2c65-11e5-85d5-f514ba21318f.png">

**Comment by garygreen** [comment]
Not with markers but `data`, is that possible?

**Comment by almossawi** [comment]
Sure, so for a line chart:

```javascript
d3.selectAll('.mg-rollover-rect rect').on('click', function(d, i) {
    console.log(d, i);
});
```

For a scatterplot:

```javascript
d3.selectAll('.mg-voronoi path').on('click', function(d, i) {
    console.log(d.point, i);
});
```

And then similarly for the other chart types.

**Comment by lambdamusic** [comment]
Hi, I've tried this code: 


```
// *1*

d3.json('{{ STATIC_URL }}wikilinks/fake_users3.json', function(data) {
    MG.data_graphic({
        title: "Years Chart",
        description: "This is a simple line chart. You can remove the area portion by adding area: false to the arguments list.",
        data: data,
        width: 1200,
        height: 200,
        right: 40,
        target: document.getElementById('wikichart'),
        x_accessor: 'year',
        y_accessor: 'value'
    });
	
});

// *2*
d3.selectAll('.mg-line1-color rect').on('click', function(d, i) {
    alert(d, i);
});
```

But the click event isn't captured because -2- gets run before -1- is completed... (I think!) 
....can you please advice on what's the correct way to queue the commands? 

Tx

**Comment by Hemanthvinayac** [comment]
@almossawi. can you please explain how to get the date & value at that particular data point?.
example using alert would be helpful.
Thanks in advance

**Comment by almossawi** [comment]
@Hemanthvinayac _d_ is your data object, hence _d.date_ and _d.value_.

**Comment by Hemanthvinayac** [comment]
@almossawi That's working fine, thank you
