### ISSUE TITLE
MG.convert.date not working with some date strings

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#469]
Given the following code:
```javascript
var dateObject = {date: "Thu Jul 09 2015 00:00:00 GMT+0300 (EEST)"};
MG.convert.date(dateObject, 'date');
```

I get the following error:
```
TypeError: e.map is not a function
```

What data type is the `MG.convert.date()` expecting for the date property?

**Comment by almossawi** [comment]
Two things:

1. Your date object ought to be an array.
2. You'll need to pass into [MG.convert.date](https://github.com/mozilla/metrics-graphics/wiki/Convenience-Functions#mg-convert-date) a specifier that exactly matches your date format, as that function uses [d3.time.format.parse](https://github.com/mbostock/d3/wiki/Time-Formatting#parse) to parse dates. To my knowledge, there isn't a way to match your time zones in parentheses, so you'll either need to get rid of those, following which you would do this:

```javascript
var dateObject = [
  {
    date: "Thu Jul 09 2015 00:00:00 GMT+0300"
  }
];

MG.convert.date(dateObject, 'date', "%a %b %d %Y %H:%M:%S GMT%Z");
```

Or use JavaScript's [Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse):

```javascript
var dateObject = [
  {
    date: "Thu Jul 09 2015 00:00:00 GMT+0300 (EEST)"
  }
];

dateObject.map(function(d) {
  d.date = new Date(d.date);
});
```

For an explanation of what each of the directives in the first example matches against, see the [D3 documentation](https://github.com/mbostock/d3/wiki/Time-Formatting).

**Comment by brydavis** [comment]
Tried to replicate example [here](http://metricsgraphicsjs.org/examples.htm#lines) and got the same problem

**Comment by brylie** [comment]
OK, how should we document data types for arguments?

**Comment by brylie** [comment]
I.e. the following line in the documentation is ambiguous at the least and possibly misleading:

> Converts a data object's values from strings to javascript Date objects

**Comment by hamilton** [comment]
I'd say it is "ambiguous". I think a slight clarification in the wiki should clear up this issue.

**Comment by GelLiNN** [comment]
What format is MG.convert turning the date into?  Because I already have to iterate through the JSON array cleaning up the data and making it all nice and expected for Metricsgraphics.  If I know the format it's expecting I can make my filtered array already have that format.

**Comment by markosole** [comment]
Hi all. I have similar problem with date value. I need this format "Y-m-d H:M:S" but can not make it work. The only thing that works but with side effects it timestamp as a date value. 
Now I have it working with timestamp but I would like to fix x axis which shows number (timestamp) instead of string date. How can I convert it? 
Maybe something like this `d3.time.format('%b %d')` - this did not work. 
Thanks
