### ISSUE TITLE
How to make a trend line in a line chart?

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#471]
I have a line chart, which is somewhat erratic, and would like to see whether the data is generally trending upwards or downwards. How do I make a trend line with a line chart?

I have found documentation on `least_squares` and notice the example of a confidence line, but am not sure if these methods are relevant here.

**Comment by almossawi** [comment]
Yes. There are [a couple of examples](http://metricsgraphicsjs.org/examples.htm#experimental) that show how to use it. If you come across any issues, feel free to file bugs as that's still a work-in-progress.

**Comment by brylie** [comment]
OK, thanks. I wasn't sure if the examples would work with a line chart.
