### ISSUE TITLE
Allow dates to be UTC rather than local

### ISSUE THREAD

**Issue by Tchanders** [mozilla/metrics-graphics#479]
We're having a problem in crash-stats with dates being converted to local time. This means that users in different countries see different graphs: crashes look like they have occurred on different dates depending on where the user is. The problem happens when d3.time.scale() is called. If d3.time.scale.utc() is called, the problem goes away. Could we have an option for having UTC dates, where d3.time.scale.utc() gets called instead?

**Comment by Tchanders** [comment]
...And d3.time.format() would also have to be replaced by d3.time.format.utc()

**Comment by almossawi** [comment]
Are you recording just dates or datetimes? As far as I know--and this may have changed since I last read about it--you ought to get the desired result by including times and appending the Z specifier to the end (per the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601#Times) format) if UTC.

**Comment by Tchanders** [comment]
They are actually time stamps, which we convert into JavaScript Date objects (so the value is still a time stamp). We hand them to Metrics Graphics, which (I think) applies d3.time.scale to convert them into x-coordinates, but the problem is that this function converts a JavaScript Date into local time.

As far as I can tell there's nothing we can do at our end, but please correct me if I'm mistaken!

**Comment by almossawi** [comment]
Got it. Let's have the time scale function be an option then. @hamilton Sounds good to you?

Targeting 2.7, which I'll start working on this coming Tuesday.

**Comment by hamilton** [comment]
I think this a smart move. More nuanced date and time handling is always a
priority.
