### ISSUE TITLE
Error when using Peity.js and metricsgraphics.js together

### ISSUE THREAD

**Issue by AsMoh** [mozilla/metrics-graphics#482]
I tried to draw bar chart using Peity.js, and it worked. I tried to draw another graph using metricsgraphics.js, and it worked. However, when I combine them , it gives me error:
![error1](https://cloud.githubusercontent.com/assets/10277729/9170742/9fa60a4a-3f76-11e5-99e2-47fde806679b.jpg)

Can you help me to solve this problem, please?

This is the metricsgraphics code for my chart.. When I add it, I get the error.

grapghData=
[
      {  "date": "2014-04-23",  "value": 115877608   },
       {  "date": "2014-04-24", "value": 132088857  },
        { "date": "2014-04-25","value": 112071353  },
        { "date": "2014-04-26", "value": 81790062 },
        { "date": "2014-04-27", "value": 105003761 },
        { "date": "2014-04-28",  "value": 100457727 },
        { "date": "2014-04-29", "value": 118253926 },
        { "date": "2014-04-30", "value": 67956992  }
    ];

grapghData = MG.convert.date(grapghData, 'date');
    MG.data_graphic({
        title: "Line Chart",
        description: "This is a simple line chart. You can remove the area portion by adding area: false to the arguments list.",
        data: grapghData,
        width: 600,
        height: 200,
        right: 40,
        target: document.getElementById('fake_users1'),
        x_accessor: 'date',
        y_accessor: 'value'
    });

Thank you in dvance..

**Comment by almossawi** [comment]
Would you mind sharing a link so that I can reproduce the error?

**Comment by AsMoh** [comment]
Hi ,

This is the link ..
https://drive.google.com/file/d/0B2NyxfyoVjxcUFNGZWJHU1ZNS0E/view?usp=sharing

Thanks...

**Comment by AsMoh** [comment]
??????????????

**Comment by almossawi** [comment]
Seems like the issue is with ``materialize.min.js``. Taking out that line fixes the issue.
