### ISSUE TITLE
I think four tests are written incorrectly (they are failing when they should be passing)

### ISSUE THREAD

**Issue by zacharystenger** [mozilla/metrics-graphics#484]
I just got a clone of MetricsGraphics up and running and when I ran gulp test I noticed 4 failing tests. Looking into it I believe the tests are written incorrectly.  Here is a list of where the errors are:

chart_title_test.js: line 16 (test Chart title is updated)
init_test.js: line 22 (test Chart's width is set correctly on subsequent calls to existing chart)
init_test.js: line 44 (test Chart's height is set correctly on subsequent calls to existing chart)
missing_test.js: line 75 (test Missing chart's width is set correctly on subsequent calls to existing chart)

chart_title_test is currently using

    .innerText

which returns undefined.  Using the following correctly returns bar

    .firstChild.nodeValue

(Side note: there is also a typo in the message returned, it says 'Chart title is foo' when it should say 'Chart title is bar')

The other three tests are using

    .offsetWidth

and

    .offsetHeight

which return undefined. Should they be using

    .getAttribute('width')

and

    .getAttribute('height')

instead? These return the correct value and the tests pass but changing the tests themselves to make them pass is iffy. Also I'm very new to the MetricsGraphics project so maybe I'm missing something. 

Please let me know if any or all of these fixes seem correct and if I should submit a separate PR for each or can lump them all together.

Thanks

**Comment by almossawi** [comment]
hmmm... I'm unable to see any failing tests on my end.
