### ISSUE TITLE
Why a Vertical line?

### ISSUE THREAD

**Issue by christinalau** [mozilla/metrics-graphics#487]
Hi, I have some data that is a little strange. They look like this:
...
Thu Aug 27 2015 10:10:33 GMT-0400 (EDT) 1440684633894 359.43073
Thu Aug 27 2015 10:10:28 GMT-0400 (EDT) 1440684628733 359.80908
Thu Aug 27 2015 10:10:23 GMT-0400 (EDT) 1440684623549 0.1661071
Thu Aug 27 2015 10:10:18 GMT-0400 (EDT) 1440684618187 0.56207275

Somehow the change in data gives me a vertical line, this is not what I expect. Is there a way to display the data so that it look more like the read data? Thanks...

![question](https://cloud.githubusercontent.com/assets/5726085/9739944/2fddf388-5620-11e5-9059-a8cac3fbec4c.png)

**Comment by almossawi** [comment]
What code are you using to plot the chart?

This code will give you the chart below:

```javascript
var data = [
    {
        date: new Date('Thu Aug 27 2015 10:10:33 GMT-0400 (EDT)'),
        val1: 1440684633894,
        val2: 359.43073
    },
    {
        date: new Date('Thu Aug 27 2015 10:10:28 GMT-0400 (EDT)'),
        val1: 1440684628733,
        val2: 359.80908
    },
    {
        date: new Date('Thu Aug 27 2015 10:10:23 GMT-0400 (EDT)'),
        val1: 1440684623549,
        val2: 0.1661071
    },
    {
        date: new Date('Thu Aug 27 2015 10:10:18 GMT-0400 (EDT)'),
        val1: 1440684618187,
        val2: 0.56207275
    }
];

MG.data_graphic({
  data: data,
  target: ".result",
  x_accessor: "date",
  y_accessor: "val1",
  interpolate: "monotone"
});
```

![2015-09-08](https://cloud.githubusercontent.com/assets/980049/9742858/dc50b97e-5617-11e5-92bd-76d50624bb3f.gif)

**Comment by christinalau** [comment]
Here is the code.
hljs.initHighlightingOnLoad();

    MG.data_graphic({
        title: title,
        area: false,
        description: desc,    
        data: data,
        width: 700,
        height: 200,
        right: 100,
        decimals: 14,
        legend: legend,
        target: target})

Here is the complete data:
[{"date":"2015-09-03T19:39:01.474Z","value":339.08115},{"date":"2015-09-03T19:38:50.765Z","value":339.08115},{"date":"2015-09-03T19:38:45.548Z","value":339.08115},{"date":"2015-09-03T19:38:40.378Z","value":339.08115},{"date":"2015-09-03T19:38:35.669Z","value":339.08115},{"date":"2015-08-27T14:15:13.303Z","value":339.44354},{"date":"2015-08-27T14:15:08.146Z","value":339.8419},{"date":"2015-08-27T14:15:02.968Z","value":340.18997},{"date":"2015-08-27T14:14:57.792Z","value":340.51233},{"date":"2015-08-27T14:14:52.592Z","value":340.87933},{"date":"2015-08-27T14:14:47.421Z","value":341.2071},{"date":"2015-08-27T14:14:42.273Z","value":341.59045},{"date":"2015-08-27T14:14:37.090Z","value":341.95895},{"date":"2015-08-27T14:14:31.909Z","value":342.3041},{"date":"2015-08-27T14:14:26.723Z","value":342.6076},{"date":"2015-08-27T14:14:21.556Z","value":342.91397},{"date":"2015-08-27T14:14:16.351Z","value":343.32315},{"date":"2015-08-27T14:14:11.187Z","value":343.77618},{"date":"2015-08-27T14:14:06.015Z","value":344.1568},{"date":"2015-08-27T14:14:00.855Z","value":344.50546},{"date":"2015-08-27T14:13:55.663Z","value":344.88483},{"date":"2015-08-27T14:13:50.506Z","value":345.28085},{"date":"2015-08-27T14:13:45.359Z","value":345.68518},{"date":"2015-08-27T14:13:40.149Z","value":346.05853},{"date":"2015-08-27T14:13:34.984Z","value":346.43457},{"date":"2015-08-27T14:13:29.823Z","value":346.83087},{"date":"2015-08-27T14:13:24.615Z","value":347.14825},{"date":"2015-08-27T14:13:19.412Z","value":347.55698},{"date":"2015-08-27T14:13:14.263Z","value":347.90585},{"date":"2015-08-27T14:13:09.114Z","value":348.23535},{"date":"2015-08-27T14:13:03.920Z","value":348.6713},{"date":"2015-08-27T14:12:58.727Z","value":349.00705},{"date":"2015-08-27T14:12:53.554Z","value":349.33954},{"date":"2015-08-27T14:12:48.398Z","value":349.74628},{"date":"2015-08-27T14:12:43.222Z","value":350.10028},{"date":"2015-08-27T14:12:37.995Z","value":350.44708},{"date":"2015-08-27T14:12:32.830Z","value":350.8391},{"date":"2015-08-27T14:12:27.649Z","value":351.2082},{"date":"2015-08-27T14:12:22.489Z","value":351.448},{"date":"2015-08-27T14:12:17.298Z","value":351.79724},{"date":"2015-08-27T14:12:12.156Z","value":352.24408},{"date":"2015-08-27T14:12:06.956Z","value":352.50107},{"date":"2015-08-27T14:12:01.821Z","value":352.9288},{"date":"2015-08-27T14:11:56.632Z","value":353.3258},{"date":"2015-08-27T14:11:51.498Z","value":353.69556},{"date":"2015-08-27T14:11:46.302Z","value":354.01324},{"date":"2015-08-27T14:11:41.164Z","value":354.5074},{"date":"2015-08-27T14:11:35.951Z","value":354.88086},{"date":"2015-08-27T14:11:30.782Z","value":355.35626},{"date":"2015-08-27T14:11:25.624Z","value":355.77286},{"date":"2015-08-27T14:11:20.452Z","value":356.1131},{"date":"2015-08-27T14:11:15.258Z","value":356.36896},{"date":"2015-08-27T14:11:10.073Z","value":356.71405},{"date":"2015-08-27T14:11:04.917Z","value":357.1374},{"date":"2015-08-27T14:10:59.752Z","value":357.5417},{"date":"2015-08-27T14:10:54.584Z","value":357.9048},{"date":"2015-08-27T14:10:49.418Z","value":358.24014},{"date":"2015-08-27T14:10:44.257Z","value":358.58112},{"date":"2015-08-27T14:10:39.058Z","value":358.9777},{"date":"2015-08-27T14:10:33.894Z","value":359.43073},{"date":"2015-08-27T14:10:28.733Z","value":359.80908},{"date":"2015-08-27T14:10:23.549Z","value":0.16610718},{"date":"2015-08-27T14:10:18.187Z","value":0.56207275},{"date":"2015-08-27T14:10:13.037Z","value":0.9112854},{"date":"2015-08-27T14:10:07.859Z","value":1.3410645},{"date":"2015-08-27T14:10:02.678Z","value":1.7168579},{"date":"2015-08-27T14:09:57.601Z","value":2.0374146},{"date":"2015-08-27T14:09:52.320Z","value":2.4422607},{"date":"2015-08-27T14:09:47.151Z","value":2.7370605},{"date":"2015-08-27T14:09:41.944Z","value":3.0750732},{"date":"2015-08-27T14:09:36.781Z","value":3.4214478},{"date":"2015-08-27T14:09:31.570Z","value":3.8310547},{"date":"2015-08-27T14:09:26.410Z","value":4.168701},{"date":"2015-08-27T14:09:21.218Z","value":4.5076904},{"date":"2015-08-27T14:09:15.983Z","value":4.903015},{"date":"2015-08-27T14:09:10.787Z","value":5.2953796},{"date":"2015-08-27T14:09:05.565Z","value":5.6881104},{"date":"2015-08-27T14:09:00.403Z","value":6.071991},{"date":"2015-08-27T14:08:55.202Z","value":6.4374695},{"date":"2015-08-27T14:08:50.044Z","value":6.8303223},{"date":"2015-08-27T14:08:44.865Z","value":7.2664185},{"date":"2015-08-27T14:08:39.747Z","value":7.606964},{"date":"2015-08-27T14:08:34.491Z","value":7.9283752},{"date":"2015-08-27T14:08:29.345Z","value":8.325256},{"date":"2015-08-27T14:08:24.170Z","value":8.738159},{"date":"2015-08-27T14:08:19.022Z","value":9.044067},{"date":"2015-08-27T14:08:13.823Z","value":9.416473},{"date":"2015-08-27T14:08:08.647Z","value":9.677673},{"date":"2015-08-27T14:08:03.513Z","value":10.041809},{"date":"2015-08-27T14:07:58.304Z","value":10.432983},{"date":"2015-08-27T14:07:53.115Z","value":10.802765},{"date":"2015-08-27T14:07:48.040Z","value":11.110809},{"date":"2015-08-27T14:07:42.844Z","value":11.46756},{"date":"2015-08-27T14:07:37.600Z","value":11.812988},{"date":"2015-08-27T14:07:32.417Z","value":12.225861},{"date":"2015-08-27T14:07:27.262Z","value":12.577026},{"date":"2015-08-27T14:07:22.104Z","value":12.933716},{"date":"2015-08-27T14:07:16.914Z","value":13.322327},{"date":"2015-08-27T14:07:11.783Z","value":13.766235},{"date":"2015-08-27T14:07:06.556Z","value":13.997345}]

**Comment by almossawi** [comment]
Oh, I see. So you have data points that are minutes apart, then a gap of six days, and then five data points that are minutes apart. That's why the variability in the first set is being lost.

![2015-09-08](https://cloud.githubusercontent.com/assets/980049/9744722/704d82ba-5622-11e5-8221-0c73edde20f6.gif)

You can either increase the chart's width, which may or may not help, or use the [mg-line-brushing](https://github.com/dandehavilland/mg-line-brushing) addon ([demo](http://metricsgraphicsjs.org/examples.htm#addons)) to add the ability to zoom in and out of the chart.

**Comment by christinalau** [comment]
I have tried both approaches and they don't work. The first approach has no effect, and the 2nd approach seems to have a non-responsive d3 script error. Does it work for you? Unfortunately I do not have ability to change the original data. Thanks for any help.

**Comment by almossawi** [comment]
Apologies for the late reply. Unfortunately, it's going to be challenging for you to see all of the variability in your data, given that it essentially looks like this:

<img width="596" alt="screen shot 2015-10-15 at 6 02 31 pm" src="https://cloud.githubusercontent.com/assets/980049/10531515/85594c4a-7367-11e5-8a20-57a70d8f034c.png">


The brushing addon ought to work fine:

![brushing](https://cloud.githubusercontent.com/assets/980049/10531510/761c96ba-7367-11e5-82df-4ec06df783f8.gif)

Here is the code that you'll want to use:

```html
<script src="js/addons/mg_line_brushing.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="css/addons/mg_line_brushing.css" type="text/css" charset="utf-8" />

<script>
var data = [{"date":"2015-09-03T19:39:01.474Z","value":339.08115},{"date":"2015-09-03T19:38:50.765Z","value":339.08115},{"date":"2015-09-03T19:38:45.548Z","value":339.08115},{"date":"2015-09-03T19:38:40.378Z","value":339.08115},{"date":"2015-09-03T19:38:35.669Z","value":339.08115},{"date":"2015-08-27T14:15:13.303Z","value":339.44354},{"date":"2015-08-27T14:15:08.146Z","value":339.8419},{"date":"2015-08-27T14:15:02.968Z","value":340.18997},{"date":"2015-08-27T14:14:57.792Z","value":340.51233},{"date":"2015-08-27T14:14:52.592Z","value":340.87933},{"date":"2015-08-27T14:14:47.421Z","value":341.2071},{"date":"2015-08-27T14:14:42.273Z","value":341.59045},{"date":"2015-08-27T14:14:37.090Z","value":341.95895},{"date":"2015-08-27T14:14:31.909Z","value":342.3041},{"date":"2015-08-27T14:14:26.723Z","value":342.6076},{"date":"2015-08-27T14:14:21.556Z","value":342.91397},{"date":"2015-08-27T14:14:16.351Z","value":343.32315},{"date":"2015-08-27T14:14:11.187Z","value":343.77618},{"date":"2015-08-27T14:14:06.015Z","value":344.1568},{"date":"2015-08-27T14:14:00.855Z","value":344.50546},{"date":"2015-08-27T14:13:55.663Z","value":344.88483},{"date":"2015-08-27T14:13:50.506Z","value":345.28085},{"date":"2015-08-27T14:13:45.359Z","value":345.68518},{"date":"2015-08-27T14:13:40.149Z","value":346.05853},{"date":"2015-08-27T14:13:34.984Z","value":346.43457},{"date":"2015-08-27T14:13:29.823Z","value":346.83087},{"date":"2015-08-27T14:13:24.615Z","value":347.14825},{"date":"2015-08-27T14:13:19.412Z","value":347.55698},{"date":"2015-08-27T14:13:14.263Z","value":347.90585},{"date":"2015-08-27T14:13:09.114Z","value":348.23535},{"date":"2015-08-27T14:13:03.920Z","value":348.6713},{"date":"2015-08-27T14:12:58.727Z","value":349.00705},{"date":"2015-08-27T14:12:53.554Z","value":349.33954},{"date":"2015-08-27T14:12:48.398Z","value":349.74628},{"date":"2015-08-27T14:12:43.222Z","value":350.10028},{"date":"2015-08-27T14:12:37.995Z","value":350.44708},{"date":"2015-08-27T14:12:32.830Z","value":350.8391},{"date":"2015-08-27T14:12:27.649Z","value":351.2082},{"date":"2015-08-27T14:12:22.489Z","value":351.448},{"date":"2015-08-27T14:12:17.298Z","value":351.79724},{"date":"2015-08-27T14:12:12.156Z","value":352.24408},{"date":"2015-08-27T14:12:06.956Z","value":352.50107},{"date":"2015-08-27T14:12:01.821Z","value":352.9288},{"date":"2015-08-27T14:11:56.632Z","value":353.3258},{"date":"2015-08-27T14:11:51.498Z","value":353.69556},{"date":"2015-08-27T14:11:46.302Z","value":354.01324},{"date":"2015-08-27T14:11:41.164Z","value":354.5074},{"date":"2015-08-27T14:11:35.951Z","value":354.88086},{"date":"2015-08-27T14:11:30.782Z","value":355.35626},{"date":"2015-08-27T14:11:25.624Z","value":355.77286},{"date":"2015-08-27T14:11:20.452Z","value":356.1131},{"date":"2015-08-27T14:11:15.258Z","value":356.36896},{"date":"2015-08-27T14:11:10.073Z","value":356.71405},{"date":"2015-08-27T14:11:04.917Z","value":357.1374},{"date":"2015-08-27T14:10:59.752Z","value":357.5417},{"date":"2015-08-27T14:10:54.584Z","value":357.9048},{"date":"2015-08-27T14:10:49.418Z","value":358.24014},{"date":"2015-08-27T14:10:44.257Z","value":358.58112},{"date":"2015-08-27T14:10:39.058Z","value":358.9777},{"date":"2015-08-27T14:10:33.894Z","value":359.43073},{"date":"2015-08-27T14:10:28.733Z","value":359.80908},{"date":"2015-08-27T14:10:23.549Z","value":0.16610718},{"date":"2015-08-27T14:10:18.187Z","value":0.56207275},{"date":"2015-08-27T14:10:13.037Z","value":0.9112854},{"date":"2015-08-27T14:10:07.859Z","value":1.3410645},{"date":"2015-08-27T14:10:02.678Z","value":1.7168579},{"date":"2015-08-27T14:09:57.601Z","value":2.0374146},{"date":"2015-08-27T14:09:52.320Z","value":2.4422607},{"date":"2015-08-27T14:09:47.151Z","value":2.7370605},{"date":"2015-08-27T14:09:41.944Z","value":3.0750732},{"date":"2015-08-27T14:09:36.781Z","value":3.4214478},{"date":"2015-08-27T14:09:31.570Z","value":3.8310547},{"date":"2015-08-27T14:09:26.410Z","value":4.168701},{"date":"2015-08-27T14:09:21.218Z","value":4.5076904},{"date":"2015-08-27T14:09:15.983Z","value":4.903015},{"date":"2015-08-27T14:09:10.787Z","value":5.2953796},{"date":"2015-08-27T14:09:05.565Z","value":5.6881104},{"date":"2015-08-27T14:09:00.403Z","value":6.071991},{"date":"2015-08-27T14:08:55.202Z","value":6.4374695},{"date":"2015-08-27T14:08:50.044Z","value":6.8303223},{"date":"2015-08-27T14:08:44.865Z","value":7.2664185},{"date":"2015-08-27T14:08:39.747Z","value":7.606964},{"date":"2015-08-27T14:08:34.491Z","value":7.9283752},{"date":"2015-08-27T14:08:29.345Z","value":8.325256},{"date":"2015-08-27T14:08:24.170Z","value":8.738159},{"date":"2015-08-27T14:08:19.022Z","value":9.044067},{"date":"2015-08-27T14:08:13.823Z","value":9.416473},{"date":"2015-08-27T14:08:08.647Z","value":9.677673},{"date":"2015-08-27T14:08:03.513Z","value":10.041809},{"date":"2015-08-27T14:07:58.304Z","value":10.432983},{"date":"2015-08-27T14:07:53.115Z","value":10.802765},{"date":"2015-08-27T14:07:48.040Z","value":11.110809},{"date":"2015-08-27T14:07:42.844Z","value":11.46756},{"date":"2015-08-27T14:07:37.600Z","value":11.812988},{"date":"2015-08-27T14:07:32.417Z","value":12.225861},{"date":"2015-08-27T14:07:27.262Z","value":12.577026},{"date":"2015-08-27T14:07:22.104Z","value":12.933716},{"date":"2015-08-27T14:07:16.914Z","value":13.322327},{"date":"2015-08-27T14:07:11.783Z","value":13.766235},{"date":"2015-08-27T14:07:06.556Z","value":13.997345}];
MG.convert.date(data, 'date', '%Y-%m-%dT%H:%M:%S.%LZ');
MG.data_graphic({
    data: data,
    width: 600,
    height: 200,
    right: 40,
    interpolate: 'basic',
    target: '.result'
});
</script>
```

Feel free to reopen the issue if you continue to have problems.
