### ISSUE TITLE
extend x-axis ticks when working with dates

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#489]
The current method for drawing the x-axis ticks when the x accessor targets dates often leaves big gaps between the axis and the left margin. This confuses users and is inelegant. We have a few stopgaps to ameliorate the design issue, but we have decided that it simply makes more sense to extend the x-axis ticks past the range of the line, so that we 1.) get the same design effect, and 2.) remove any chance of too-short axes.

This will effectively solve a few other issues: #458, #456.

**Comment by almossawi** [comment]
@hamilton See what you think of this last commit. ``xax_not_compact`` is on by default for now. The examples don't look too bad.

**Comment by hamilton** [comment]
looks good to me.

**Comment by almossawi** [comment]
Renamed the option to ``axes_not_compact``. MG will transition uses of ``xax_start_at_min`` to ``axes_not_compact`` starting in v2.7. It's on by default for now. Feel free to change that if you have a strong preference for the original one.

**Comment by almossawi** [comment]
Trying to consolidate all issues to do with axes and min, max values. It looks like we can keep track of this in #456, so I'll close this.
