### ISSUE TITLE
add rollover formatting options

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#490]
The default rollover formatting options are very limited. We would like to include custom formatting options that are both powerful and easy. We will be including two new params: ```x_rollover_format``` and ```y_rollover_format```. It takes either a __string__ (depending on what the data type is), or a __function__ (for other / extended cases).

__STRING__

When the accessor is a number, we will provide D3's native number formatting options: https://github.com/mbostock/d3/wiki/Formatting

When the acessor is a date, we will provide D3's native date formatting options: https://github.com/mbostock/d3/wiki/Time-Formatting

__FUNCTION__

If you pass in a function, you get the data point, as before. This should allow for every other useful case we care about.

**Comment by dgilperez** [comment]
+1

**Comment by hamilton** [comment]
@almossawi one way we can make this easier to format is to make a series of tspans within the rollover text element, each one corresponding to the x accessor, y accessor, and perhaps something relating to the group if we have a multiline element. This should then reduce the problem to merely formatting tspans and changing the text within them, which should open up possibilities for other formatting options, if we want to go that direction.

**Comment by almossawi** [comment]
@hamilton Yes, as discussed. That sounds great.

**Comment by hamilton** [comment]
There are issues with these commits.
