### ISSUE TITLE
No area with negative y values

### ISSUE THREAD

**Issue by natefaubion** [mozilla/metrics-graphics#492]
If you have some basic data that alternates between positive and negative like:
```
[
  {"x": 1, "y": -100},
  {"x": 2, "y": -130},
  {"x": 3, "y": -120},
  {"x": 4, "y": -80},
  {"x": 5, "y": 20},
  {"x": 6, "y": 30},
  {"x": 7, "y": -60},
  {"x": 8, "y": -40},
  {"x": 9, "y": 0},
  {"x": 10, "y": 0},
  {"x": 11, "y": -90},
  {"x": 12, "y": -90}
]
```
The chart won't render with an area (the svg element doesn't even exist). I expected it to alternate across 0. Ideally, I'd love to be able to have different colored area for positive and negative values.

**Comment by almossawi** [comment]
@hamilton hmm... I forget why we did this.

https://github.com/mozilla/metrics-graphics/blob/master/src/js/charts/line.js#L157

**Comment by hamilton** [comment]
I think I just never got to it, frankly. We can put it on 2.7 and hit it this quarter.
