### ISSUE TITLE
Add yax_start_at_min option and yax_end_at_max option

### ISSUE THREAD

**Issue by ryanphung** [mozilla/metrics-graphics#495]
Thanks for building such a great tool; I love how everything is so simple and looks great.

This is a feature request. When I enable the option `min_y_from_data`, I notice that sometimes the y-axis marker doesn't start from the bottom and doesn't end at the top of the axis; hence there are large gaps.

There are options to change this behaviour for the x-axis (`xax_start_at_min`, and `xax_end_at_max` is being worked on in #456); but I cannot find similar options for y-axis.

<img width="755" alt="screen shot 2015-09-18 at 12 05 40 pm" src="https://cloud.githubusercontent.com/assets/1664614/9951768/a6da5be0-5dfd-11e5-8f17-1ac81d461943.png">

**Comment by almossawi** [comment]
Thanks for the feature request. We'll be redoing the way axes work starting next month (see https://github.com/mozilla/metrics-graphics/issues/489), which we're planning to dedicate to the 2.7 release. That will do away with the need to have separate options to extend the axes and ought to make things a lot clearer.

**Comment by ryanphung** [comment]
Hi @almossawi, thank you for the update.

**Comment by almossawi** [comment]
Being tracked in #456 and #489, so I'll close this, if you don't mind.
