### ISSUE TITLE
Add option to consider baselines when min_y_from_data is enabled

### ISSUE THREAD

**Issue by ryanphung** [mozilla/metrics-graphics#496]
Thanks for building this awesome tool.

`min_y_from_data` is a great option. When using this together with baselines, I notice that sometimes the baseline is not displayed in the chart because the baseline is not within the chart data range. I understand that this could be the intended behaviour.

Would be great if there is an option that allows `min_y_from_data` to take into consideration the baselines as well. In other words, treat the baseline as chart data.

**Comment by almossawi** [comment]
Thanks, targeting v2.7.

**Comment by almossawi** [comment]
Fixed. Feel free to reopen if you notice any issues.

**Comment by ryanphung** [comment]
Thank you, I'll report if I encounter any issue
