### ISSUE TITLE
Is there a way to make the rollover float or follow the mouse?

### ISSUE THREAD

**Issue by dgilperez** [mozilla/metrics-graphics#497]
I have a graph whose width exceeds the container and I'm using a scrollbar to show it in full. As the rollover is placed at the top right corner by default, it will be hidden for the most part of the chart. 

The ideal solution for me would be to provide an option for the rollover to track the mouse and appear some pixels above the cursor. 

Is there a built-in way for that? Any combination of options? I can also have a look at the code and send a PR for that, but I'd appreciate some hints about where to start.

**Comment by dgilperez** [comment]
I have improvised this code, that I share for others to use / improve: 

    mouseover: 
      function(d, i) {
        $('#my_chart svg .mg-active-datapoint-container')
          .attr('transform', 'translate(' + event.clientX + ',20)');
      }

**Comment by hamilton** [comment]
nice :+1:
