### ISSUE TITLE
Rails wrapper gem released

### ISSUE THREAD

**Issue by dgilperez** [mozilla/metrics-graphics#498]
Hi! 

Thanks a lot for a great and very needed library. 

I just wanted to let you know I released a Rails wrapper gem that includes a helper method to ease integration within a Rails app: https://github.com/dgilperez/metrics-graphics-rails, just in case you want to add that to any integration section you may have in the docs. Please let me know if I should do that directly myself.

Cheers!

**Comment by almossawi** [comment]
Hi there,

Wonderful, thank you! I've added it to the wiki: https://github.com/mozilla/metrics-graphics/wiki#gallery

Feel free to modify the entry as you see fit.

**Comment by dgilperez** [comment]
That's great !!! Thanks again for great stuff.
