### ISSUE TITLE
Graph linking and linked_format?

### ISSUE THREAD

**Issue by pcl** [mozilla/metrics-graphics#499]
I'm trying to build a linked set of graphs, but am running into problems. The data on the two graphs are based on fine-grained timestamps. Is there any way to automatically round / bucket points to support linking, or must the x values match up for linking to work?

**Comment by pcl** [comment]
Here's some HTML to demonstrate the problem: https://gist.github.com/pcl/01fd4df5dac3a0b1efed

**Comment by almossawi** [comment]
Yes, you can set [linked_format](https://github.com/mozilla/metrics-graphics/wiki/Graphic#linked_format) to override the class names, e.g. ``linked_format: "%Y-%m-%d-%H-%M-%S"`` for more fine-grained, ``linked_format: "%Y-%m-%d-%H-%M"`` for less fine-grained. For instance:

```javascript
var values = [{"date":"2015-10-01T03:43:17.541", "value": 2},
{"date":"2015-10-01T03:45:18.788", "value": 1},
{"date":"2015-10-01T04:35:47.841", "value": 0},
{"date":"2015-10-01T05:45:40.487", "value": 2},
{"date":"2015-10-01T05:46:55.957", "value": 3},
{"date":"2015-10-01T06:10:46.072", "value": 30},
{"date":"2015-10-01T06:33:57.833", "value": 58},
{"date":"2015-10-01T06:35:46.393", "value": 60},
{"date":"2015-10-01T07:19:15.695", "value": 90},
{"date":"2015-10-01T08:05:14.071", "value": 96},
{"date":"2015-10-01T09:37:36.667", "value": 100},
{"date":"2015-10-01T15:16:01.087", "value": 99},
{"date":"2015-10-01T15:17:27.857", "value": 98},
{"date":"2015-10-01T15:19:53.235", "value": 97},
{"date":"2015-10-01T15:22:32.898", "value": 96},
{"date":"2015-10-01T15:26:28.075", "value": 95},
{"date":"2015-10-01T15:29:39.062", "value": 94},
{"date":"2015-10-01T15:31:40.756", "value": 93},
{"date":"2015-10-01T15:36:23.236", "value": 91},
{"date":"2015-10-01T15:37:29.203", "value": 90},
{"date":"2015-10-01T15:39:09.187", "value": 89},
{"date":"2015-10-01T15:43:48.953", "value": 88},
{"date":"2015-10-01T15:52:16.228", "value": 87},
{"date":"2015-10-01T16:04:36.714", "value": 86},
{"date":"2015-10-01T16:07:16.714", "value": 85},
{"date":"2015-10-01T16:21:49.502", "value": 84},
{"date":"2015-10-01T16:23:09.503", "value": 83},
{"date":"2015-10-01T16:25:50.013", "value": 82},
{"date":"2015-10-01T16:28:19.503", "value": 81},
{"date":"2015-10-01T16:29:39.503", "value": 80},
{"date":"2015-10-01T16:31:19.502", "value": 79},
{"date":"2015-10-01T16:33:59.503", "value": 78},
{"date":"2015-10-01T16:44:04.079", "value": 75},
{"date":"2015-10-01T17:01:32.563", "value": 73},
{"date":"2015-10-01T17:29:25.509", "value": 92},
{"date":"2015-10-01T17:32:26.379", "value": 93},
{"date":"2015-10-01T17:36:40.264", "value": 95},
{"date":"2015-10-01T17:38:31.603", "value": 96},
{"date":"2015-10-01T17:44:00.276", "value": 97},
{"date":"2015-10-01T17:49:33.615", "value": 98},
{"date":"2015-10-01T17:52:58.468", "value": 99},
{"date":"2015-10-01T18:03:38.310", "value": 98},
{"date":"2015-10-01T18:10:35.057", "value": 97},
{"date":"2015-10-01T18:25:25.041", "value": 96},
{"date":"2015-10-01T18:33:01.039", "value": 95},
{"date":"2015-10-01T18:42:23.455", "value": 95},
{"date":"2015-10-01T18:46:52.297", "value": 94},
{"date":"2015-10-01T19:01:15.506", "value": 93},
{"date":"2015-10-01T19:01:41.006", "value": 92},
{"date":"2015-10-01T19:14:47.642", "value": 91},
{"date":"2015-10-01T19:19:00.428", "value": 90},
{"date":"2015-10-01T19:36:43.113", "value": 89},
{"date":"2015-10-01T19:51:34.000", "value": 88},
{"date":"2015-10-01T20:00:58.974", "value": 87},
{"date":"2015-10-01T20:11:59.595", "value": 86},
{"date":"2015-10-01T20:14:02.448", "value": 85},
{"date":"2015-10-01T20:29:31.247", "value": 83},
{"date":"2015-10-01T20:31:53.446", "value": 82},
{"date":"2015-10-01T20:34:43.443", "value": 81},
{"date":"2015-10-01T20:37:23.445", "value": 80},
{"date":"2015-10-01T20:38:43.538", "value": 79},
{"date":"2015-10-01T20:40:40.001", "value": 78},
{"date":"2015-10-01T20:42:40.559", "value": 77},
{"date":"2015-10-01T20:47:29.466", "value": 76},
{"date":"2015-10-01T21:05:48.157", "value": 75},
{"date":"2015-10-01T21:11:39.270", "value": 74},
{"date":"2015-10-01T21:23:38.995", "value": 73},
{"date":"2015-10-01T21:30:11.892", "value": 72},
{"date":"2015-10-01T21:31:08.672", "value": 72},
{"date":"2015-10-01T21:32:18.028", "value": 71},
{"date":"2015-10-01T21:48:15.067", "value": 70},
{"date":"2015-10-01T22:09:17.118", "value": 68},
{"date":"2015-10-01T22:14:47.000", "value": 67},
{"date":"2015-10-01T22:22:34.609", "value": 66},
{"date":"2015-10-01T22:29:57.019", "value": 65},
{"date":"2015-10-01T22:34:47.088", "value": 64},
{"date":"2015-10-01T22:42:20.252", "value": 63}];
var states = [{"date":"2015-10-01T03:44:33.390", "value": 0},
{"date":"2015-10-01T03:44:33.454", "value": 0},
{"date":"2015-10-01T03:45:04.110", "value": 1},
{"date":"2015-10-01T03:45:04.219", "value": 1},
{"date":"2015-10-01T03:45:19.490", "value": 0},
{"date":"2015-10-01T03:45:19.598", "value": 0},
{"date":"2015-10-01T04:37:37.047", "value": 1},
{"date":"2015-10-01T04:37:37.139", "value": 1},
{"date":"2015-10-01T04:38:09.370", "value": 0},
{"date":"2015-10-01T04:38:09.493", "value": 0},
{"date":"2015-10-01T05:45:42.383", "value": 1},
{"date":"2015-10-01T05:45:51.139", "value": 1},
{"date":"2015-10-01T05:46:57.150", "value": 1},
{"date":"2015-10-01T05:46:58.395", "value": 1},
{"date":"2015-10-01T05:48:29.738", "value": 0},
{"date":"2015-10-01T05:48:29.938", "value": 0},
{"date":"2015-10-01T05:48:30.213", "value": 1},
{"date":"2015-10-01T05:48:30.281", "value": 1},
{"date":"2015-10-01T05:48:32.866", "value": 0},
{"date":"2015-10-01T05:48:33.050", "value": 0},
{"date":"2015-10-01T14:37:17.437", "value": 1},
{"date":"2015-10-01T14:37:17.522", "value": 1},
{"date":"2015-10-01T14:44:35.198", "value": 0},
{"date":"2015-10-01T14:44:35.268", "value": 0},
{"date":"2015-10-01T15:07:16.353", "value": 0},
{"date":"2015-10-01T15:07:16.426", "value": 0},
{"date":"2015-10-01T15:07:27.272", "value": 1},
{"date":"2015-10-01T15:07:27.439", "value": 1},
{"date":"2015-10-01T15:08:28.196", "value": 0},
{"date":"2015-10-01T15:08:28.353", "value": 0},
{"date":"2015-10-01T15:09:06.493", "value": 1},
{"date":"2015-10-01T15:09:06.530", "value": 1},
{"date":"2015-10-01T15:09:38.782", "value": 0},
{"date":"2015-10-01T15:09:38.826", "value": 0},
{"date":"2015-10-01T15:14:58.698", "value": 1},
{"date":"2015-10-01T15:14:58.759", "value": 1},
{"date":"2015-10-01T15:15:02.902", "value": 0},
{"date":"2015-10-01T15:15:02.938", "value": 0},
{"date":"2015-10-01T15:18:59.343", "value": 1},
{"date":"2015-10-01T15:18:59.425", "value": 1},
{"date":"2015-10-01T15:20:14.158", "value": 0},
{"date":"2015-10-01T15:20:14.199", "value": 0},
{"date":"2015-10-01T15:21:30.454", "value": 1},
{"date":"2015-10-01T15:21:30.508", "value": 1},
{"date":"2015-10-01T15:24:33.494", "value": 0},
{"date":"2015-10-01T15:24:33.564", "value": 0},
{"date":"2015-10-01T15:27:53.422", "value": 1},
{"date":"2015-10-01T15:27:53.487", "value": 1},
{"date":"2015-10-01T15:30:50.998", "value": 0},
{"date":"2015-10-01T15:30:51.531", "value": 0},
{"date":"2015-10-01T15:38:02.094", "value": 1},
{"date":"2015-10-01T15:38:02.199", "value": 1},
{"date":"2015-10-01T15:40:43.317", "value": 0},
{"date":"2015-10-01T15:40:43.576", "value": 0},
{"date":"2015-10-01T16:03:38.986", "value": 1},
{"date":"2015-10-01T16:03:39.110", "value": 1},
{"date":"2015-10-01T16:08:42.299", "value": 0},
{"date":"2015-10-01T16:08:42.355", "value": 0},
{"date":"2015-10-01T16:21:37.721", "value": 1},
{"date":"2015-10-01T16:21:37.889", "value": 1},
{"date":"2015-10-01T16:36:11.427", "value": 0},
{"date":"2015-10-01T16:36:11.484", "value": 0},
{"date":"2015-10-01T16:55:23.625", "value": 1},
{"date":"2015-10-01T16:55:23.956", "value": 1},
{"date":"2015-10-01T16:55:37.467", "value": 0},
{"date":"2015-10-01T16:55:37.717", "value": 0},
{"date":"2015-10-01T17:36:41.749", "value": 1},
{"date":"2015-10-01T17:36:41.924", "value": 1},
{"date":"2015-10-01T17:37:42.890", "value": 0},
{"date":"2015-10-01T17:37:43.127", "value": 0},
{"date":"2015-10-01T17:55:31.606", "value": 1},
{"date":"2015-10-01T17:55:31.688", "value": 1},
{"date":"2015-10-01T17:55:43.160", "value": 0},
{"date":"2015-10-01T17:55:43.222", "value": 0},
{"date":"2015-10-01T17:56:05.843", "value": 1},
{"date":"2015-10-01T17:56:05.950", "value": 1},
{"date":"2015-10-01T17:58:45.797", "value": 0},
{"date":"2015-10-01T17:58:45.895", "value": 0},
{"date":"2015-10-01T18:12:14.240", "value": 1},
{"date":"2015-10-01T18:12:14.293", "value": 1},
{"date":"2015-10-01T18:12:30.723", "value": 0},
{"date":"2015-10-01T18:12:31.373", "value": 0},
{"date":"2015-10-01T18:46:53.734", "value": 1},
{"date":"2015-10-01T18:46:53.775", "value": 1},
{"date":"2015-10-01T18:47:17.327", "value": 0},
{"date":"2015-10-01T18:47:17.427", "value": 0},
{"date":"2015-10-01T19:01:15.623", "value": 1},
{"date":"2015-10-01T19:01:15.735", "value": 1},
{"date":"2015-10-01T19:02:33.204", "value": 0},
{"date":"2015-10-01T19:02:33.631", "value": 0},
{"date":"2015-10-01T20:11:50.114", "value": 1},
{"date":"2015-10-01T20:11:50.397", "value": 1},
{"date":"2015-10-01T20:12:06.484", "value": 0},
{"date":"2015-10-01T20:12:06.698", "value": 0},
{"date":"2015-10-01T20:14:02.781", "value": 1},
{"date":"2015-10-01T20:14:02.889", "value": 1},
{"date":"2015-10-01T20:14:20.791", "value": 0},
{"date":"2015-10-01T20:14:20.834", "value": 0},
{"date":"2015-10-01T20:29:31.303", "value": 1},
{"date":"2015-10-01T20:29:31.389", "value": 1},
{"date":"2015-10-01T20:29:34.763", "value": 0},
{"date":"2015-10-01T20:29:34.867", "value": 0},
{"date":"2015-10-01T20:37:29.113", "value": 1},
{"date":"2015-10-01T20:37:29.196", "value": 1},
{"date":"2015-10-01T20:37:50.276", "value": 0},
{"date":"2015-10-01T20:37:50.451", "value": 0},
{"date":"2015-10-01T21:29:54.595", "value": 1},
{"date":"2015-10-01T21:29:54.680", "value": 1},
{"date":"2015-10-01T21:30:14.033", "value": 0},
{"date":"2015-10-01T21:30:14.086", "value": 0},
{"date":"2015-10-01T22:45:40.668", "value": 1},
{"date":"2015-10-01T22:45:40.827", "value": 1}];

MG.convert.date(values, 'date', '%Y-%m-%dT%H:%M:%S.%L');
MG.convert.date(states, 'date', '%Y-%m-%dT%H:%M:%S.%L');

MG.data_graphic({
    data: values,
    width: 2200,
    height: 350,
    target: "#result1",
    x_accessor: "date",
    y_accessor: "value",
    linked: true,
    linked_format: "%Y-%m-%d-%H-%M-%S",
    interpolate: "linear"
});
MG.data_graphic({
    data: states,
    width: 2200,
    height: 350,
    target: "#result2",
    x_accessor: "date",
    y_accessor: "value",
    linked: true,
    linked_format: "%Y-%m-%d-%H-%M-%S",
    interpolate: "step-after"
});
```

**Comment by pcl** [comment]
Perfect, thanks. I had tried ISO-8601 format (%Y-%m-%dT%h:%M:%S), which
didn't seem to do anything.

On Mon, Oct 5, 2015 at 9:51 PM, Ali Almossawi <notifications@github.com>
wrote:

> Yes, you can set linked_format
> <https://github.com/mozilla/metrics-graphics/wiki/Graphic#linked_format>
> to override the class names, e.g. linked_format: "%Y-%m-%d-%H-%M-%S" for
> more fine-grained, linked_format: "%Y-%m-%d-%H-%M" for less fine-grained.
> For instance:
>
> var values = [{"date":"2015-10-01T03:43:17.541", "value": 2},
> {"date":"2015-10-01T03:45:18.788", "value": 1},
> {"date":"2015-10-01T04:35:47.841", "value": 0},
> {"date":"2015-10-01T05:45:40.487", "value": 2},
> {"date":"2015-10-01T05:46:55.957", "value": 3},
> {"date":"2015-10-01T06:10:46.072", "value": 30},
> {"date":"2015-10-01T06:33:57.833", "value": 58},
> {"date":"2015-10-01T06:35:46.393", "value": 60},
> {"date":"2015-10-01T07:19:15.695", "value": 90},
> {"date":"2015-10-01T08:05:14.071", "value": 96},
> {"date":"2015-10-01T09:37:36.667", "value": 100},
> {"date":"2015-10-01T15:16:01.087", "value": 99},
> {"date":"2015-10-01T15:17:27.857", "value": 98},
> {"date":"2015-10-01T15:19:53.235", "value": 97},
> {"date":"2015-10-01T15:22:32.898", "value": 96},
> {"date":"2015-10-01T15:26:28.075", "value": 95},
> {"date":"2015-10-01T15:29:39.062", "value": 94},
> {"date":"2015-10-01T15:31:40.756", "value": 93},
> {"date":"2015-10-01T15:36:23.236", "value": 91},
> {"date":"2015-10-01T15:37:29.203", "value": 90},
> {"date":"2015-10-01T15:39:09.187", "value": 89},
> {"date":"2015-10-01T15:43:48.953", "value": 88},
> {"date":"2015-10-01T15:52:16.228", "value": 87},
> {"date":"2015-10-01T16:04:36.714", "value": 86},
> {"date":"2015-10-01T16:07:16.714", "value": 85},
> {"date":"2015-10-01T16:21:49.502", "value": 84},
> {"date":"2015-10-01T16:23:09.503", "value": 83},
> {"date":"2015-10-01T16:25:50.013", "value": 82},
> {"date":"2015-10-01T16:28:19.503", "value": 81},
> {"date":"2015-10-01T16:29:39.503", "value": 80},
> {"date":"2015-10-01T16:31:19.502", "value": 79},
> {"date":"2015-10-01T16:33:59.503", "value": 78},
> {"date":"2015-10-01T16:44:04.079", "value": 75},
> {"date":"2015-10-01T17:01:32.563", "value": 73},
> {"date":"2015-10-01T17:29:25.509", "value": 92},
> {"date":"2015-10-01T17:32:26.379", "value": 93},
> {"date":"2015-10-01T17:36:40.264", "value": 95},
> {"date":"2015-10-01T17:38:31.603", "value": 96},
> {"date":"2015-10-01T17:44:00.276", "value": 97},
> {"date":"2015-10-01T17:49:33.615", "value": 98},
> {"date":"2015-10-01T17:52:58.468", "value": 99},
> {"date":"2015-10-01T18:03:38.310", "value": 98},
> {"date":"2015-10-01T18:10:35.057", "value": 97},
> {"date":"2015-10-01T18:25:25.041", "value": 96},
> {"date":"2015-10-01T18:33:01.039", "value": 95},
> {"date":"2015-10-01T18:42:23.455", "value": 95},
> {"date":"2015-10-01T18:46:52.297", "value": 94},
> {"date":"2015-10-01T19:01:15.506", "value": 93},
> {"date":"2015-10-01T19:01:41.006", "value": 92},
> {"date":"2015-10-01T19:14:47.642", "value": 91},
> {"date":"2015-10-01T19:19:00.428", "value": 90},
> {"date":"2015-10-01T19:36:43.113", "value": 89},
> {"date":"2015-10-01T19:51:34.000", "value": 88},
> {"date":"2015-10-01T20:00:58.974", "value": 87},
> {"date":"2015-10-01T20:11:59.595", "value": 86},
> {"date":"2015-10-01T20:14:02.448", "value": 85},
> {"date":"2015-10-01T20:29:31.247", "value": 83},
> {"date":"2015-10-01T20:31:53.446", "value": 82},
> {"date":"2015-10-01T20:34:43.443", "value": 81},
> {"date":"2015-10-01T20:37:23.445", "value": 80},
> {"date":"2015-10-01T20:38:43.538", "value": 79},
> {"date":"2015-10-01T20:40:40.001", "value": 78},
> {"date":"2015-10-01T20:42:40.559", "value": 77},
> {"date":"2015-10-01T20:47:29.466", "value": 76},
> {"date":"2015-10-01T21:05:48.157", "value": 75},
> {"date":"2015-10-01T21:11:39.270", "value": 74},
> {"date":"2015-10-01T21:23:38.995", "value": 73},
> {"date":"2015-10-01T21:30:11.892", "value": 72},
> {"date":"2015-10-01T21:31:08.672", "value": 72},
> {"date":"2015-10-01T21:32:18.028", "value": 71},
> {"date":"2015-10-01T21:48:15.067", "value": 70},
> {"date":"2015-10-01T22:09:17.118", "value": 68},
> {"date":"2015-10-01T22:14:47.000", "value": 67},
> {"date":"2015-10-01T22:22:34.609", "value": 66},
> {"date":"2015-10-01T22:29:57.019", "value": 65},
> {"date":"2015-10-01T22:34:47.088", "value": 64},
> {"date":"2015-10-01T22:42:20.252", "value": 63}];var states = [{"date":"2015-10-01T03:44:33.390", "value": 0},
> {"date":"2015-10-01T03:44:33.454", "value": 0},
> {"date":"2015-10-01T03:45:04.110", "value": 1},
> {"date":"2015-10-01T03:45:04.219", "value": 1},
> {"date":"2015-10-01T03:45:19.490", "value": 0},
> {"date":"2015-10-01T03:45:19.598", "value": 0},
> {"date":"2015-10-01T04:37:37.047", "value": 1},
> {"date":"2015-10-01T04:37:37.139", "value": 1},
> {"date":"2015-10-01T04:38:09.370", "value": 0},
> {"date":"2015-10-01T04:38:09.493", "value": 0},
> {"date":"2015-10-01T05:45:42.383", "value": 1},
> {"date":"2015-10-01T05:45:51.139", "value": 1},
> {"date":"2015-10-01T05:46:57.150", "value": 1},
> {"date":"2015-10-01T05:46:58.395", "value": 1},
> {"date":"2015-10-01T05:48:29.738", "value": 0},
> {"date":"2015-10-01T05:48:29.938", "value": 0},
> {"date":"2015-10-01T05:48:30.213", "value": 1},
> {"date":"2015-10-01T05:48:30.281", "value": 1},
> {"date":"2015-10-01T05:48:32.866", "value": 0},
> {"date":"2015-10-01T05:48:33.050", "value": 0},
> {"date":"2015-10-01T14:37:17.437", "value": 1},
> {"date":"2015-10-01T14:37:17.522", "value": 1},
> {"date":"2015-10-01T14:44:35.198", "value": 0},
> {"date":"2015-10-01T14:44:35.268", "value": 0},
> {"date":"2015-10-01T15:07:16.353", "value": 0},
> {"date":"2015-10-01T15:07:16.426", "value": 0},
> {"date":"2015-10-01T15:07:27.272", "value": 1},
> {"date":"2015-10-01T15:07:27.439", "value": 1},
> {"date":"2015-10-01T15:08:28.196", "value": 0},
> {"date":"2015-10-01T15:08:28.353", "value": 0},
> {"date":"2015-10-01T15:09:06.493", "value": 1},
> {"date":"2015-10-01T15:09:06.530", "value": 1},
> {"date":"2015-10-01T15:09:38.782", "value": 0},
> {"date":"2015-10-01T15:09:38.826", "value": 0},
> {"date":"2015-10-01T15:14:58.698", "value": 1},
> {"date":"2015-10-01T15:14:58.759", "value": 1},
> {"date":"2015-10-01T15:15:02.902", "value": 0},
> {"date":"2015-10-01T15:15:02.938", "value": 0},
> {"date":"2015-10-01T15:18:59.343", "value": 1},
> {"date":"2015-10-01T15:18:59.425", "value": 1},
> {"date":"2015-10-01T15:20:14.158", "value": 0},
> {"date":"2015-10-01T15:20:14.199", "value": 0},
> {"date":"2015-10-01T15:21:30.454", "value": 1},
> {"date":"2015-10-01T15:21:30.508", "value": 1},
> {"date":"2015-10-01T15:24:33.494", "value": 0},
> {"date":"2015-10-01T15:24:33.564", "value": 0},
> {"date":"2015-10-01T15:27:53.422", "value": 1},
> {"date":"2015-10-01T15:27:53.487", "value": 1},
> {"date":"2015-10-01T15:30:50.998", "value": 0},
> {"date":"2015-10-01T15:30:51.531", "value": 0},
> {"date":"2015-10-01T15:38:02.094", "value": 1},
> {"date":"2015-10-01T15:38:02.199", "value": 1},
> {"date":"2015-10-01T15:40:43.317", "value": 0},
> {"date":"2015-10-01T15:40:43.576", "value": 0},
> {"date":"2015-10-01T16:03:38.986", "value": 1},
> {"date":"2015-10-01T16:03:39.110", "value": 1},
> {"date":"2015-10-01T16:08:42.299", "value": 0},
> {"date":"2015-10-01T16:08:42.355", "value": 0},
> {"date":"2015-10-01T16:21:37.721", "value": 1},
> {"date":"2015-10-01T16:21:37.889", "value": 1},
> {"date":"2015-10-01T16:36:11.427", "value": 0},
> {"date":"2015-10-01T16:36:11.484", "value": 0},
> {"date":"2015-10-01T16:55:23.625", "value": 1},
> {"date":"2015-10-01T16:55:23.956", "value": 1},
> {"date":"2015-10-01T16:55:37.467", "value": 0},
> {"date":"2015-10-01T16:55:37.717", "value": 0},
> {"date":"2015-10-01T17:36:41.749", "value": 1},
> {"date":"2015-10-01T17:36:41.924", "value": 1},
> {"date":"2015-10-01T17:37:42.890", "value": 0},
> {"date":"2015-10-01T17:37:43.127", "value": 0},
> {"date":"2015-10-01T17:55:31.606", "value": 1},
> {"date":"2015-10-01T17:55:31.688", "value": 1},
> {"date":"2015-10-01T17:55:43.160", "value": 0},
> {"date":"2015-10-01T17:55:43.222", "value": 0},
> {"date":"2015-10-01T17:56:05.843", "value": 1},
> {"date":"2015-10-01T17:56:05.950", "value": 1},
> {"date":"2015-10-01T17:58:45.797", "value": 0},
> {"date":"2015-10-01T17:58:45.895", "value": 0},
> {"date":"2015-10-01T18:12:14.240", "value": 1},
> {"date":"2015-10-01T18:12:14.293", "value": 1},
> {"date":"2015-10-01T18:12:30.723", "value": 0},
> {"date":"2015-10-01T18:12:31.373", "value": 0},
> {"date":"2015-10-01T18:46:53.734", "value": 1},
> {"date":"2015-10-01T18:46:53.775", "value": 1},
> {"date":"2015-10-01T18:47:17.327", "value": 0},
> {"date":"2015-10-01T18:47:17.427", "value": 0},
> {"date":"2015-10-01T19:01:15.623", "value": 1},
> {"date":"2015-10-01T19:01:15.735", "value": 1},
> {"date":"2015-10-01T19:02:33.204", "value": 0},
> {"date":"2015-10-01T19:02:33.631", "value": 0},
> {"date":"2015-10-01T20:11:50.114", "value": 1},
> {"date":"2015-10-01T20:11:50.397", "value": 1},
> {"date":"2015-10-01T20:12:06.484", "value": 0},
> {"date":"2015-10-01T20:12:06.698", "value": 0},
> {"date":"2015-10-01T20:14:02.781", "value": 1},
> {"date":"2015-10-01T20:14:02.889", "value": 1},
> {"date":"2015-10-01T20:14:20.791", "value": 0},
> {"date":"2015-10-01T20:14:20.834", "value": 0},
> {"date":"2015-10-01T20:29:31.303", "value": 1},
> {"date":"2015-10-01T20:29:31.389", "value": 1},
> {"date":"2015-10-01T20:29:34.763", "value": 0},
> {"date":"2015-10-01T20:29:34.867", "value": 0},
> {"date":"2015-10-01T20:37:29.113", "value": 1},
> {"date":"2015-10-01T20:37:29.196", "value": 1},
> {"date":"2015-10-01T20:37:50.276", "value": 0},
> {"date":"2015-10-01T20:37:50.451", "value": 0},
> {"date":"2015-10-01T21:29:54.595", "value": 1},
> {"date":"2015-10-01T21:29:54.680", "value": 1},
> {"date":"2015-10-01T21:30:14.033", "value": 0},
> {"date":"2015-10-01T21:30:14.086", "value": 0},
> {"date":"2015-10-01T22:45:40.668", "value": 1},
> {"date":"2015-10-01T22:45:40.827", "value": 1}];
> MG.convert.date(values, 'date', '%Y-%m-%dT%H:%M:%S.%L');MG.convert.date(states, 'date', '%Y-%m-%dT%H:%M:%S.%L');
> MG.data_graphic({
>     data: values,
>     width: 2200,
>     height: 350,
>     target: "#result1",
>     x_accessor: "date",
>     y_accessor: "value",
>     linked: true,
>     linked_format: "%Y-%m-%d-%H-%M-%S",
>     interpolate: "linear"
> });MG.data_graphic({
>     data: states,
>     width: 2200,
>     height: 350,
>     target: "#result2",
>     x_accessor: "date",
>     y_accessor: "value",
>     linked: true,
>     linked_format: "%Y-%m-%d-%H-%M-%S",
>     interpolate: "step-after"
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/metrics-graphics/issues/499#issuecomment-145741315>
> .
>



-- 
Patrick Linskey
202 669 5907
