### ISSUE TITLE
Make charts responsive so that they look good in mobile

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#5]

**Comment by luiscape** [comment]
Hi @almossawi , I am interesting in knowing in what context you are using "responsive". I thought it meant precisely to resize SVGs based on the title of this issue ... or am I getting this wrong?

**Comment by almossawi** [comment]
Hi @luiscape, Oh, layout rather than charts. That's when we started using Bootstrap.

See [full_height and full_width](https://github.com/mozilla/metrics-graphics/wiki/List-of-Options#graphic) if you'd like to make the charts responsive.

**Comment by luiscape** [comment]
@almossawi, thanks! I had missed that parameter. I'll give it a try. :)
