### ISSUE TITLE
Time details in rollover

### ISSUE THREAD

**Issue by roud33** [mozilla/metrics-graphics#502]
Good day !

I'm building a graph from timestamped speed values.
I'm having trouble displaying the whole datetime information incl. seconds in the rollover.
Here's my dataset:
![image](https://cloud.githubusercontent.com/assets/5745386/10274075/d2c302d6-6b39-11e5-90f2-4d3a4bcf35e6.png)
Here's the graph - in the red zone, I have month, year, hour, minute information, but I would like to add seconds & if possible milliseconds.
![image](https://cloud.githubusercontent.com/assets/5745386/10274087/f43e6fb8-6b39-11e5-90a9-34c909029693.png)
And the code : 

                        speed.push({
                            date: new Date(parseDate(data[i][csvIdent.clock])),
                            value: parseFloat(data[i][csvIdent.speed])
                        });
                    MG.data_graphic({

                        data: speed,
                        linked_format:"%Y",
                        width: 1000,
                        height: 500,
                        baselines: [{
                            value: 1,
                            label: 'acc_ref'
                        }],
                        target: '#speed', // the html element that the graphic is inserted in
                        x_accessor: "date", // the key that accesses the x value
                        y_accessor: 'value', // the key that accesses the y value

                    })

thanks a lot !

**Comment by almossawi** [comment]
Hi there,

You'll want to specify a custom [mouseover](https://github.com/mozilla/metrics-graphics/wiki/Graphic#mouseover) function:

```javascript
var data = [
  {
    "date": "2015/09/15T02:23:14:033Z",
    "value": -0.03
  },
  {
    "date": "2015/09/15T02:23:14:044Z",
    "value": 0.13
  }
];
MG.convert.date(data, 'date', '%Y/%m/%dT%H:%M:%S:%LZ');

MG.data_graphic({
    data: data,
    target: ".result",
    x_accessor: "date",
    y_accessor: "value",
    mouseover: function(d, i) {
        var format = d3.time.format("%b %d, %Y %H:%M:%S %L");
        d3.select('.result svg .mg-active-datapoint')
            .text(format(d.date));
    }
});
```

![2015-10-05](https://cloud.githubusercontent.com/assets/980049/10291380/55bb3b62-6b5e-11e5-9334-46ba6785aed6.gif)

**Comment by roud33** [comment]
Thanks a lot for your help Almossawi !

But for some reasons the mouseover still doesn't work.
Here's my complete html code : 

For a "svg id='test' height="500" width="1000""

<head>

    <script src='d3.min.js' charset='utf-8'></script>
    <script src='metricsgraphics.min.js'></script>
    <link href='metricsgraphics.css' rel='stylesheet' type='text/css'>

    <script>
        var data = [{
            "date": "2015/09/15T02:23:14:033Z",
            "value": -0.03
        }, {
            "date": "2015/09/15T02:23:14:044Z",
            "value": 0.13
        }];

        MG.convert.date(data, 'date', '%Y/%m/%dT%H:%M:%S:%LZ');

        MG.data_graphic({
            data: data,
            target: "#test",
            x_accessor: "date",
            y_accessor: "value",
            mouseover: function(d, i) {
                var format = d3.time.format("%b %d, %Y %H:%M:%S %L");
                d3.select('.result svg .mg-active-datapoint')
                    .text(format(d.date));
            }
        });
    </script>
</head>

And here's what I get :
![image](https://cloud.githubusercontent.com/assets/5745386/10307407/038b149e-6c2f-11e5-980f-6c45873f9cea.png)

I don't get it. Whatever I put in the mouseover field, it doesn't work

**Comment by almossawi** [comment]
On line 18, change ``.result`` to the class name or ID of your target element, which in your case is ``#test``:

```javascript
var data = [{
        "date": "2015/09/15T02:23:14:033Z",
        "value": -0.03
    }, {
        "date": "2015/09/15T02:23:14:044Z",
        "value": 0.13
    }];

    MG.convert.date(data, 'date', '%Y/%m/%dT%H:%M:%S:%LZ');

    MG.data_graphic({
        data: data,
        target: "#test",
        x_accessor: "date",
        y_accessor: "value",
        mouseover: function(d, i) {
            var format = d3.time.format("%b %d, %Y %H:%M:%S %L");
            d3.select('#test svg .mg-active-datapoint')
                .text(format(d.date));
        }
    });
```

![2015-10-06](https://cloud.githubusercontent.com/assets/980049/10314708/2adb8548-6c0b-11e5-9394-22289b19f5e7.gif)

**Comment by roud33** [comment]
oopsss ! That works ! Thanks a lot !!!!!!!!!!
