### ISSUE TITLE
allow specification of line color in MG.data_graphic

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#503]
There are often cases where relying on CSS to determine line colors is not flexible enough. Being able to pass in an array of colors would be a useful option.

**Comment by hamilton** [comment]
@almossawi Would love to get another set of eyes on this commit.

The change is:

1.) we add new classes to line elements + rollovers so we are not selecting based on -color, but more generic classes.
2.) added new keyword argument(s) ``color`` and ``colors``, which do the same thing. If you have a single line, you can specify a string that is a hex / rgb / web color, and if you have a multiline, you can specify an array of colors.

This required a pretty major refactoring of how we select elements in the rollovers for line charts, but I think it is worth it since it a. removes the conflation of color and rollover selections, class-wise and b. opens up coloring lines in the API itself, not just in CSS. I've pretty thoroughly tested it across voronoi, linked charts, single line charts, and aggregate rollovers, but have not against the custom_color_map logic, since I am less familiar with it. Added examples as well.

At any rate, take a look and see what you think. Trying to curtail my agent-of-chaos status on this lib, but couldn't resist this change.

**Comment by almossawi** [comment]
@hamilton Wonderful. It looks great :+1:
