### ISSUE TITLE
Make title a text element in the SVG

### ISSUE THREAD

**Issue by amlwwalker** [mozilla/metrics-graphics#504]
Its a bit annoying that the title of the chart is an h2 element above the chart. If you look at libraries like http://maurizzzio.github.io/function-plot/ the title is part of the SVG. This means that if you copy the SVG contents (or in my case create a "Download SVG" button) you get the title with it.

In my opinion it would be better anyway if the title was part of the SVG.

**Comment by hamilton** [comment]
Sorry that you find this annoying. We have on our roadmap a plan to convert the title to SVG.

**Comment by almossawi** [comment]
I've made a start on this. The title is now part of the SVG container, and the popover works as before. This also resolves the issue with titles sometimes appearing horizontally misaligned due to a large left margin.

**Comment by almossawi** [comment]
All done. @hamilton Let me know if you notice any issues. I also changed the y-position of ``mg-active-datapoint`` so that it's always slightly above the plot area rather than midway between the top edge and the plot area.

**Comment by amlwwalker** [comment]
nice guys!
