### ISSUE TITLE
Dates + histogram chart type: x axis is rendered numerically instead of with dates

### ISSUE THREAD

**Issue by pcl** [mozilla/metrics-graphics#505]
For example, if I add `chart_type: "histogram"` to the interactive demo, I get the attached.

I haven't tried pre-bucketing yet. I'm assuming that if I pre-bucketed and provided the bucket names as strings instead of dates, things would work.
![screen shot 2015-10-11 at 8 33 13 pm](https://cloud.githubusercontent.com/assets/33086/10420095/83968250-7057-11e5-8710-daf3fbda7b63.png)

**Comment by hamilton** [comment]
Hi - thanks for the comment. Our histogram type is in need of serious work to smooth out the functionality, design, and API. We will likely be improving how it works in the coming couple of months. Sorry for the inconvenience.
