### ISSUE TITLE
Date ranges longer than a few years should require some special formatting

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#510]
@almossawi While messing around with evictions data, I noticed that our graphs have some unintended side effects of using year labels in our way.

<img width="654" alt="screen shot 2015-10-15 at 5 25 40 pm" src="https://cloud.githubusercontent.com/assets/95735/10531026/e309062e-7361-11e5-8592-348e367d40d1.png">

I propose we have either automatic formatting for historical data, or something to make this a little more elegant.

**Comment by almossawi** [comment]
Ah, yes, absolutely.

**Comment by hamilton** [comment]
Doing some cleaning up of issues. This was fixed a couple of versions back.
