### ISSUE TITLE
changing mg-line-color* also colors the underlying voronoi shapes

### ISSUE THREAD

**Issue by garygreen** [mozilla/metrics-graphics#514]
I know this is a WIP related to #503 with the [`colors`](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/data_graphic.js#L89) option -- has any progress been made on this? I have a requirement where I need to change the color of certain lines (which I don't think is currently possible?)

I've tried setting the line colors by css like `.mg-line-color1 { stroke: black; }` etc but for some reason I get weird lines all over the place?

![stats](https://cloud.githubusercontent.com/assets/1702638/10634387/5c9bb578-77e9-11e5-91b6-4d2b6417f556.PNG)

**Comment by hamilton** [comment]
Oh, nice. You're doing it absolutely right. But my changes seem to clolor the voronoi shapes that determine the rollovers. So this is a bug. The colors option is available now with #503, but not in the latest release.

**Comment by hamilton** [comment]
I'm having a bit of trouble replicating your bug in the most recent version of the library - could you provide your code that produces the weird line additions?

**Comment by garygreen** [comment]
```
console.log(MG.version) // 2.6.0
```

**Comment by garygreen** [comment]
Ah it appears fixed in master. So when's the new version 2.7.0 land? :smile:

**Comment by hamilton** [comment]
Cool - I suspected this actually had gotten fixed with #503, glad to see it did :) 

2.7 hits week, most likely.
