### ISSUE TITLE
Bottom: 0 doesn't really result in no bottom margin

### ISSUE THREAD

**Issue by neverfox** [mozilla/metrics-graphics#516]
If you set bottom to 0 and turn off the x-axis, I would expect the area under the chart to sit right that the bottom edge of the SVG. That doesn't appear to be the case however.

**Comment by almossawi** [comment]
You'll want to adjust both _bottom_ and [buffer](https://github.com/mozilla/metrics-graphics/wiki/Layout#buffer).

**Comment by neverfox** [comment]
Got it. While I'm on the subject, is there any way to control the gap between the tooltip text and the highest value on the chart. I'm working with a very constrained height (sparkline-type application) but would like the values to show on rollover. However, there's so much gap what the line is compressed far too much.

**Comment by almossawi** [comment]
Yes, it might not look too good in 2.6 since the rollover area is positioned half-way between the top edge and the plot area. It works much better in master, as the rollover area is positioned slightly above the plot area--2.7 is planned for release next week:

![no-margins](https://cloud.githubusercontent.com/assets/980049/10655213/76135090-7827-11e5-92ad-1033d4b69c23.gif)


```javascript
MG.data_graphic({
  data: JSON.parse($('.data textarea').val()),
  width: 200,
  height: 120,
  x_axis: false,
  y_axis: false,
  bottom: 0,
  top: 10,
  left: 0,
  right: 0,
  buffer: 0,
  target: ".result",
  x_accessor: "year",
  y_accessor: "sightings"
});
```

**Comment by neverfox** [comment]
That's very helpful. I've got it looking good now with master. Now I just need to figure out why `full_width` isn't working. It's tricky to get a determinant div size inside of a table. I can get it on iniitalization, but not on resize.

**Comment by neverfox** [comment]
Actually, the width is adjusting, but what you would call the buffer seems to grow as the graph shrinks is width.

**Comment by almossawi** [comment]
You're welcome to submit a PR.  [This](https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/window_listeners.js) is how it's currently done.

**Comment by neverfox** [comment]
Thanks. I just wanted to make sure there wasn't something already to change the behavior before I went down that route.
