### ISSUE TITLE
Box-and-whisker plot (Tukey)

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#518]
# User story

```
As a researcher
I would like to plot my data in a box-and-whisker plot
so that I can quickly see the overall shape of a data set
```
# Feature

> A [box plot](https://en.wikipedia.org/wiki/Box_plot) is a convenient way of graphically depicting groups of numerical data through their quartiles.

![Box-and-whisker plot](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Michelsonmorley-boxplot.svg/500px-Michelsonmorley-boxplot.svg.png)
# Components

Box plots, generally, have the following components:
- X/Y axis labels
- X/Y [scale](https://github.com/mbostock/d3/wiki/Quantitative-Scales) bars
- One or more categories of measurement
- Box (i.e. bar) for each category
  - Showing [inter-quartile range](https://en.wikipedia.org/wiki/Interquartile_range)
  - Line for [median](https://en.wikipedia.org/wiki/Median)
- Whiskers
  - Line (sometimes dotted or dashed) indicating distance to marker
  - End marker (or cross-hatch) indicating, for example:
    - percentiles (e.g. 9th and 91st percentiles)
    - minimum/maximum
    - +/- 1 Standard Deviation around mean
- Markers
  - Showing [outlying data points](https://en.wikipedia.org/wiki/Outlier) (outside of whisker range)
- (optional) Indicator line, e.g. showing data mean, target value, annotation, etc.
- (optional) top and right containing lines around chart area
# Examples
- mbostock [box plot](http://bl.ocks.org/mbostock/4061502)
- jensgrubert [D3.js Boxplot with Axes and Labels](http://bl.ocks.org/jensgrubert/7789216)
- Plot.ly [box plots](https://plot.ly/javascript/box-plots/)

**Comment by hamilton** [comment]
Yes indeed - would be very useful to have & we plan to implement boxplots once we feel comfortable with the workload on our plates.

**Comment by brylie** [comment]
All good. Just putting the idea in the backlog for planning, documentation, etc.

**Comment by brylie** [comment]
Plot.ly has a very flexible box plot API, which MG can use as reference. However, Plot.ly seems to require axis data to be mapped to arrays, which is less simple and elegant than how Metrics Graphics handles axis data.

@hamilton what are your thoughts on the Plot.ly box plot API?

**Comment by brylie** [comment]
I notice that Plot.ly allows you to declare chart axes *either* by providing an array (e.g. [box: x](https://plot.ly/javascript/reference/#box-x)) of data or by a "number or categorical coordinate string" (e.g. [box: x0](https://plot.ly/javascript/reference/#box-x0)).

**Comment by hamilton** [comment]
(2 years later) upon thinking about it, I feel that box plots are out of scope for MG at this time. We're focusing on having very strongly opinionated / fully-featured plot types, and I can't see how we can prioritize this for our target audience.
