### ISSUE TITLE
Ability to clear mg_window_listeners

### ISSUE THREAD

**Issue by dareid** [mozilla/metrics-graphics#544]
If full_width or full_height = TRUE, a 'resize' event listener is registered on the window for the graph. This event listener cannot be removed when the graph is removed from the DOM. This leads to the following errors:

```
Uncaught TypeError: Cannot read property 'getAttribute' of null
   d3_selectionPrototype.attr @ d3.js:632
   (anonymous function) @ metricsgraphics.js:2180
```
It should be possible to deregister window listeners on graph destruction.

**Comment by brab** [comment]
+1
