### ISSUE TITLE
filled area in dark theme from first to last datapoint

### ISSUE THREAD

**Issue by NSchnitzler** [mozilla/metrics-graphics#549]
activating the dark theme causes a filled area in dark theme from first to last datapoint
<img width="1019" alt="metrics" src="https://cloud.githubusercontent.com/assets/6046936/11195598/f501e656-8cb2-11e5-98c8-40b67f40b3d0.png">

**Comment by almossawi** [comment]
Are you also including the default stylesheet, as in the examples?

**Comment by NSchnitzler** [comment]
oh no, i replaced the default stylesheet by the dark one, with the dark one as addition it is working!

thank you!

**Comment by almossawi** [comment]
Glad to hear it.
