### ISSUE TITLE
Download as PNG

### ISSUE THREAD

**Issue by amlwwalker** [mozilla/metrics-graphics#550]
I am trying to download the SVG as a PNG. 
I am having a problem downloading the SVG properly - here is what the SVG looks like:

![image](https://cloud.githubusercontent.com/assets/2920180/11254714/2c316bc8-8e3a-11e5-8dca-be080f5807b9.png)

Here is what the PNG looks like:

![image](https://cloud.githubusercontent.com/assets/2920180/11254723/3343ade0-8e3a-11e5-8a56-22afc365ada1.png)

The problem as I understand it is that the design on the plot is being set in CSS. If it was set in javascript it would come through in the PNG.

I don't expect a library re write, I was just wondering if any one has any suggestions as to how to fix this. The code I am using is this:

```
d3.select("#save_as_png").on("click", function(){
  var html = d3.select("svg")
        .attr("version", 1.1)
        .attr("xmlns", "http://www.w3.org/2000/svg")
        .node().parentNode.innerHTML;
  var width = d3.select("svg").attr("width")
  var height = d3.select("svg").attr("height")
  var imgsrc = 'data:image/svg+xml;base64,'+ btoa(unescape(encodeURIComponent(html)));  
  saveSVG(imgsrc, width, height);

});

function saveSVG(imgsrc, width, height) {
    
    var inputValue = "filename" 
      if (!inputValue) {
        return false
      }
      var canvas = document.createElement("canvas");
        canvas.width = width;
        canvas.height = height;
        context = canvas.getContext("2d");

        var image = new Image;
        image.src = imgsrc;
        console.log(image.src);
        image.onload = function() {
          context.drawImage(image, 0, 0);

          var canvasdata = canvas.toDataURL("image/png");

          var pngimg = '<img src="'+canvasdata+'">'; 
            d3.select("#pngdataurl").html(pngimg);

          var a = document.createElement("a");
          a.download = inputValue+".png";
          a.href = canvasdata;
          a.click();
        };
}
```

It just needs a button added to the page with an ID of `save_as_png`. 

Would really some help with this, but I understand its not an issue per se with the library.
Thanks

FYI the project I am working on is here:
https://github.com/amlwwalker/d3-graphing/tree/refactor (refactor branch)

**Comment by almossawi** [comment]
Yes, you would need to either inline the styles or add them inside a _styles_ tag within your SVG container's _defs_ tag. [This function](https://github.com/exupero/saveSvgAsPng/blob/gh-pages/saveSvgAsPng.js#L51) ought to be helpful.

<img width="857" alt="screen shot 2015-11-19 at 9 40 03 am" src="https://cloud.githubusercontent.com/assets/980049/11278779/c920c610-8ea1-11e5-8009-0d8c4e521de2.png">

**Comment by hamilton** [comment]
Is there anything to do on this front? Anything we need to be aware of?
