### ISSUE TITLE
IE 11 gives method 'map' not found

### ISSUE THREAD

**Issue by ThiloL** [mozilla/metrics-graphics#557]
with version 2.7.0

**Comment by hamilton** [comment]
Thanks for the issue. Could you give more context? Perhaps an example or line number where this error occurs? Unfortunately We don't have a whole lot of developer support and I don't actually have a windows box to test on IE 11.

**Comment by ThiloL** [comment]
![mg1](https://cloud.githubusercontent.com/assets/2923889/11529277/4411cb4a-98ec-11e5-86dc-73498ee8d968.JPG)

**Comment by ThiloL** [comment]
json data looks like this: [{\"StatDate\":\"2015-09-24T00:00:00\",\"StatValue\":408},{\"StatDate\":\"2015-09-25T00:00:00\",\"StatValue\":408},{\"StatDate\":\"2015-09-26T00:00:00\",

**Comment by hamilton** [comment]
Ok - could you verify that ``data`` (what you're passing in) is an array of objects, and what your ``time_format`` is? If you haven't specified, you'll have to set ``time_format`` as per d3's [time formatting options](https://github.com/mbostock/d3/wiki/Time-Formatting).

**Comment by ThiloL** [comment]
I used this code from the examples. Where should I specify time_format?

d3.json('data/fake_users1.json', function(data) {
    data = MG.convert.date(data, 'date');
    MG.data_graphic({
        title: "Line Chart",
        description: "This is a simple line chart. You can remove the area portion by adding area: false to the arguments list.",
        data: data,
        width: 600,
        height: 200,
        right: 40,
        target: document.getElementById('fake_users1'),
        x_accessor: 'date',
        y_accessor: 'value'
    });
});

**Comment by almossawi** [comment]
You'll want to pass in the time format to MG.convert.date, like so

```javascript
MG.convert.date(data, 'date', '%Y-%m-%dT%H:%M:%S');
```

The time format you pass in depends on your data, of course (e.g. the format [here](https://github.com/mozilla/metrics-graphics/issues/502#issuecomment-146448800) is slightly different). More info is available in [the wiki](https://github.com/mozilla/metrics-graphics/wiki/Convenience-Functions).

**Comment by hamilton** [comment]
Hey @ThiloL - did this answer your question?

**Comment by ThiloL** [comment]
I changed the date format in my JSON, so I could use the original script.
Thanks!
