### ISSUE TITLE
I beleive src/index.html should be removed

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/metrics-graphics#558]
I can not get to to render properly, and maybe it is just old

**Comment by almossawi** [comment]
Ah, yes. The page is a replicate of examples/index.htm, but has live-reloading to make development a bit easier. You run it with ``gulp serve``.

**Comment by hamilton** [comment]
@almossawi should this be removed? I don't personally use it.

**Comment by almossawi** [comment]
It's useful when you want to retain a dataset while making changes to the code, without having to worry about losing anything if the page gets inadvertently refreshed.

jshint reported several errors that I've gone ahead and fixed, as well as inconsistencies in tab spaces in a a few files--this is by no means a comprehensive cleanup; we'll want to make sure to do that before any upcoming release.
