### ISSUE TITLE
Possible cyclic attribute causing build to fail

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#559]
Tests that invoke MG.clone are failing with a 'maximum call stack size exceeded' error in phantomjs, possibly due to the ``args`` object having a cyclic attribute somewhere. My guess is probably due to a recent change.

**Comment by hamilton** [comment]
I don't think it is cyclic - otherwise it would also throw for Chrome. I think phantomjs's call stack is very, very small. Going to have to debug it tomorrow though. Likely due to decomposing line.js, which had quite a bit of complicated nested code.

**Comment by hamilton** [comment]
(unless, of course, chrome ignores that)
