### ISSUE TITLE
have solution for overlapping dates on x-axis

### ISSUE THREAD

**Issue by hamilton** [mozilla/metrics-graphics#561]
We have this problem from time to time, where certain tick counts (generated by d3) are simply too many to fit without overlaps. One temporary hack is to remove half the x-axis labels upon drawing if they overlap.

**Comment by devmi** [comment]
On a smaller width, it's still possible to overlap dates on x-axis on **v2.11**.
<img width="381" alt="mg-issue-561" src="https://user-images.githubusercontent.com/19313261/27504380-4b6c99ee-583d-11e7-88db-95d5401d77be.png">


To reproduce it, please copy the [auto time formatting > Over A Large Span of Days](https://www.metricsgraphicsjs.org/examples.htm#auto-time-formatting) sample code to the [interactive demo](https://www.metricsgraphicsjs.org/interactive-demo.htm) demo, adjusting some values as shown below:

```javascript
function fake_days(length) {  //no changes
    var d = new Date();
    var v = 100000;

    var data = [];
    for (var i = 0; i < length; i++) {
        v += (Math.random() - 0.5) * 10000;
        if (v < 0) v = 0;
        data.push({date: MG.clone(d), value: v});
        d.setDate(d.getDate() + 1);
    }
    return data;
}
var many_days = fake_days(80);  //also reproducible w/other values, like 23, 81,82...

MG.data_graphic({
    title: "Over A Large Span of Days",
    data: many_days,
    target: ".result",  //'#time4',
    width: 400,   //600,
    height: 200,
    right: 40
});
```
 
Shall I create a new issue?
