### ISSUE TITLE
Multi line chart from object attributes within array?

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#566]
Is it possible to make a [multi-line chart](http://metricsgraphicsjs.org/examples.htm#multilines) when data is structured in the following manner?

```js
[ 
  { date: Thu Dec 17 2015 02:19:29 GMT+0200 (EET),
     inactive: 1,
    semiActive: 2,
     active: 0 },
   { date: Wed Dec 16 2015 02:19:29 GMT+0200 (EET),
     inactive: 1,
     semiActive: 2,
     active: 0 },
   { date: Tue Dec 15 2015 02:19:29 GMT+0200 (EET),
     inactive: 1,
     semiActive: 2,
     active: 0 }
]
```

E.g. I want to produce a colored line for each activity level `inactive`, `semiActive`, `active`. This would be similar to how stacked bar charts are produced.

**Comment by hamilton** [comment]
If I understand the need correctly, you can pass into ``y_accessor`` an array of strings, each one an accessor. So, for instance, ``['inactive', 'semiActive', 'active']``. This is another method to automatically create a multi-line chart.

**Comment by brylie** [comment]
Brilliant! Thank you for your timely response @hamilton. I am still learning the nuances of MetricsGraphics.

**Comment by hamilton** [comment]
Well, this is clearly a problem with our current documentation / examples if it was not obvious :)
