### ISSUE TITLE
Dates misaligned with data points on multi-line chart

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#567]
When creating a multi-line chart, the data points are misaligned from the x-axis:

![screenshot](https://cloud.githubusercontent.com/assets/17307/11873403/11135e68-a4e3-11e5-9372-076383ee0462.png)

How can I troubleshoot this misalignment?

**Comment by hamilton** [comment]
It is very possible that your ``Date`` object has a clock associated with it (hours and minutes). The time scale is not discrete on dates, but continuous on the unix timestamp itself. If you subtract whatever hours and minutes are in your datetime object, then I think it should work as expected.

**Comment by brylie** [comment]
Ah, that is it I reckon. We are capturing times in UTC+2, so I will have to figure out how to remove the time offset.

**Comment by brylie** [comment]
It was a bit confusing since both the axis and hover text were only displaying the date.
