### ISSUE TITLE
`interpolate` does not work when `missing_is_hidden` is set to true

### ISSUE THREAD

**Issue by j6k4m8** [mozilla/metrics-graphics#572]
I think the title says it all — here's a sample so others can reproduce:

```javascript
{
    area: true,
    data: [
        {'date':new Date('2014-11-01'),'value':12},
        {'date':new Date('2014-12-01'),'value':14},
        {'date':new Date('2014-13-01'),'value':10},
    ],
    missing_is_hidden: true,
    right: 5,
    left: 30,
    height: 300,
    target: '#plot-target',
    x_accessor: 'date',
    y_accessor: 'value',
    interpolate: "monotone"
}
```

Comment out the `missing_is_hidden` line to resolve.

I think this may be expected behavior, but the [documentation](https://github.com/mozilla/metrics-graphics/wiki/Graphic#interpolate) leaves this unclear.

**[EDIT]** Just realized this is mentioned briefly [here](https://github.com/mozilla/metrics-graphics/blob/fd5d6b7e07bd3cc0a42193e3dc84cb2361d1aab4/examples/charts/data.htm#L16). Now that I'm reading it, it's an intuitive reason. But this is definitely not obvious to a new user!

**Comment by j6k4m8** [comment]
Added an explanation to the docs [here](https://github.com/mozilla/metrics-graphics/wiki/Graphic/d50842ed6c0db33d38b93a8c5ce21bd697743fcc). This can probably be closed?

**Comment by almossawi** [comment]
Great, thank you.
