### ISSUE TITLE
Reduce space between title and Graph

### ISSUE THREAD

**Issue by NSchnitzler** [mozilla/metrics-graphics#574]
Is it possible to reduce the space between the title an the plot are? In my case it's a waste of space.

![mg](https://cloud.githubusercontent.com/assets/6046936/12074255/dae6612e-b148-11e5-862b-caf734e539c9.jpg)

**Comment by almossawi** [comment]
Yes, you'll want to modify [top](https://github.com/mozilla/metrics-graphics/wiki/Layout#top).

**Comment by NSchnitzler** [comment]
ok, that was easy! 
Thank you
