### ISSUE TITLE
enable negative values in bar chart

### ISSUE THREAD

**Issue by fedorocko** [mozilla/metrics-graphics#576]
Bar chart does not support negative values on y axis (vertical chart) leaving 'Error: Invalid negative value for <rect> attribute width="-100"'.

**Comment by hamilton** [comment]
Thanks for the issue. This will be solved in 2.9. #580 will be the meta bug to track the progress on our bar chart improvements, and I'll use this issue to be the one where we track the progress on the negative value part.

**Comment by hamilton** [comment]
The last commit should have fixed this issue
