### ISSUE TITLE
Percentage values have classic floating point formatting error

### ISSUE THREAD

**Issue by thegrandpoobah** [mozilla/metrics-graphics#578]
I've created a line graph with two data series that are formatted as percentages, and I am running into the classic ".00000000001%" floating point number formatting issue.

Screenshot:

<img width="933" alt="whoops" src="https://cloud.githubusercontent.com/assets/278023/12135014/f2f19c94-b403-11e5-80e4-7907f293f12a.png">

Data Series (gist): https://gist.github.com/thegrandpoobah/4352e77acecb644d2d57

Code: 

```js
  MG.data_graphic({
    title: dataSeries[0].name + ' vs ' + dataSeries[1].name,
    data: _.pluck(dataSeries, 'prices'),
    colors: ['blue', 'red'],
    full_width: true,
    height: 400,
    target: chartTarget,
    x_accessor: 'end',
    y_accessor: 'index',
    min_y_from_data: true,
    legend: _.pluck(dataSeries, 'name'),
    legend_target: legendTarget,
    aggregate_rollover: true,
    format: 'percentage',
    baselines: [{value: 1, label: '100%'}]
  }) 
```
MetricsGraphics Version: 2.7.0
D3 Version: 3.5.12

Tried this on Firefox and Microsoft Edge.

**Comment by hamilton** [comment]
I'm sorry to say this is a common thing we've encountered with d3.js, which is how we are formatting our axis text.

**Comment by thegrandpoobah** [comment]
Do you know if there is an open issue in D3's tracker regarding this? It would seem like quite a fundamental problem in their formatting code.

**Comment by hamilton** [comment]
It's not a problem with d3, but a problem with javascript / IEEE and floating points. IIRC, to take a simple issue, consider that in javascript ``1/10 + 2/10 !== 3/10`` (try it yourself and see). This all said, there is surely a guard against this that we can implement, and perhaps d3 has figured out how to correct for this since the last time I looked (which was admittedly a while back). So we'll look into it and use this issue to track the change.

Thanks :+1:

**Comment by thegrandpoobah** [comment]
I understand the floating point problem, but d3 specifically advertises "format" as guarding against this kind of problem: https://github.com/mbostock/d3/wiki/Formatting (its the first line!). And as far as I can see by browsing the code, MG uses d3.format for rendering this text, which is why it was surprising to me.

Anyways, thanks for looking into it!

**Comment by hamilton** [comment]
Agreed, it is surprising. this issue https://github.com/mbostock/d3/issues/210 even suggests at one point a pull request was potentially offered there (there is no case in which the floating point error should exist or make sense in the display of numbers to humans).
