### ISSUE TITLE
Add hook on line chart destruction.

### ISSUE THREAD

**Issue by blazkovicz** [mozilla/metrics-graphics#586]
MG has hook 'line.after_init' but does not have 'line.before_destroy', so there is no clear way to remove events, added to svg on chart initialization. I suspect that several calls of MG.data_graphic on same dom node will result in memory leaking.

**Comment by hamilton** [comment]
Good call. @almossawi has had some practical experience with fixing memory leaks on the DOM w/ this lib. Would be good to get his thoughts here.
