### ISSUE TITLE
Error parsing data with "%Y-%m-%d %H:%M:S" format

### ISSUE THREAD

**Issue by NSchnitzler** [mozilla/metrics-graphics#588]
My data looks like:
`[{"zeit":"2016-01-10 01:00:00","qm":0},{"zeit":"2016-01-10 11:00:00","qm":1.42},{"zeit":"2016-01-10 12:00:00","qm":0.9}]`
parsing with:
    `data = MG.convert.date(data, 'zeit', "%Y-%m-%d %H:%M:S");`
or     `data = MG.convert.date(data, 'zeit');`

![metric](https://cloud.githubusercontent.com/assets/6046936/12221416/14e3bfa0-b79a-11e5-9da6-041c036196e6.jpg)

**Comment by hamilton** [comment]
You have an error in your format string - only ``S`` in your example, not ``%S``.
