### ISSUE TITLE
bottom and position of x_label

### ISSUE THREAD

**Issue by blazkovicz** [mozilla/metrics-graphics#589]
It's about strange relationship between option bottom and position of x_label (main label for axis): with default bottom x_label is placed right over x-axis labels, with bottom: 60 it's placed under labels (desired behaviour) but too much space remains under graphics. Now I have to set `bottom: 40` and every time manually set attribute `dy=1rem` for `.mg-x-axis .label` after calling `MG.data_graphic` to solve the problem.

![1](https://cloud.githubusercontent.com/assets/4517837/12229279/ed09fde0-b867-11e5-866e-dbccc50e11b7.png)

**Comment by hamilton** [comment]
Agreed - this is long-overdue for rethinking, and should be a simple fix. The title should consistently sit below the axis.

**Comment by hamilton** [comment]
In hindsight, the previous commit should have taken care of this.
