### ISSUE TITLE
Function Accessors

### ISSUE THREAD

**Issue by j6k4m8** [mozilla/metrics-graphics#592]
I'd love to be able to pass a function instead of a string to the accessor options:

```
x_accessor: function(d) { return Date.parse(d.date) }
```

Does this exist, or is there a reason it doesn't? Seems like a very good feature to offer.

**Comment by j6k4m8** [comment]
If someone gives the go-ahead, I'd be happy to see if I could tackle this...

**Comment by hamilton** [comment]
(I recognize this issue was filed forever ago @j6k4m8)

I am a bit averse to conflating both the formatting of the data (which should be in general done outside of a call to ``MG.data_graphic``) and the accessing of it. Ideally this type of parsing should be done prior to the call to MG.

**Comment by j6k4m8** [comment]
That's fair! Glad to hear the rationale. In retrospect, better to keep MG clean and do this elsewhere — but may be good food for thought for later :)
