### ISSUE TITLE
Not all charts are resized when full_width = true is set for multiple charts

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#604]
Introduced in 2.8, most probably.

**Comment by hamilton** [comment]
@almossawi I'm having trouble reproducing this issue in the latest version

**Comment by almossawi** [comment]
@hamilton For instance, [here](https://github.com/mozilla/firefox-code-quality). I'm about to merge #607, which will fix this.

**Comment by hamilton** [comment]
:+1: thanks
