### ISSUE TITLE
Single line chart rollover does not display value when aggregate_rollover: true 

### ISSUE THREAD

**Issue by Benco1** [mozilla/metrics-graphics#610]
With charts that switch between multi- and single-line format due to dynamic data I noticed that aggregate_rollover == true prevents the data value from being displayed in the rollover legend if chart is single-line. This is easy to correct by detecting the number of unique keys being passed to the chart, but this seems like a case MG should be able to handle on it's own.

**Comment by jieter** [comment]
Just experienced this too. I fixed it by expecting an array when `this.aggregate_rollover && 'values' in d` in my `mouseover` callback.

Would be nice if this was more consistent, I'd at least always expect an array if `this.aggregate_rollover == true`

**Comment by hamilton** [comment]
Thanks for the bug @Benco1 & @jieter. Fixed.

![aggregate rollover fix](https://zippy.gfycat.com/ConsciousGreedyArmadillo.gif)
