### ISSUE TITLE
Missing rollover label in non-bar charts

### ISSUE THREAD

**Issue by Mark-Wood** [mozilla/metrics-graphics#612]
All rollovers for non-bar charts with a label defined (either through a legend or the property identified by the label_accessor argument) do not include the label.

This behaviour is inconsistent with the bar chart, which uses the group_accessor to display similar information.

The erroneous code can be found in mg_update_rollover_text:
`if (!args.chart_type === 'bar' && (args.legend || args.label_accessor))`

**Comment by hamilton** [comment]
Believe this was resolved via #614, so going to close this issue
