### ISSUE TITLE
Automatic time formatting not working on rollovers

### ISSUE THREAD

**Issue by GeorgeDewar** [mozilla/metrics-graphics#621]
The automatic time formatting doesn't seem to work for rollovers. Oddly, it seems to work OK in the interactive demo (but not with the code in master).

![aggregate-rollover](https://cloud.githubusercontent.com/assets/5344417/13307079/b4db6bbe-dbcd-11e5-988f-33d9aac7c0ab.png)

The problem appears to be in the *mg_format_data_for_mouseover* function, which formats the time with `MG.time_format(args.utc_time, '%b %e, %Y')`.

My current workaround / fix is to change this to `mg_get_rollover_time_format(args)`, which gives behaviour consistent with the non-aggregated rollover.

Example case:

```
function fake_data(length, seconds) {
    var d = new Date();
    var v = 100000;
    var data=[];

    for (var i = 0; i < length; i++) {
        v += (Math.random() - 0.5) * 10000;
        data.push({date: MG.clone(d), value: v});
        d = new Date(d.getTime() + seconds * 1000);
    }
    return data;
}

var less_than_a_minute = fake_data(25, 1);

MG.data_graphic({
    title: "Less Than A Minute",
    data: less_than_a_minute,
    target: '.result',
    width: 600,
    height: 200,
    right: 40
});
```

**Comment by SinanGabel** [comment]
Hi!

I have noticed that if the x-axis is showing HH:MM (hours:minutes) then the roll-over will too, and if the x-axis does not show HH:MM then the roll-over will not either. I personally need the roll-over to show the HH:MM no matter what the x-axis shows.

PS Cannot say if the above observation is always the case.

Thanks!

Best,
Sinan

**Comment by jasonish** [comment]
This might be a regression I'm seeing from 2.8 to 2.9.  With 2.8, in sub 1-hour charts I'll see the minute data.  In 2.9, I only see the date, no time info.

**Comment by almossawi** [comment]
@jasonish Indeed.

**Comment by almossawi** [comment]
This was, perhaps, erroneously rolled back in? Fixing.
