### ISSUE TITLE
Unnecessary removing and adding of mg-active-datapoint-container

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#626]
It ends up being rendered over the voronoi. Appears to have been introduced in 2.8.

![1](https://cloud.githubusercontent.com/assets/980049/13550363/be05e2b4-e2d0-11e5-8506-519e66adea3f.gif)

Pending: tests.

**Comment by hamilton** [comment]
Yes, I had changed the way these get updated (a couple of weeks ago), which included adding & removing them. On one hand, the rollover API is now really easy to use. But on the other, the element gets constructed upon the rollover. I found that in practice it doesn't hurt too much, but am happy to revert back to it being a standard set of elements that get drawn.

**Comment by almossawi** [comment]
Instead of adding and removing the container, better to just clear and repopulate it. I've made the change. Keeping this open to add tests.
