### ISSUE TITLE
yax_units option would be useful as a suffix symbol, not just prefix 

### ISSUE THREAD

**Issue by bellerbrock** [mozilla/metrics-graphics#636]
When labeling the y axis with units, such as °C or mm, it would be useful to be able to append them to the labels. 30°C or 100mm is more intuitive than °C30 or mm100. 
I just changed this quickly in my own copy of metricsgraphics.js by finding every instance of the args.yax_units variable, and moving it from the front of each addition operation to the back. But that's an ugly, temporary solution. Could something like yax_prefix and yax_suffix be made into new options?

**Comment by almossawi** [comment]
Yes. #619

**Comment by bellerbrock** [comment]
Ah, I see. My mistake, I should have searched through the other issues
first.

On 27 April 2016 at 12:26, Ali Almossawi <notifications@github.com> wrote:

> Yes. #619 <https://github.com/mozilla/metrics-graphics/issues/619>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/metrics-graphics/issues/636#issuecomment-215138581>
>



-- 
Bryan Ellerbrock
Research Specialist, Mueller Lab
Boyce Thompson Institute for Plant Research
Office/Lab: 211 | 607-227-9868
