### ISSUE TITLE
MG passing NaN

### ISSUE THREAD

**Issue by thesec** [mozilla/metrics-graphics#637]
Am getting a 
> Unexpected value NaN parsing cx attribute

in d3.js when passing the minimum sample data as follows

`MG.data_graphic( {
                    data: [[{'date':['2014-04-16'], 'value':[1]}]],
                    target: '#trunk'
                } );`

How comes? How to fix?

**Comment by almossawi** [comment]
```javascript
var data = [{'date': '2014-04-16', 'value': 1}];
MG.convert.date(data, 'date');

MG.data_graphic( {
  data: data,
  target: '#trunk'
});
```

**Comment by thesec** [comment]
thx
