### ISSUE TITLE
x line time format ?

### ISSUE THREAD

**Issue by prodimon** [mozilla/metrics-graphics#638]
As icispolzovat date in the format  2016-05-14 01:35:02 ?

I do not know how to convert the data in a graph
```
[
{"date":"2016-05-14 01:35:02","value":"0"},
{"date":"2016-05-14 01:40:02","value":"3"},
{"date":"2016-05-14 01:45:02","value":"2"},
{"date":"2016-05-14 01:50:02","value":"9"}
]
```

**Comment by almossawi** [comment]
```javascript
var data = [
  {"date":"2016-05-14 01:35:02","value":"0"},
  {"date":"2016-05-14 01:40:02","value":"3"},
  {"date":"2016-05-14 01:45:02","value":"2"},
  {"date":"2016-05-14 01:50:02","value":"9"}
]

MG.convert.date(data, 'date', '%Y-%m-%d %H:%M:%S');

MG.data_graphic({
  data: data,
  target: ".result"
});
```

**Comment by nskerl** [comment]
I hate to tag on here, but has anyone tried to do this with a UTC stamp?

2016-05-20T14:41:00-07:00

Ive tried with `data = MG.convert.date(data, "Date","%Y-%m-%dT%H:%M:%S%Z");` but no luck:

https://jsfiddle.net/ce3wofx0/

**Comment by almossawi** [comment]
@nskerl The colons are the culprit. The fix will land [in D3 v4](https://github.com/d3/d3/issues/2055#issuecomment-190545851). Until then, use ``2016-07-20T09:58:00-0700`` instead of ``2016-07-20T09:58:00-07:00``.
