### ISSUE TITLE
flawed transition between dataseries with different number of datapoints

### ISSUE THREAD

**Issue by matkoniecz** [mozilla/metrics-graphics#641]
![out](https://cloud.githubusercontent.com/assets/899988/15627500/6aaf4ec2-24e6-11e6-8dbc-a5e4b8f874ca.gif)

this problem disappears on replacing null with 0 (see https://github.com/matkoniecz/bug_report-testcase-metrics-graphics/commit/7b5a030ce6908559e31390403c2082b7b0a92d15)

![out](https://cloud.githubusercontent.com/assets/899988/15627508/b7763aa4-24e6-11e6-9619-911a3df225fa.gif)

testcase resides in https://github.com/matkoniecz/bug_report-testcase-metrics-graphics repository (file toggleable_chart.html).

**Comment by matkoniecz** [comment]
Tested in 46.0.1 on Lubuntu 14.04.

**Comment by almossawi** [comment]
You'll want to set [missing_is_zero](https://github.com/mozilla/metrics-graphics/wiki/Data#missing_is_zero).

**Comment by matkoniecz** [comment]
In this case it is decent workaround, but it would fail for cases where missing value is next to higher value.
