### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by TheGelato** [mozilla/metrics-graphics#645]
How to increase font size for the labels on X and Y Axis?

**Comment by almossawi** [comment]
[.mg-x-axis text and .mg-y-axis text](https://github.com/mozilla/metrics-graphics/blob/master/dist/metricsgraphics.css#L346). Remember to [set the font-size for your html element](https://github.com/mozilla/metrics-graphics/blob/master/examples/css/metricsgraphics-demo.css#L117).
