### ISSUE TITLE
missing_is_hidden not working on interactive demo

### ISSUE THREAD

**Issue by mattweber-bbg** [mozilla/metrics-graphics#647]
If you delete some data from [the interactive demo](http://metricsgraphicsjs.org/interactive-demo.htm) and set `missing_is_hidden: true`, the missing data isn't hidden -- it's linearly interpolated. Obviously I wouldn't care much about this if my own data weren't having the same problem. :) Any idea why this works in the examples but not the interactive demo?

```
//modify away!
MG.data_graphic({
  title: "UFO Sightings",
  description: "Yearly UFO sightings from 1945 to 2010.",
  data: JSON.parse($('.data textarea').val()),
  markers: [{'year': 1964, 'label': '"The Creeping Terror" released'}],
  width: 400,
  height: 250,
  target: ".result",
  x_accessor: "year",
  y_accessor: "sightings",
  missing_is_hidden: true,
});
```

**Comment by almossawi** [comment]
[This change](https://github.com/mozilla/metrics-graphics/commit/2c8dfd75d46d77a8c23ffaf6cc5ef7a76a550c64#diff-62588ad2632505b865edba204bce939a) to _mg_get_time_frame_ broke that option. v2.9 is therefore impacted.

Fixing and adding a test for it momentarily. Thanks for reporting the issue.

**Comment by almossawi** [comment]
```javascript
var data = [
  {
    "year": "1945-01-01",
    "sightings": 6
  },
  {
    "year": "1945-01-02",
    "sightings": 8
  },
  {
    "year": "1945-01-03",
    "sightings": 34
  },
  {
    "year": "1945-01-09",
    "sightings": 15
  },
  {
    "year": "1945-01-10",
    "sightings": 25
  }
];

MG.convert.date(data, 'year');

MG.data_graphic({
  data: data,
  target: ".result",
  x_accessor: "year",
  y_accessor: "sightings",
  missing_is_hidden: true,
});
```

![11](https://cloud.githubusercontent.com/assets/980049/16500179/6a9bd6da-3eb8-11e6-9ec1-d34266a7e890.gif)

**Comment by almossawi** [comment]
Also changed the deployed version of the example to 2.8: http://metricsgraphicsjs.org/examples.htm#data
