### ISSUE TITLE
Support server rendering?

### ISSUE THREAD

**Issue by benwiley4000** [mozilla/metrics-graphics#650]
I know this is far-fetched! But _how_ far-fetched?

Use case: I server-side render my pages with React, so they're ready to look at when they hit the client. But `componentDidMount` doesn't get called in my React component until it has loaded on the client, and that's my opportunity to render my charts to the page. For a large app that means a pretty long pause before a jarring visual change when the charts get added!

Hypothetical solution: server side SVG rendering. MetricsGraphics somehow generates the SVG as a string on the server, and I can use React's `dangerouslySetInnerHTML` to include it inline manually. On the client, MG can modify the preexisting SVG per usual.

Obvious problem: client dependencies. An obvious one is jQuery (see my other issue topic on removing jQuery as a hard dependency: https://github.com/mozilla/metrics-graphics/issues/649) and we also need the DOM to exist since d3 works by operating on DOM elements. A potential solution is to use a server side DOM with d3, like in [this example](https://bl.ocks.org/tomgp/c99a699587b5c5465228).

The string content could then be extracted from the server DOM and included in React, or whatever other server side HTML algorithm you like.

I could use a different library of course, but I really like MetricsGraphics and want to be able to stick with it. :smiley: 
### Proposed API:

```
MG.render_to_string.data_graphic(options) // returns SVG string
```

**Comment by almossawi** [comment]
Do you want to submit a PR? :)

**Comment by benwiley4000** [comment]
Kind of? I'm a bit intimidated by my own idea but I could give it a shot if I can find some time to work on it.

**Comment by benwiley4000** [comment]
An update - I haven't forgotten about this and I would still potentially work on a PR, but it really depends on when I have time to prioritize this at work (sometime in the next few months). If anyone else feels like finding a way to tackle this I'd love to see someone give it a go. :smiley:

**Comment by DigitalMarc** [comment]
Any update on this?

**Comment by benwiley4000** [comment]
@DigitalMarc I just submitted one solution - want to let me know what you think of the API? It's different than I proposed initially.

**Comment by DigitalMarc** [comment]
Hey @benwiley4000 , thanks a lot! I've been looking quickly at the API and that seems nice! I'll not test it for now but I'll get there to check the benefits vs the drawback of the server side rendering as the server might receive to much pressure dealing with load of charts rendering.
Cheers!

**Comment by benwiley4000** [comment]
@DigitalMarc if you're working with something rather large and worried about render time blocking the server perhaps you could use [`child_process.fork`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) in Node.

**Comment by benwiley4000** [comment]
Though I feel such enhancements should be built into the module - I'll look into this if it's a problem (Creating a new virtual dom for each rendering request is probably expensive).

**Comment by benwiley4000** [comment]
@DigitalMarc My branch has been updated to re-use the virtual DOM between calls.
