### ISSUE TITLE
Remove gulp-es6-module-transpiler, use Babel?

### ISSUE THREAD

**Issue by benwiley4000** [mozilla/metrics-graphics#653]
I've forked `metrics-graphics` and I'm trying to build. Gulp returns this error: `Error: Cannot find module 'es6-module-transpiler/node_modules/recast'`.

I took a look in the `gulp-es6-module-transpiler` dependency - they have very bad code (https://github.com/ryanseddon/gulp-es6-module-transpiler/blob/master/lib/index.js#L13).

I don't really know what's wrong and I don't even understand how this module's being used in the build process since it's not referenced after being required, but I tried removing the require and that broke other things. Any chance Babel could be used instead?

**Comment by benwiley4000** [comment]
Also accepted: a way to make my build complete as is.

**Comment by Ezekiel-DA** [comment]
This isn't strictly an answer to your question re. removing this dependency entirely but I had the same issue trying to compile from scratch a couple of days ago.
It turns out that the `recast` module was not correctly installed because it needs Python to compile, which I did not have installed yet on this (Windows) machine.

If that's your problem too, be careful that you'll need Python 2.7; Python 3 won't work. After installation you should be able to rerun `npm install` and see the recast module finish its installation.

HTH !

**Comment by benwiley4000** [comment]
@Ezekiel-DA appreciate the tip - however I'm on Ubuntu 15.04 and I have Python 2.7 installed on my machine by default, so probably not.

I looked around and I'm now 99.999% sure the problem is that the author of the library didn't anticipate npm 3. It expects `recast` to be a submodule of `es6-module-transpiler`, but npm 3 produces a flat module tree structure until a version conflict emerges. It's not worth forking or pull requesting the library, since [es6-module-transpiler has been deprecated in favor of Babel](https://github.com/esnext/es6-module-transpiler#note-this-project-been-deprecated-in-favor-of-babel--rollup).

**Comment by Ezekiel-DA** [comment]
Interesting ! I didn't run into this issue even though I'm also using npm 3.
I imagine that is becauseafter the initial failure to build `recast` I tried a manual `npm install recast`, which added it as a top level module !

**Comment by Koslun** [comment]
Seeing the same issue using Ubuntu 15.10, npm 3.10.3, node 4.4.7 and python 2.7 (default install I think).

Manually installing recast did solve it. So does adding it to the devPackages in `package.json` as `"recast": "^0.11.10",`.

Would suggest updating `package.json` with `"recast": "^0.11.10",` for now.

Think long-term an optimal strategy would be to start using Rollup instead to also generally do some tree-shaking much like how d3 itself does and also recently in Angular 2 as well. As I remember reading the experience from a core Angular team member Rollup is a bit of a hassle to use but seems to at least work well for libraries/frameworks.

As @benwiley4000 mentioned the other option is however to start using babel. 

Either way, given that the library in use now is deprecated I would assume the switch need to happen sooner or later.

**Comment by almossawi** [comment]
Apologies for the late reply. I somehow missed this issue.

I've no objections at all to switching to Babel, in light of what you mentioned--I presume @hamilton doesn't have any either. I believe @dandehavilland was kind enough to put together a lot of the build process early on. Feel free to submit a PR. 👍

**Comment by jweir** [comment]
Just ran into this problem myself. A fix would be very nice.

**Comment by hamilton** [comment]
Sorry for very late reply folks. I am more than happy if we switch to Babel. I think fewer dependencies are a good thing here. I think a PR would be a good starting point for us.
