### ISSUE TITLE
BLOCKER: Broken examples (bar chart)

### ISSUE THREAD

**Issue by almossawi** [mozilla/metrics-graphics#654]
@hamilton 

* CSV files are missing for the bar chart (examples.htm#experimental)
* A recent commit appears to have broken the brushing add-on (examples.htm#addons)

**Comment by almossawi** [comment]
@hamilton To my knowledge, 1. fixing bars and histograms and 2. adding the new scatterplot examples you're working on are the only outstanding tasks, right?

Otherwise, 2.10 looks good to go.

**Comment by hamilton** [comment]
@almossawi Yes, this is the remaining work for 2.10. I am not sure if unifying the 'bar' chart type to histograms is going to make this release, because I think in general histograms could use an overhaul that would push back the release date even further.

**Comment by almossawi** [comment]
@hamilton I currently have some bandwidth, so I wouldn't mind looking into what it would take to get those working again. We can perhaps push the overhaul to 2.11.

**Comment by hamilton** [comment]
Agreed - overhaul should wait until 2.11. I'm finishing the bar chart port today and updating the examples page.

**Comment by almossawi** [comment]
@hamilton I'm currently updating the [documentation for bar charts](https://github.com/mozilla/metrics-graphics/wiki/Bar)--are there options other than predictors that won't exist or might perhaps work differently in 2.10?

**Comment by hamilton** [comment]
To my knowledge, no. I was thinking it may be a good move to state that bar charts are still experimental right now, and the design has not tightened up fully. I think the confusion generated by #679 has shown me that we should probably state clearly that these newer chart types need some annotation, and maybe even a small print to the console saying that the API / feature set for this chart type is not fully worked out.
