### ISSUE TITLE
how to include in the client side?

### ISSUE THREAD

**Issue by Markkos89** [mozilla/metrics-graphics#655]
I can't install metrics graphics on my node.js application.
sorry for creating an issue but maybe someone would give me a hand, been for hours now until i decide to create this issue, there is no information on the net.

the question is, where to paste files? which ones require on the html?

**Comment by hamilton** [comment]
Hello / sorry for the late reply - you can put either of ``metricsgraphics.js`` or ``metricsgraphics.min.js`` in the dist dir as the source, client-side. MG was developed primarily for client-side apps, and I believe there has been work done to integrate it more with node, but I am not knowledgeable on this.
