### ISSUE TITLE
React component

### ISSUE THREAD

**Issue by anvk** [mozilla/metrics-graphics#656]
I'm just curious if there any metrics-graphics React version of this library? And if there is no such thing and I (or any other developer) decides to create one would it allowed and compliant with Mozilla Public License v2.0 ?

**Comment by dashed** [comment]
There would be (and there shouldn't be) no licensing issues. 

If you do decide to create a react component, I'd be highly interested in checking it out 👍

**Comment by wlach** [comment]
This is implemented as a seperate library. See: https://github.com/mozilla/react-metrics-graphics
