### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of nulls

### ISSUE THREAD

**Issue by wanbinkimoon** [mozilla/metrics-graphics#658]
I try to create my own chart but i'm constantly getting this error, even if I try with the first example of the introduction section. 

> MG.data_graphic({
    title: "Downloads",
    description: "This graphic shows a time-series of downloads.",
    data: [{'date':new Date('2014-11-01'),'value':12},
           {'date':new Date('2014-11-02'),'value':18}],
    width: 600,
    height: 250,
    target: '#downloads',
    x_accessor: 'date',
    y_accessor: 'value',
})

**Comment by almossawi** [comment]
I'm unable to reproduce the error.

**Comment by wanbinkimoon** [comment]
I fixed the problem was on my app sorry to bother.

*Nicola Bertelloni* // +39 328 4559247

On 7 July 2016 at 19:04:18, Ali Almossawi (notifications@github.com) wrote:

I'm unable to reproduce the error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/metrics-graphics/issues/658#issuecomment-231142571>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJns11ZwFtJKkf0jYDyqFZF9zayGLXmkks5qTTFtgaJpZM4JG-wN>
.
