### ISSUE TITLE
Destroy MG graph

### ISSUE THREAD

**Issue by Davidx7** [mozilla/metrics-graphics#661]
What is the correct way to remove a MG graph in order to prevent memory leaks? 

Sorry for the issue, can't find anything relating to this

**Comment by Davidx7** [comment]
I ask because running `MG.data_graphic(gg)` works, but takes a long time before it does the resizing. A few seconds, sometimes more, and I don't get why

**Comment by Davidx7** [comment]
Fixed my own problem. 
If the redraw takes a long time with no plausible explanation, `empty()` the `<div>` where is `args.target` and fire `MG` again. It will be effective imediatly

**Comment by almossawi** [comment]
Would you mind sharing your data and code?
