### ISSUE TITLE
Use subset of d3 v4 modules

### ISSUE THREAD

**Issue by Koslun** [mozilla/metrics-graphics#662]
The probably largest change with the latest release of d3 (version 4) is that it has become modular. So I was wondering: is any interest in using this to select the subset of modules in d3 that this library actually uses rather than depending on all of d3?

As I currently have a very limited understanding of what modules this library uses and how big each d3 moduleis I am however not sure how much smaller this would make any final build size. But given how large d3 is I would suspect that it could be a very decent reduction and thus worth pursuing.

It would mean breaking changes for anyone assuming this library loads all of d3. But it should only be for them to manually include any part they want or include all of d3 themselves as I understand it. Either way,  upgrading to version 4 between 2.9 to 2.10 is a much bigger breaking change so would assume that it is not big issue.

Thoughts?

**Comment by almossawi** [comment]
I've not looked into just yet. Feel free to submit a PR. For reference, these are the D3 4 modules that MG uses:

* [d3-array](https://github.com/d3/d3-array)
* [d3-collection](https://github.com/d3/d3-collection)
* [d3-color](https://github.com/d3/d3-color)
* [d3-dispatch](https://github.com/d3/d3-dispatch)
* [d3-dsv](https://github.com/d3/d3-dsv)
* [d3-ease](https://github.com/d3/d3-ease)
* [d3-format](https://github.com/d3/d3-format)
* [d3-interpolate](https://github.com/d3/d3-interpolate)
* [d3-path](https://github.com/d3/d3-path)
* [d3-random](https://github.com/d3/d3-random)
* [d3-request](https://github.com/d3/d3-request)
* [d3-scale](https://github.com/d3/d3-scale)
* [d3-selection](https://github.com/d3/d3-selection)
* [d3-shape](https://github.com/d3/d3-shape)
* [d3-time](https://github.com/d3/d3-time)
* [d3-time-format](https://github.com/d3/d3-time-format)
* [d3-timer](https://github.com/d3/d3-timer)
* [d3-transition](https://github.com/d3/d3-transition)
* [d3-voronoi](https://github.com/d3/d3-voronoi)

```html
<script src="https://d3js.org/d3-array.v1.min.js"></script>
<script src="https://d3js.org/d3-collection.v1.min.js"></script>
<script src="https://d3js.org/d3-color.v1.min.js"></script>
<script src="https://d3js.org/d3-dispatch.v1.min.js"></script>
<script src="https://d3js.org/d3-dsv.v1.min.js"></script>
<script src="https://d3js.org/d3-ease.v1.min.js"></script>
<script src="https://d3js.org/d3-format.v1.min.js"></script>
<script src="https://d3js.org/d3-interpolate.v1.min.js"></script>
<script src="https://d3js.org/d3-path.v1.min.js"></script>
<script src="https://d3js.org/d3-random.v1.min.js"></script>
<script src="https://d3js.org/d3-request.v1.min.js"></script>
<script src="https://d3js.org/d3-scale.v1.min.js"></script>
<script src="https://d3js.org/d3-selection.v1.min.js"></script>
<script src="https://d3js.org/d3-shape.v1.min.js"></script>
<script src="https://d3js.org/d3-time.v1.min.js"></script>
<script src="https://d3js.org/d3-time-format.v2.min.js"></script>
<script src="https://d3js.org/d3-timer.v1.min.js"></script>
<script src="https://d3js.org/d3-transition.v1.min.js"></script>
<script src="https://d3js.org/d3-voronoi.v1.min.js"></script>
```

**Comment by Koslun** [comment]
Cool, are you completely sure that no more or less than those packages are in use? Can try to investigate it further if there are uncertainties.

Nevertheless, assuming those are the packages to be used I took them and the all the packages d3 v4 depends on and compared them in a google drive spread sheet [here](https://docs.google.com/spreadsheets/d/1HgjhFayT-br5XGZxIJhk49YymiQdCPOwXdTq0oCDo7w/edit?usp=sharing).

The conclusion is that the following packages should then be possible to drop: 

```javascript
"d3-axis": "1.0.0",
"d3-brush": "1.0.1",
"d3-chord": "1.0.0",
"d3-drag": "1.0.0",
"d3-force": "1.0.0",
"d3-geo": "1.1.1",
"d3-hierarchy": "1.0.0",
"d3-polygon": "1.0.0",
"d3-quadtree": "1.0.0",
"d3-queue": "3.0.1",
"d3-zoom": "1.0.2"
```

Can begin with checking out the current size of each package to get an idea of the actual benefit. Should then probably be able to send a PR this weekend or sometime next week.

**Comment by Koslun** [comment]
Updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1HgjhFayT-br5XGZxIJhk49YymiQdCPOwXdTq0oCDo7w/edit?usp=sharing). 

Looking at the uncompressed sum of the d3 modules when minified, the saving should come down to ~74.8 kB. Going from ~211.1 kB to ~136.3 kB (35.43% reduction), if you assume that you use the custom d3 v4 minified build. If you simply use each individual module it goes up to about ~220.6 kB, saving upwards of ~84.3 kB (38.21% reduction). Though I disregard the further optimization of doing a local build of this specific set using rollup, webpack 2.0 or something similar. While the final size served in production when compressed is also smaller.

Regardless, conclusion remains that the d3 dependency size can be reduced by a little more than a third.

**Comment by Koslun** [comment]
More difficult than I had hoped. Requiring directly from the sub-modules stops `d3` from being globally available. Thus breaking all but 17 tests.

So think you need to manually export each module and make them available globally on  `d3`.

I am however not sure how to actually to that in this project. Thinking that you would want to export all the sub-modules like in the[ 'index.js' file in `d3`](https://github.com/d3/d3/blob/master/index.js). But export with `*` like this: `export * from 'd3-dependency'`, rather than explicitely stating each exported member, and then importing all of them to a global `d3` variable.

Will start a PR with the relevant modules updated in `bower.json` and `package.json` and hopefully someone else can figure this out.
