### ISSUE TITLE
Wiki page Graphic missing a chart_type possible value

### ISSUE THREAD

**Issue by rixlabs** [mozilla/metrics-graphics#664]
The section [chart_type](https://github.com/mozilla/metrics-graphics/wiki/Graphic#wiki-chart_type) of the Graphic wiki is missing **bar** as one of the possible chart types.

No it is
`Possible values: {'line', 'histogram', 'point', 'missing-data'}`

Should be
`Possible values: {'line', 'histogram', 'point', 'bar', 'missing-data'}`

This page is the only one where I found the exact parameters to set the chart. It isn't useful to add this values also on the specific Chart Types page or is better to keep that page generic as it is?

**Comment by almossawi** [comment]
Good catch 👍
