### ISSUE TITLE
D3 time format is a mix of old and new syntax in the dist file

### ISSUE THREAD

**Issue by ashokfernandez** [mozilla/metrics-graphics#668]
I've searched the source for the repo and it seems that all of the references to the old d3 v3 time format have been changed from `d3.time.format` to `d3.timeFormat` as discussed [here](https://github.com/d3/d3/blob/master/CHANGES.md#time-formats-d3-time-format)

However in the [dist file for the current version](https://github.com/mozilla/metrics-graphics/blob/68f64a8a700c20666d9c0f68087a28fcb6ca3ef2/dist/metricsgraphics.js#L2771) on line 2771 there seems to be a reference to `d3.time.format` on which throws an error when you've got d3 v4 setup. 

Is the dist version an old build of the current source?

**Comment by almossawi** [comment]
Good catch, thanks. 👍
