### ISSUE TITLE
Reverse time-axis zigzag shape

### ISSUE THREAD

**Issue by vic317yeh** [mozilla/metrics-graphics#672]
For some reason my graph shows a zigzag shape in the reverse time order (check out the plot near July 12).

<img width="668" alt="screen shot 2016-07-21 at 4 47 26 pm" src="https://cloud.githubusercontent.com/assets/4696273/17042517/fe137d72-4f62-11e6-8eea-6f88f711f361.png">
 
My dates are sorted in order, but there is a huge gap of data between June 27 and July 11. How do I make the plot smooth in attempt to remove the zigzag shape?

**Comment by almossawi** [comment]
See [interpolate](https://github.com/mozilla/metrics-graphics/wiki/Graphic#interpolate). Setting it to _linear_ ought to fix that.

**Comment by vic317yeh** [comment]
It worked. Thanks!
