### ISSUE TITLE
When multiple charts are shown on one page, all x-axis labels are bunched below the first chart

### ISSUE THREAD

**Issue by openjck** [mozilla/metrics-graphics#677]
### Steps to reproduce

Download and open this [HTML document](https://gist.github.com/openjck/f49a6c2cc23160ebc1a06095b76b8215)

### Actual result

The first chart has five x-axis labels ([screenshot](https://cloud.githubusercontent.com/assets/933396/17157879/79722e04-5360-11e6-829c-9cca057246e3.png)). The rest of the charts don't have any.

### Expected result

Each chart should have one x-axis label.

**Comment by almossawi** [comment]
Thanks, fixed.

**Comment by openjck** [comment]
Wow that was fast. Do you know when the next version will be released to NPM?

**Comment by almossawi** [comment]
Hopefully, by next week.
