### ISSUE TITLE
Vertical bar error

### ISSUE THREAD

**Issue by vic317yeh** [mozilla/metrics-graphics#679]
I tried to run the vertical bar example in the experimental page but kept getting this error: 
d3.v3.js?v=8be1f0b:598 Error: <text> attribute x: Expected length, "NaN".
Does anyone know what the problem is?

**Comment by hamilton** [comment]
Vertical bars (which are marked as 'experimental') are as of 2.9 not very stable, so it wouldn't be surprising. But I think this brings up a great point - until we feel some of our other code base is ready to go, we should mark it as unequivocally experimental.
