### ISSUE TITLE
[Feature Request] - Export as JPEG, PNG, PDF built in Like Highchart.

### ISSUE THREAD

**Issue by bhaveshgohel** [mozilla/metrics-graphics#682]
Hello, Is it possible to export charts like in Highchart to JPEG, PNG, PDF etc.. ?

**Comment by almossawi** [comment]
See #550.

**Comment by bhaveshgohel** [comment]
@almossawi : Hi, I'm aware about the #550, but It will be great if it could be the built in functionality via some options or adding some file for just export functionality. :)

**Comment by hamilton** [comment]
This function will likely not be implemented any time soon. You could, however use Firefox Screenshots or the function @almossawi referred to in #550, but that's about the best we can provide at this point.
