### ISSUE TITLE
Uncaught TypeError: curve is not a function d3.v4.js

### ISSUE THREAD

**Issue by Pascal66** [mozilla/metrics-graphics#686]
After Migrating to d3.v4, to continue to use MG,  i've this error
I just saw 4.0 introduces a new curve API but no issue about that, in the line 
'''if (context == null) output = curve(buffer = path());

I know it not depend directly to MG, but i now use d3.v4, i hope someone else have this issue

**Comment by Pascal66** [comment]
My fault, i've not migrated fully my code using metricsgraphics :
`interpolate: d3.curveStep, //"step",`

**Comment by almossawi** [comment]
Yes, please refer to the [release notes](https://github.com/mozilla/metrics-graphics/releases/tag/v2.10.0) for a list of API changes. [interpolate](https://github.com/mozilla/metrics-graphics/wiki/Graphic#interpolate) now takes a function rather than a string.

**Comment by Pascal66** [comment]
:+1: 
Btw i didnt find anything for my new error : 
d3.v4.js:7680 Uncaught TypeError: Cannot read property 'ownerDocument' of null

'  function window(node) {
    return (node.ownerDocument && node.ownerDocument.defaultView) // node is a Node
        || (node.document && node) // node is a Window
        || node.defaultView; // node is a Document
  }
'
