### ISSUE TITLE
x-axis labels are too long for some data

### ISSUE THREAD

**Issue by openjck** [mozilla/metrics-graphics#691]
### Steps to reproduce

Download and open this [HTML document](https://gist.github.com/openjck/1aed4bb0358fce7f275f42c8b4a37c9d)

### Actual result

Many of the x-axis labels are too long.

### Expected result

The x-axis labels should be: *0*, *0.1*, *0.2*, *0.3*, *0.4*, *0.5*, *0.6*, *0.7*, and *0.8*.

**Comment by openjck** [comment]
🕴👉

**Comment by almossawi** [comment]
Thanks 👍

**Comment by almossawi** [comment]
@hamilton Any objections to a v2.10.1 release for this issue?

**Comment by almossawi** [comment]
@openjck Ok to close?

**Comment by openjck** [comment]
Sure

**Comment by openjck** [comment]
Sure thing. Thanks for the fix!
