### ISSUE TITLE
process_line() should not force interpolate = d3.curveLinear with missing_is_hidden

### ISSUE THREAD

**Issue by brwebb** [mozilla/metrics-graphics#693]
It appears that other d3 interpolate functions will work with missing_is_hidden. As an example, I tried d3.curveCatmullRom.alpha(1) and it appeared to render properly. Can the implementation be changed to allow client code to configure the interpolate function when hidden_is_missing is true? Thanks!

Existing code:

https://github.com/mozilla/metrics-graphics/blob/c9aee2c9b8ad7e9876ed17c6514b0ebb0c16a591/src/js/misc/process.js#L174

  // force linear interpolation when missing_is_hidden is enabled
  if (args.missing_is_hidden) {
    args.interpolate = d3.curveLinear;
  }

**Comment by almossawi** [comment]
Good catch. That appears to no longer be necessary.

**Comment by brwebb** [comment]
Thanks!
