### ISSUE TITLE
Transition state incorrectly has continuous line with missing_is_hidden: true

### ISSUE THREAD

**Issue by brwebb** [mozilla/metrics-graphics#694]
I am using MG 2.10. I have the following configuration:

            transition_on_update: true,
            missing_is_hidden: true,

I have segments of the data that are missing in the time series data. During the transition, the line appears to temporarily switch to missing_is_hidden = false state. Before and after the transition correctly do not show line segments for missing data. However, the transition state incorrectly has a continuous line.

**Comment by almossawi** [comment]
This commit fixes it, though I wonder whether the custom tween function is necessary anymore.
![12](https://cloud.githubusercontent.com/assets/980049/17713035/b48af4aa-63ad-11e6-92cf-daeccfe466bb.gif)

**Comment by brwebb** [comment]
Thanks!
