### ISSUE TITLE
aggregate rollovers with multiline data, of single points, cause error

### ISSUE THREAD

**Issue by jweir** [mozilla/metrics-graphics#695]
The below graph will raise an error `Cannot read property '0' of undefined`

```js
    MG.data_graphic({
      data : [{x: 1, y1: 10, y2: 10}],
      target: '#graph-prices',
      x_accessor: 'x',
      y_accessor: ["y1","y2"],
      aggregate_rollover: true,
    });
```
at https://github.com/mozilla/metrics-graphics/blob/master/src/js/charts/line.js#L536

Using only 1 y_accessor, or adding another item to the data does not cause the error.

**Comment by almossawi** [comment]
Thanks 👍
