### ISSUE TITLE
Markers do not appear with non-default x_accessor

### ISSUE THREAD

**Issue by esbie** [mozilla/metrics-graphics#704]
When specifying markers, I only see them rendered in the svg canvas if the graph's `x_accessor` is set to 'date'. If I set the `x_accessor` to anything else, the mg-markers container is empty, while the rest of the graph renders no problem.

**Comment by almossawi** [comment]
Would you mind sharing your code? You can take a look at the [interactive demo](http://metricsgraphicsjs.org/interactive-demo.htm) for a working example.

**Comment by esbie** [comment]
Ah I see my mistake. I was looking at examples [here](http://metricsgraphicsjs.org/examples.htm#annotations) and [here](https://github.com/mozilla/metrics-graphics/wiki/Graphic#markers) all of which have markers that specify a `date` field. 

So I incorrectly assumed `date` had to be the name of the field, when in fact the name of the field has to be whatever the `x_accessor` is set to.

Thanks for your reply!
