### ISSUE TITLE
extending axe

### ISSUE THREAD

**Issue by Pascal66** [mozilla/metrics-graphics#706]
IS it possible to extend the x-axe to 1 day or 1 week or 1 month later ?

**Comment by almossawi** [comment]
You'll want to set [max_x](https://github.com/mozilla/metrics-graphics/wiki/Axes#max_x).

**Comment by Pascal66** [comment]
ok but how I know the actual x to add 1 week to max_x ?

**Comment by Pascal66** [comment]
I found the way to do.
Can I add  a trend line in this extended x axis ?
