### ISSUE TITLE
Shortened x-axis labels can be misleading

### ISSUE THREAD

**Issue by openjck** [mozilla/metrics-graphics#707]
### Steps to reproduce

Download and open this [HTML document](https://gist.github.com/openjck/3eb8471f3d25c7042794c820a1a201d8)
### Actual result

The x-axis labels are:
**500&emsp;1k&emsp;2k&emsp;2k&emsp;2k&emsp;3k**
### Expected result

The x-axis labels should be something like:
**500&emsp;1.0k&emsp;1.5k&emsp;2.0k&emsp;2.5k&emsp;3.0k**

**Comment by openjck** [comment]
Screenshot :smile:

![screen shot 2018-02-12 at 3 11 06 pm](https://user-images.githubusercontent.com/933396/36117283-ff9f3436-1006-11e8-882b-0e831b96ebaa.png)

**Comment by shikhar-scs** [comment]
@wlach If no one is working on this issue, can I take it up please ?

**Comment by daosist92** [comment]
Sry if it's offtop but maybe the issue https://github.com/mozilla/metrics-graphics/issues/753 is connected with this. Anyway if it's so I'll be very grateful if you take a look.

**Comment by openjck** [comment]
@shikhar-scs It sounds like you're free to take it up. At least that's how I interpret the *help wanted* label. :smile:

**Comment by shikhar-scs** [comment]
Thankyou @openjck for that, I'll get started with the work soon 👍

**Comment by shikhar-scs** [comment]
Surprisingly in my system it shows this file to be correct :open_mouth: 

![hey](https://user-images.githubusercontent.com/25258877/36252302-26292a48-126a-11e8-8049-66f4bc5c1f17.png)

**Comment by openjck** [comment]
@shikhar-scs Are you using the Gist, which uses a later version of metrics-graphics, or master? Maybe it was fixed and the issue wasn't closed.

**Comment by shikhar-scs** [comment]
> Maybe it was fixed and the issue wasn't closed.

Yeah that is what I think.

**Comment by openjck** [comment]
I'm also seeing that it was fixed *at least* as early as b363d82c229fba6a280c9782b8154aad0ac901e7, maybe much earlier.

**Comment by shikhar-scs** [comment]
Yeah. So I guess @wlach this can be closed

**Comment by wlach** [comment]
Ok, closing! Thanks all.
