### ISSUE TITLE
Wrong Y axis values

### ISSUE THREAD

**Issue by dbulic** [mozilla/metrics-graphics#709]
At http://metricsgraphicsjs.org/examples.htm#lines (Linked Graphic, top chart), we can see that first point is next to 20M label value. However, it's a 15M value actually.

![y-axis](https://cloud.githubusercontent.com/assets/22821/18273992/782bac54-7440-11e6-861c-d32ddb9a0afd.png)

https://github.com/mozilla/metrics-graphics/blob/master/examples/data/brief-1.json

```
{
        "date": "2014-02-01", 
        "value": 15000000
}
```

**Comment by exitgames** [comment]
Am experiencing the same, yet with a 1.5k showing as 2k. When to expect a fix?

**Comment by exitgames** [comment]
Worked around explicitely setting `yax_format: d3.format(',.0s')`.

**Comment by exitgames** [comment]
Hmm, the precision is what does the trick .2 works, even with ',.2s' ... '.1s' already fails.
Waiting for a fix.

**Comment by almossawi** [comment]
Thanks 👍
