### ISSUE TITLE
Bar chart full_width not working

### ISSUE THREAD

**Issue by fengxia41103** [mozilla/metrics-graphics#737]
Using version 2.11.0.

Graph type "bar" will not respect "full_width=true"; line chart works fine. Setting "width=[a number]" works, but this defeats the purpose of a responsive design. Tried setting "full_width=true, full_height=false", same effect.

Examined DOM, the top level SVG element has the correct width, but the actual graph is 1/3 of it visually.  

Options:
    this.options = {
      title: "",
      description: "",
      full_width: true,
      full_height: true,
      rotate_x_labels: 45,
      area: false,
      x_accessor: 'year',
      y_accessor: 'value',
      legend_target: 'div#custom-color-key',
      colors: ['blue', 'rgb(255,100,43)', '#CCCCFF'],
      aggregate_rollover: true
    }

**Comment by hamilton** [comment]
Bar charts are not fully implemented at this point (and indeed marked 'experimental' on our documentation), and I'm sure once we circle back on this, we'll fix this.
