### ISSUE TITLE
Left and right y axes?

### ISSUE THREAD

**Issue by cache-rules** [mozilla/metrics-graphics#739]
Hello,

I'm working on a project that visualizes some metrics data, and I'd like to use MetricsGraphics, but it looks to be lacking a critical feature. I need to be able to plot up to 4 different series of data in a chart, but some of the data has very large y-axis numbers (i.e. a value of 1,000,000) while other metrics would be much smaller (i.e a value of 1 or 5). When plotting these measures on the same y-axis scale the series with large numbers looks fine, but the series with smaller values just looks like a flat line. In other charting libraries (i.e. ggplot2, D3) I have had the ability to use a different scale for each series and render those scales on the left and right side of the chart.

As far as I can tell I cannot do this with MetricsGraphics, but please correct me if I am wrong. If it currently is not possible, is this a feature that you would be willing to add to MetricsGraphics? If so, I may be willing to do it, but it would be helpful to have someone point me in the right direction.

Thanks,
Alan

**Comment by SinanGabel** [comment]
That could be great. 

If possible it could be great to have an option that would allow for automatic allocation (some kind of "most appropriate allocation") of the different time series to the two axis (left and right axis).

**Comment by hamilton** [comment]
Hi - apologies for the delay in response here! I'm afraid this is out of scope for Metrics Graphics for philosophical reasons. We've discussed this in #138 before, if you'd like to see an explanation.
