### ISSUE TITLE
Enable synchronized rollover of multiple charts

### ISSUE THREAD

**Issue by calexicoz** [mozilla/metrics-graphics#742]
Hi there,

Kudos for MG! It's a great library :D

Often times, I show dashboards with multiple graphs, each presenting their own set of metrics (multiple lines). It would be nice to have the rollover on one chart be a rollover on all the charts simultaneously, so one could look at all the values at a point in time easily (and/or look at the shape of each graph at a specific point in time).

Thanks!

**Comment by hamilton** [comment]
Hi - this is certainly already doable. Take a look [here](https://github.com/mozilla/metrics-graphics/wiki/Graphic#linked).

Apologies for the late reply - I was on leave for the last few months, meanwhile the other contributor left Mozilla, so things are a bit backed up at the moment.

**Comment by calexicoz** [comment]
No worries at all, and thanks for the update!
