### ISSUE TITLE
Divide time series graph into two colors

### ISSUE THREAD

**Issue by dhruvarora93** [mozilla/metrics-graphics#744]
Hi,

I am drawing a time-series graph using the library. I want to divide my graph in two different colors, as in, from Jan-June the graph should be in a particular color and from July onwards in a different color. How can I do that ? Appreciate any help.

Thanks.

**Comment by arnonuem** [comment]
@dhruvarora93 I am working on the same issue. Have you found any solution yet?

**Comment by hamilton** [comment]
A pretty easy way to do that would be to make two time series for the two different colors, and plot that. As of now there is no way to do that with a single array of data.

**Comment by wlach** [comment]
I think we're just going to suggest using @hamilton's suggestion above to handle this case.
