### ISSUE TITLE
any directive for angular?

### ISSUE THREAD

**Issue by xycloud** [mozilla/metrics-graphics#748]
any directive for angular?

**Comment by YagoLopez** [comment]
Hey there.

Do you mean, Angular 2+?

I'm finishing a dashboard that includes an Angular MetricsGraphics component and a Leaflet Maps Directive. Take a look at: [NG Dashboard](https://github.com/YagoLopez/ng-dashboard)

The dashboard itself is based on a library of angular ui components developed by me:
[Material Light](https://github.com/YagoLopez/material-light)

Comments and sugestions are welcome.

**Comment by alexrussell** [comment]
FWIW the Readme mentions an "angular directive" in the [Gallery section](https://github.com/mozilla/metrics-graphics#gallery) at the end.

Links to https://github.com/elmarquez/angular-metrics-graphics but it may be out of date as it appears to have last been edited in 2015.

**Comment by YagoLopez** [comment]
@alexrussell yes, that is a directive for the old version of AngularJS.

For anyone interested in a component for the new version  (v4+) here is the code:
[MgChart](https://github.com/YagoLopez/ng-dashboard/tree/master/src/app/mgChart).

It is part of a Dashboard project for Angular (v4+) [NG Dashboard](https://github.com/YagoLopez/ng-dashboard)

[Demo online](https://yagolopez.js.org/ng-dashboard/dist)

Feel free to test it and leave any comment

**Comment by wlach** [comment]
Hey all, we are currently linking to one angular wrapper in the README.md, feel free to send pull requests to add more. Closing this issue, as we won't be adding angular support directly inside metricsgraphics itself.
