### ISSUE TITLE
How to render an image instead of group/category label?

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#751]
We have an application that asks users how they are feeling, by presenting them with a series of faces:

![screenshot_20170417_204516](https://cloud.githubusercontent.com/assets/17307/25097821/c5fd2908-23ae-11e7-9095-d63ec4cdcbd9.png)

We would like to render a bar chart, or other chart type, with the results of the question:

![screenshot_20170417_204620](https://cloud.githubusercontent.com/assets/17307/25097857/ecb13206-23ae-11e7-9c3d-6b56dbb5a2da.png)

How can we display the corresponding face, rather than the emotion name, for the bar chart categories?

**Comment by hamilton** [comment]
Great idea. Not sure at the moment. Bar charts are not a fully-finished thing quite yet, but it seems like the real issue is we should be able to render images as labels in some way.

**Comment by Gaetane** [comment]
It could be great also to be able to add images in the markers label, to highlight some important data.

**Comment by brylie** [comment]
Yep, I am literally just working on the above chart in our project.

Any update on this request, or ideas as to how to proceed?

**Comment by hamilton** [comment]
We're getting back to sorting through all the issues right now. I'm afraid this is not on our roadmap at the moment.
