### ISSUE TITLE
Add support for Vega grammar

### ISSUE THREAD

**Issue by brylie** [mozilla/metrics-graphics#757]
> Vega is a visualization grammar, a declarative language for creating, saving, and sharing interactive visualization designs.
>The goal of the Vega project is to promote an ecosystem of usable and interoperable tools, supporting use cases ranging from exploratory data analysis to effective communication via custom visualization design.
> [Vega homepage](https://vega.github.io/vega/)

A delarative visualization language, or grammar, gives people an intuitive way to create data visualizations. Vega is attempting to build a standardized, research-based, grammar for data visualization.

# Goal
Align Metrics Graphics with the Vega *ecosystem*, by adding incremental support for Vega semantics.

**Comment by hamilton** [comment]
Thank you for the issue. We're getting back to sorting through all our currently-open issues, and I'm afraid this is out of scope for MG.
