### ISSUE TITLE
End load event

### ISSUE THREAD

**Issue by YagoLopez** [mozilla/metrics-graphics#759]
Hello. I'm making a MG Angular 4 Component. I'have searched for something like "event loaded" with no luck.

Is there any event/life cycle hook/callback to know when a chart has ended its process?

Thank you.

**Comment by hamilton** [comment]
Given that MG is a synchronous library, you could just put the callback right after the call to `MG.data_graphic`. We do not currently support any other form of an "event loaded" hook at the moment, but may in the future once we embark on refactoring the hooks.

**Comment by YagoLopez** [comment]
@hamilton Thanks for the response. I will try with using a callback.
