### ISSUE TITLE
Y-axis label sometimes overlaps ticks

### ISSUE THREAD

**Issue by openjck** [mozilla/metrics-graphics#764]
### Steps to reproduce

Download and open this [HTML document](https://gist.github.com/openjck/621505033bc9b22d7d24eb7f48f65062)

### Actual result

The y-axis label overlaps the y-axis ticks

### Expected result

The y-axis label should not overlap the y-axis ticks

**Comment by wlach** [comment]
This still seems to be reproducible, would be nice to fix.

![image](https://user-images.githubusercontent.com/20569/33966702-32209c9e-e026-11e7-8a9f-42db0872443d.png)

**Comment by himanish-star** [comment]
@wlach, Can I take over this issue?
