### ISSUE TITLE
[Question] How to force Y axis to not display its negative part?

### ISSUE THREAD

**Issue by EpocDotFr** [mozilla/metrics-graphics#773]
Hello!

I have a little issue using MG (wonderful library BTW!) when Y values are all equal to 0.

![image](https://user-images.githubusercontent.com/2053431/33135305-5242be4c-cfa2-11e7-89bf-5f3b3cc92dfe.png)

In my use case, negative Y values aren't possible but as you can see MG shows me the `-1` Y tick instead of the `1` one. Setting `min_y` to `0` has no effect.

Do anyone know how to prevent this behavior?

**Comment by EpocDotFr** [comment]
Hello?

**Comment by EpocDotFr** [comment]
Can please someone help me?

**Comment by wlach** [comment]
@EpocDotFr This looks like a bug to me. I will try to have a quick look at it tomorrow, but just bear in mind there is no one whose full-time job it is to maintain or support this library. The source isn't *too* hard to understand if you want to try and solve the problem yourself.

**Comment by EpocDotFr** [comment]
I think the issue is located [here](https://github.com/mozilla/metrics-graphics/blob/815373f836cf5e702044b292d3535492c5b49c77/src/js/common/y_axis.js#L888). Setting `max_y` to something high will bypass all those computations and display a positive Y axis. Example for `max_y` set to `1000` will all axis `Y` values set to `0`:

![image](https://user-images.githubusercontent.com/2053431/34490187-5c33619c-efdf-11e7-9c14-5476a6c8e595.png)

**Comment by wlach** [comment]
I think #788 should fix the issues here, waiting for Hamilton to give a review.

**Comment by EpocDotFr** [comment]
I would happily want to test this fix but I cannot find any compiled JS file (I don't use NPM).

**Comment by wlach** [comment]
If you're inclined it probably wouldn't be too difficult to modify the metricsgraphics distribution files to include the changes above, otherwise I can do up a new release with this and some other fixes next week (after it is reviewed)

**Comment by EpocDotFr** [comment]
Confirmed: the issue is fixed with your modification.

**Comment by shikhar-scs** [comment]
I guess this bug has been fixed. (If yes) Please close this

**Comment by EpocDotFr** [comment]
The bug is fixed but the fix is not yet released. IMO it's better to close this issue once the fix is released.

**Comment by shikhar-scs** [comment]
Yeah Sure :+1:

**Comment by EpocDotFr** [comment]
I confirm this bug was fixed in the latest 2.11 release. CLosing issue. Thank you!
