### ISSUE TITLE
Change 'follow' to 'following' in README.md

### ISSUE THREAD

**Issue by himanish-star** [mozilla/metrics-graphics#799]
The line `For an eleventh line, you would add the follow CSS rules:` should be changed to `For an eleventh line, you would add the following CSS rules:`

![image](https://user-images.githubusercontent.com/30361728/35774012-46d11bd2-0989-11e8-8d49-b87319c7f245.png)

If this is desired to be corrected. May I do so?

**Comment by wlach** [comment]
Please do. :) No need to ask!

**Comment by himanish-star** [comment]
Sure I'll do it
