### ISSUE TITLE
Release notes missing for 2.12.0 and 2.13.0

### ISSUE THREAD

**Issue by edmorley** [mozilla/metrics-graphics#800]
Hi :-)

The latest version with a detailed changelog on the releases page is 2.11:
https://github.com/mozilla/metrics-graphics/releases

Could someone add a few notes for 2.12/2.13 to help us know what might change when upgrading?

**Comment by wlach** [comment]
I am probably not going to bother with release notes (unless there's a convenient automagic way to create them? please re-open if you know of one), but producing an auto-changelog seems reasonable, did that here: ef491495002bad10b3ade5080c26203d82822b4c

**Comment by edmorley** [comment]
Works for me, thank you :-)
