### ISSUE TITLE
Travis should support ES6

### ISSUE THREAD

**Issue by lobax** [mozilla/metrics-graphics#815]
As a part of #807 and #811, we need to be able to test the modern ES6 constructs. These will however currently fail on travis, given that travis is configured to run on Node.js 0.10 (which does not support ES6 constructs). 

Proposed solution: Travis should be configured to run on a newer version of Node that supports ES6 (e.g. 8.x)

**Comment by wlach** [comment]
Hmm, the version of node you're specifying in that change looks weird. Could you try to specify the node version as done here:

https://github.com/iodide-project/iodide/blob/ec1dbaba28cd7c3860fd504055831bf91755566f/.travis.yml#L3

Also, in the future when you're working on something like this, just go ahead and make the pull request  (even if it's "broken") -- it'll be easier for me to find the changes and avoids the overhead of having a separate issue. :)

**Comment by wlach** [comment]
I think we're good here, thanks @lobax and co.!
