### ISSUE TITLE
y-axis labels are sometimes misleading when min_y_from_data=true

### ISSUE THREAD

**Issue by openjck** [mozilla/metrics-graphics#821]
### Steps to reproduce

Download and open this [HTML document](https://gist.github.com/openjck/b6e26c027f76c3691533c71a0721578e)

#### Screenshot

![](https://user-images.githubusercontent.com/933396/36760720-f8af953c-1be9-11e8-92a9-af836650db1a.png)

#### Description

The y-axis labels are:

**3**
**3**
**3**

### Expected result

The y-axis labels should be something like:

**3.4**
**3.2**
**3.0**

**Comment by openjck** [comment]
This also appears to happen if `min_y` and/or `max_y` are set manually.

**Comment by wlach** [comment]
This may be doable as a good first issue. It's not trivial, but shouldn't be excessively difficult unless I'm missing something. I think we probably just need to allow showing some of the decimal part on the y axis if the range is small enough.

Instructions on how to contribute to metrics graphics:

https://github.com/mozilla/metrics-graphics#contributing

I would probably start by looking at the y_axis code (maybe adding some console.logs to see what's going on).

https://github.com/mozilla/metrics-graphics/blob/master/src/js/common/y_axis.js

**Comment by cnwangjie** [comment]
I'm working on it.
