### ISSUE TITLE
Gulp "build:js" task generate a wrong dist/metricsgraphics.js UMD formated file

### ISSUE THREAD

**Issue by thomaschampagne** [mozilla/metrics-graphics#825]
Note: Problem as been identified in commit: https://github.com/mozilla/metrics-graphics/commit/5f42d5e7af4eca9d672398bfbf793614855a36d7

---
Since commit https://github.com/mozilla/metrics-graphics/commit/5f42d5e7af4eca9d672398bfbf793614855a36d7, the gulp "build:js" task generate `dist/metricsgraphics.js` umd file with an `undefined` value injected in `root` variable:

```javascript
'use strict';

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['d3'], factory);
  } else if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') {
    module.exports = factory(require('d3'));
  } else {
    root.MG = factory(root.d3); 
  }
})(undefined, function (d3) {  // ============== >undefined <==============
  (typeof window === 'undefined' ? global : window).MG = { version: '2.11' };
```
If we enter in `else` case, then the following error is raised:
```
Uncaught TypeError: Cannot read property 'd3' of undefined
    at metricsgraphics.js:11
    at metricsgraphics.js:13
(anonymous) @ metricsgraphics.js:11
(anonymous) @ metricsgraphics.js:13
```
Expected formated UMD file should be:

`})(this, function (d3) {`

instead of

`})(undefined, function (d3) {`

Like in all previous commits.

**Comment by wlach** [comment]
Hmm, I wonder what the problem is. I'll look into it.

**Comment by thomaschampagne** [comment]
@wlach I have the fix. Do nothing. I will submit you a PR ;)

**Comment by wlach** [comment]
Awesome!

**Comment by thomaschampagne** [comment]
@wlach PR  https://github.com/mozilla/metrics-graphics/pull/826 pushed to fix that
