### ISSUE TITLE
Generated "dist/metricsgraphics.js" throws "Cannot set property 'row_number' of undefined"

### ISSUE THREAD

**Issue by thomaschampagne** [mozilla/metrics-graphics#828]
@wlach Using the current master at commit https://github.com/mozilla/metrics-graphics/commit/b893d05502cdd4f9886deafa3ff98763e48054fb and just generated "dist/metricsgraphics.js", i'm getting the below error on a client app:

```javascript
metricsgraphics.js:3700 Uncaught TypeError: Cannot set property 'row_number' of undefined
    at mg_mouseover_text (metricsgraphics.js:3700)
    at metricsgraphics.js:4887
    at mg_configure_singleton_rollover (metricsgraphics.js:4492)
    at mg_add_single_line_rollover (metricsgraphics.js:4567)
    at mg_line_rollover_setup (metricsgraphics.js:4684)
    at lineChart.rollover (metricsgraphics.js:4860)
    at lineChart.init (metricsgraphics.js:4841)
    at new lineChart (metricsgraphics.js:4953)
    at Object.MG.data_graphic (metricsgraphics.js:825)
    at <anonymous>:100:4
```
I dug in my app code without success...

**And i finally reproduced it on metrics-graphics examples page:**

In `example.htm` i used "dist/metricsgraphics.js" directly instead of importing js file one by one. And this is what i got, same error:

![image](https://user-images.githubusercontent.com/151973/37089546-2cd7489c-2201-11e8-9c8a-8e807bc707b1.png)

Note that:
* I was also able to reproduce this on commit https://github.com/mozilla/metrics-graphics/commit/5538f8c97e18f2c9c01246b0d717932276a5e98b (just before my commit https://github.com/mozilla/metrics-graphics/commit/2aa74205c85f1e7fb06868f84bd5125466dc474e which fixes https://github.com/mozilla/metrics-graphics/issues/825). 
* Wasn't able to reproduce it on tag **v2.13.0**

**Few minutes later...**

After a deeper analysis commit by commit. I detected that the bug comes from this commit: 

0406a62efe672de2454c00ec741bac3438fdca54 "Merge pull request #809 from wlach/use-babel"

**Comment by wlach** [comment]
Probably more fallout from using babel :/ hopefully there is a workaround...

**Comment by thomaschampagne** [comment]
**Another info:**

If you revert my commit https://github.com/mozilla/metrics-graphics/commit/2aa74205c85f1e7fb06868f84bd5125466dc474e _(Use babel before umd step in gulp build pipeline (fixes #825) (#826))_ 

And edit `dist/metricsgraphics.js`  by replacing on line **13**:

`})(undefined, function (d3) {`
by
`})(this, function (d3) {`

to get a valid UMD file... then the bug do not occurs on my chrome v64

**Comment by wlach** [comment]
@thomaschampagne It seems correct to me to use babel before the umd step, let's see if we can't track down the underlying cause.

**Comment by wlach** [comment]
Ok, I think the problem is that `this` in this type of function used to resolve to `window`, but doesn't since we started using babel:

https://github.com/mozilla/metrics-graphics/blob/b893d05502cdd4f9886deafa3ff98763e48054fb/src/js/common/rollover.js#L105

Possible solutions:

1. Switch uses of `this` in cases like this to reference window directly (kind of horrible).
2. Refactor code to not need to pollute global scope in first place (better)

@hamilton do you remember anyone of this? is my understanding of the problem correct?

**Comment by wlach** [comment]
Update: Discussed this with hamilton last week. Fixing this area of the code to use closures, etc instead of relying on a semi-magical `this` object.
