### ISSUE TITLE
Errors: root and MG not defined

### ISSUE THREAD

**Issue by openjck** [mozilla/metrics-graphics#835]
Run [this JS fiddle](https://jsfiddle.net/ouzL498n/). Notice the console errors about `root` and `MG` not being found. This isn't a peculiarity of JSFiddle. It also happens if the file is opened locally.

This didn't happen in the past. If you use a very old commit hash ([example](https://jsfiddle.net/tnkfwab3/1/)), this will work.

**Comment by wlach** [comment]
This is due to https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github I believe.

Using rawgit.com seems to work. e.g.

https://jsfiddle.net/ouzL498n/8/

**Comment by openjck** [comment]
I'm a little confused. The [original JS fiddle](https://jsfiddle.net/ouzL498n/) is using *rawgit.com* and it looks like [yours](https://jsfiddle.net/ouzL498n/8/) is using a different commit from the *wlach-dist-test* branch.

**Comment by wlach** [comment]
argh, I misdiagnosed the problem. I regenerated the files in dist/ and pushed them to a branch where I experienced the above error. Commit 43b73b64a1ea1e03069a6010965eec644a589a63 must be the culprit, which I guess a subsequent change (probably 2aa74205c85f1e7fb06868f84bd5125466dc474e) fixed.

**Comment by openjck** [comment]
Did 2aa7420 fix it? I'm still seeing the bug on 2aa7420 and on the latest master.

**Comment by wlach** [comment]
@openjck we haven't regenerated the files in dist/ since 2aa7420 was fixed, so it is expected that we'll still be failing until that's done

**Comment by openjck** [comment]
Ah I see. Works for me. :smiley:
